waddrmgr/manager.go

A rare panic could occur importing multisignature scripts found in the
blockchain that were unconfirmed. This avoids the nil dereference that
causes the panic.
Fixes #26

Fix a rare panic importing discovered multisignature scripts

---

walletsetup.go

Allow wallet to accept hex or words as seed.

---

rpcserver.go
wallet/createtx.go
wallet/wallet.go

This will provide a way in which users can see what their fee is currently set to while creating transactions.   
dcrctl --wallet getwalletfee 
will return w.FeeIncrement value

Add rpc cmd to return currently set fee increment

---

rpcserver.go
wallet/chainntfns.go
wallet/createtx.go
wstakemgr/db.go
wstakemgr/stake.go

This update allows the per-ticket setting of the VoteBits field so
that different VoteBits settings can be user selected in stake pools.
It is backwards compatible with the former VoteBits selection method
on the command line. Tickets stored before this update will continue
to use the VoteBits selection from the command line. Tickets stored
after this update will be initialized with the VoteBits selection from
the command line and then be able to be updated by the RPC. After
updating, any votes cast with that ticket will be assigned the
per-ticket, user selected VoteBits instead of the default VoteBits.

Add individual ticket setting for VoteBits via the RPC

---

waddrmgr/db.go
waddrmgr/manager.go
wallet/addresspool.go
wallet/chainntfns.go
wallet/wallet.go

The address pool would fail to restore to the correct index when
restoring from a wallet seed. This was fixed by adding better tracking
of the address index in the wallet. A large portion of the code in
address pool was refactored for both clarity and concision. Some
code handling storing of the next to use address in the address manager
was also refactored to expand its use case and to make its role in
syncing the address pool clearer.
Fixes #35.

Fix bug in the address pool when restoring from seed

---

wallet/addresspool.go

This was caught when further testing master on TestNet. Now the mutex for the address pool should be initialized when wallet starts and the struct is instantiated.

Hotfix for rare panic caused by uninitialized mutex

---

rpcserver.go
wtxmgr/query.go

getstakeinfo caused issues on the stake pool because of very slow performance.
The speed of the RPC call has been improved by reading more local information
instead of fetching it from the remote daemon.

Increase the performance of getstakeinfo

---

wallet/chainntfns.go

A bug in multisignature handling would occasionally cause the
inappropriate failing of transactions being added to the transaction
manager. If a multisignature script of any kind was found but a
reference to the script could not be found in the transaction
manager, the whole function would fail. The error returned from
the function is now ignored because failing to find a multisignature
output to spend for a random multisignature script should not be
considered an error.

Fix bug in multisignature output spending in chainntfns.go

---

wstakemgr/stake.go

In the case of redundant wallets, votes and revocations that were
rejected from the daemon as duplicates were not stored at all in
the stake database. This would cause corrupted values for votes
and revocations when calling getstakeinfo. This was corrected by
storing the votes and revocations first, before shipping to the
daemon.

Fix a bug that caused votes and revocations not being stored

---

wallet/chainntfns.go
wtxmgr/tx.go
wtxmgr/unconfirmed.go

The wallet had no way to remove expired transactions from the internal
memory pool. Tickets that were lower than the current stake difficulty
were also never removed. Automatic pruning of these transactions on a
per block basis has been added, allowing the wallet to recover and
respend these funds. The function removeConflict has also been 
renamed to removeUnconfirmed to better describe its activity.
Fixes #3.

Automatically remove old tickets and expired transactions

---

wstakemgr/stake.go

If a ticket was used to generate multiple votes, DumpSSGenHashes would
only load the first vote generated. The wstakemgr/stake.go code now
loads all vote hashes, so that the number of votes are counted
correctly in getstakeinfo.

Fix bug displaying the wrong number of votes in getstakeinfo

---

rpc/legacyrpc/methods.go

The 'voted' field used to include all votes in the wallet,
even if they had failed to ever get into the blockchain.
Now only votes that entered the blockchain are considered
for the 'voted' field.

Change 'voted' in getstakeinfo to only return blockchain votes

---

internal/prompt/prompt.go

This fixes the behavior for dcrwallet that was lost in the latest
btcwallet sync.
Fixes #83.

Display seed using the PGP Word List.

---

rpc/legacyrpc/methods.go

This fixes the unsafemainnet option so it only affects mainnet.  This
broke as part of the recent btcwallet sync as the entire feature had
to be rewritten for the new legacyrpc package.
Fixes #85.

Only enable mainnet RPC method safety check on mainnet.

---

dcrwallet.go

Since the stop RPC and ^C interrupt handling now shutdown the process
using the same code path, the closeDB callback needs to stop any
remaining uses of the database before closing the DB.
This should prevent any database corruption issues that may happen
during clean shutdown, but unclean shutdown can still corrupt the
database since not all operations that should be atomic actually are.

Stop uses of database before closing db.

---

wallet/addresspool.go
wallet/wallet.go

Add call to pool.BatchComplete() at the end of GetNewAddress()
to prevent address counter from being reset when it shouldn't.
Fixes #68
Also correct a comment typo in GetAddress code.

Prevent addresses from being shown more than once.

---

wallet/chainntfns.go
wstakemgr/stake.go

This reverts commit 9fc2eeea1275bf310951abcb32aae888d74685ae.
We are revert sync to 0208a commits due to possible consensus issues.
We will now break down each btcd sync commit into piecemeal commit PRs to avoid this in the future

Revert "Fixes to work with dcrd sync"

---

wallet/chainntfns.go
wallet/wallet.go

A call to UnspentOutpoints did not have error handling, which was
added.
A restrictive switch statement would cause all outputs that were not
either pay-to-pubkey hash or pay-to-script-hash multisig to be stored.
This was reverted to the same behavior as btcwallet where all outputs
are stored if the address is found in the address manager. Code
handling multisignature redeemScript lookup in outputs was also
corrected.

Fix a bug relating to relevantTx handling and uncaught error

---

config.go
rpc/legacyrpc/methods.go
wallet/addresspool.go
wallet/chainntfns.go
wallet/createtx.go
wallet/wallet.go
wtxmgr/db.go
wtxmgr/error.go
wtxmgr/example_test.go
wtxmgr/query.go
wtxmgr/query_test.go
wtxmgr/tx.go
wtxmgr/tx_test.go

Redesign UTXO storage of accounts in DB, fix accounts
Accounts were extremely broken in terms of both spending from them
and finding their balances. This pull request fixes a large number
of issues with them.
- The database now stores the pkScript locations, size, and account
types. This speeds up pkScript and account pull down immensely,
and is backwards compatible with the old database format. The
database version has been bumped to 2.
- Balances are now calculated for accounts through the wtxmgr's
database instead of using the old, slow functions.
- Spending from an individual account has been fixed by refactoring
the unspentOutputsForAmount function to properly find UTXOs for
accounts.
Builds on #103, fixes #50, #46, #22, and #2.

Overhaul accounts to function correctly

---

config.go
rpc/documentation/clientusage.md
sample-dcrwallet.conf

Fixes issue https://github.com/decred/dcrwallet/issues/99

Fix all rpclisten references in documentation

---

rpc/legacyrpc/methods.go
wallet/addresspool.go
wallet/wallet.go

Some changes that were acquired when syncing to btcwallet caused
resyncing from seed to fail to correctly place the initial address
index in address pool, resulting in gaps. This has been fixed and
a new debug function added to assist in debugging wallet address
gaps. Tolerances on address gaps for the initial rescan have been
loosened to help correctly scan old wallets that may have had gaps
introduced.
A bug that could also introduce gaps was found in the
getrawchangeaddress RPC call, which used the wrong function to
get change addresses for default or imported accounts. It now
uses the correct function.

Fix wallet resyncing from seed and address index positioning

---

internal/rpchelp/helpdescs_en_US.go
rpc/legacyrpc/errors.go
rpc/legacyrpc/methods.go
wallet/chainntfns.go
wallet/wallet.go

This will now allow users to update balancetomaintain while wallet is running.
Also make balanceToMaintain into unexported and restrict access to normal get/setters.

Add new balancetomaintain rpc command

---

dcrwallet.go

This makes btcwallet match btcd's behavior.
Initially pointed out in:
decred/dcrwallet#125
Closes #125

Print version string at startup.

---

wtxmgr/tx.go

Wallet would fail to update UTXOs for imported address outputs while
rescanning after using importprivkey or importscript if the transaction
already existed in the database. The new code is rearranged to always
update spending data even if the transaction already exists.
Fixes #132.

Fix updating the UTXO set for imported addresses

---

wallet/chainntfns.go

Wallet would sometimes drop or mishandle notifications that came in
synchronously when wallet was doing a resync. This ensures the resync
has been completely before launching notification handling.

Help prevent errors during initial sync by waiting for it to finish

---

rpc/legacyrpc/methods.go

getstakeinfo: fix proportionMissed calculation
The calculation in the rpc request was incorrect.  
Was: missed/poolsize + missed.
Now: missed/voted + missed
Fixes #105

Fix proportionmissed calc --> missed / missed + voted

---

config.go
dcrwallet.go
internal/prompt/prompt.go
waddrmgr/db.go
waddrmgr/error.go
waddrmgr/manager.go
wallet/addresspool.go
wallet/chainntfns.go
wallet/createtx.go
wallet/loader.go
wallet/sync.go
wallet/wallet.go
walletsetup.go

The old address pool code was faulty in that it could not scale to
more accounts than the default account and did address index alignment
using an actual address instead of an index. This updates the address
pools to be generalized so that in the future they can be multiaccount.
Address indexes for an account are now stored in the meta bucket of the
address manager database. The logic for the address pool has been
greatly simplified.
Accounts are now restored when the wallet is restored from seed. New
logic similar to the logarithmic scan for addresses in the default
account has been added. On start up, the wallet will also rescan and
check for new address usage in all of its used accounts. The wallet
must be able to connect to the daemon immediately after creation from
seed to be able to …

Refactor address pool code and automatically resync accounts from seed

---

dcrwallet.go
wallet/loader.go
wallet/sync.go
wallet/wallet.go

Password prompting on first run or when --promptpass has been
set now prompts before the RPC server has started. If the wrong
password is entered, the user is reprompted to enter their
password.

Modify the logic for password prompting

---

dcrwallet.go
wallet/addresspool.go
wallet/createtx.go
wallet/loader.go
wallet/sync.go
wallet/wallet.go

Add safety checks for address pool access
Address pool access now has checks to ensure that the address
pool exists and has been initialized before calls accessing its
functions or internals.

Fix address pool panics on start up

---

chain/chain.go
goclean.sh
internal/helpers/helpers.go
internal/rpchelp/methods.go
rpc/rpcserver/server.go
snacl/snacl.go
waddrmgr/manager.go
wallet/rescan.go
wtxmgr/query_test.go
wtxmgr/tx_test.go

This commit corrects various things found by the static checkers
(comments, unkeyed fields, return after some if/else).
Add generated files and legacy files to the whitelist to be ignored.
Catch .travis.yml up with btcd so goclean can be run.

Add goclean.sh script from btcd.

---

wallet/wallet.go

Before, stake txscript types were being avoided so they were not being flagged as spendable, which would result in them being left out of ListUnspent response
Fixes #131

Add stake txscript types in ListUnspent to be spendable

---

walletdb/bdb/db.go

This fixes a deadlock where failed transactions due to the namespaces'
bucket being missing would cause deadlocks due to bolt's mmap rwmutex
still being read or write locked (and no way to unlock it, since the
underlying bolt tx was not returned on failure).

Rollback namespace transactions when bucket is not found.

---

dcrwallet.go

A bug where the password was prompted for on a new watching only
wallet start up caused the watching only wallet to never sync.
Now the password check is skipped. Fixes #148.

Fix watching only wallets

---

.travis.yml

The vet tool moved to the Go tree as of go1.5 so it does not
need to be installed seperately.  With the x/tools repo now gone,
remove the install step for vet since it fails.

Update TravisCI configs. (#409)

---

cmd/sweepaccount/main.go
internal/cfgutil/amount.go

This tool creates on-chain transactions, one per used address in a
source account, to sweep all output value to new addresses in a
different destination account.
This is a cherry-pick of the btcwallet commit 4ee9ce59fba801ff5036de35afac67b61e6247cc.

Add sweepaccount tool.

---

wallet/sync.go

An ErrSyncToIndex error when calling SyncAccountToAddrIndex simply
indicates that the address manager is ahead of the address pool
index, which is not an error causing any issues. This error is now
caught and skipped.
Fixes #174.

Fix bug in syncing to address index

---

wallet/addresspool.go

I was doing some testing of auto-synchronizing of wallets and noticed that a wallet synced from seed had an off by one where address 21 was in place of address 20:
wallet1:
[DBG] WLLT: Get new address for branch 0 returned TsVtthQ8ivLETX7AK1AWzaXawSxwgkrpgSb (idx 19) from the address pool
[DBG] WLLT: Get new address for branch 0 returned TsbPAa7m2dJ2y6b3Nsbrr2jECmcM4my4PP3 (idx 20) from the address pool
wallet2:
[DBG] WLLT: Get new address for branch 0 returned TsVtthQ8ivLETX7AK1AWzaXawSxwgkrpgSb (idx 19) from the address pool
DBG] WLLT: Get new address for branch 0 returned TsbPAa7m2dJ2y6b3Nsbrr2jECmcM4my4PP3 (idx 20) from the address pool
newly synced wallet3:
WLLT: Get new address for branch 0 returned TsVtthQ8ivLETX7AK1AWzaXawSxwgkrpgSb (idx 19) from the address pool
[DBG] WLLT: Get …

fix off by one when initializing a wallet

---

config.go
dcrwallet.go
wallet/loader.go
wallet/sync.go
wallet/wallet.go
walletsetup.go

The new RPC function existsaddresses is not used in place of
existsaddress, which should enhance the synchronization speed of
dcrwallet on restore from seed and start up.
A new flag has been added to allow users to optionally set their 
final address index scan lengths.

Refactor address index syncing code

---

version.go

Change wallet from alpha to beta.  Since wallet is used
in production this seems more accurate at this time.

Bump for v0.1.0

---

wallet/createtx.go
wallet/wallet.go

Automatic ticket purchases by the wallet could cause excessive usage
of the default account internal branch because the address for the
split transaction outputs was created using the exported new address
function for the wallet. The API for txToOutputs has been modified and
a new function that calls it, TxToOutputs, created. This new function
does all the locking required, so that the internal function txToOutputs
may be called by other functions in wallet that already have the
relevant locks held.

Isolate address pool to prevent excessive address creation

---

wallet/sync.go

The final address index scan length was accidentally removed
during a previous rebase. It has been reinserted to be the
variable declared on the command line.

Reinsert scan length variable

---

wallet/txauthor/author.go
wallet/txauthor/author_test.go

Due to the way dust is calculated, if the transaction relay fee is
zero, then a zero output amount is not considered dust.  As the
transaction authoring code used this dust check to determine whether a
change output can be included or not, it could create unnecessary
change outputs which return no value back to the wallet.  Prevent this
by including an explicit check for zero values.

Do not include zero value change outputs.

---

wallet/createtx.go
wallet/wallet.go

This will fix issues with allowhighfees checking in dcrd on testnet/simnet

Add TicketFeeIncrementTestnet

---

rpc/legacyrpc/methods.go

The purchaseticket RPC would previously fail if the ticket address
or pool address was undeclared (), not allowing the end user to
set the ticket expiry if either was absent. This corrects this
problem by skipping assignment if it is .

Allow passing an empty string for purchaseticket addresses

---

config.go
dcrwallet.go
wallet/chainntfns.go
wallet/loader.go
wallet/wallet.go

The automatic ticket purchase frequency has been changed to default
to 1. The frequency can be changed with the command line argument
--ticketbuyfreq=.

Add ability to change autopurchase frequency

---

wallet/loader.go

This fixes a dcrwallet-specific bug introduced by
4b64adf52f873a4ec5237d3fb16b5252ddef3846 which removed the call to
wallet.Open from wallet.Loader.CreateNewWallet, replacing the wallet
pointer with nil, and removes the addition of a call to close the
wallet database.  The introduction of a nil pointer caused runtime
panics when executing Loader callbacks that dereferenced the wallet
pointer, and by the caller who would dereference the return value.
This makes the LoaderService.CreateNewWallet RPC useful again.

Open and return wallet from CreateNewWallet.

---

pgpwordlist/pgpwordlist.go

Remove btcd/wire dependency.

---

glide.lock

I must have missed this during the sync merge.

Fix glide.yaml hash in glide.lock.

---

wallet/createtx.go

Tickets could sometimes be purchased at the wrong price if the
wallet was not yet synced to the best block. Instead, fetch the next
price from the daemon and use that instead.

Call the more reliable GetStakeDifficulty for ticket prices

---

wallet/chainntfns.go
wallet/wallet.go

Two bugs relating to reorganizations were fixed. The first was an off
by one bug on initial sync which rarely would ever affect the end user.
The second was that logic causing the removal of all blocks to the
genesis block on a disconnection of an unknown block would cause
irreversible corruption of the wallet. The new code ignores the hash
of the block to remove and assumes that daemon removing blocks to some
common unknown forking point between the daemon and wallet before
connecting the side chain's blocks.

Fix bugs relating to reorganizations

---

.travis.yml

This ensures that the vendor experiment is enabled when building not
just dcrwallet, but glide itself as well (glide vendors dependencies
and checks them into its git repo).
While here, switch from using 'go get $(glide novendor)' to 'go
install . ./cmd/...' to build the project and all related commands.
This won't hide errors when glide fails to restore a required
dependency or the vendor experiment is disabled.

Enable vendor experiment earlier in travis script.

---

rpc/legacyrpc/methods.go
wallet/createtx.go
wallet/wallet.go

While here, fix an error in legacyrpc's redeemMultiSigOut function
which used the default relay fees and ignored the wallet's current
settings.

Use same fee policies across all networks.

---

dcrwallet.go
wallet/sync.go
wallet/wallet.go
wstakemgr/feeest.go
wstakemgr/stake.go

The fee calculation for revocations was stuck at a very high fixed
rate. The fees for revocations are now calculated on a per kilobyte
basis. The wallet now also triggers winner and missed ticket
notifications on start up, so that revocations for tickets that
were missed while the wallet was offline will be triggered when
the wallet is started.
Fixes #51.

Fix fee calculation for revocations and rebroastcast on start up

---

wallet/loader.go

This allows consumers of wallet.Loader to use the type without needing
to import the database driver themselves.

Import bdb driver from wallet package.

---

prompt/prompt.go

This makes the internal prompt.Setup function available for use in
other projects.
Fixes #272.

Add non-internal prompt package.

---

wtxmgr/tx.go

Including unspendable inputs could occasionally cause old
wallets to not be able to send coins. This PR should prevent
that.

Skip zero value outputs when making transactions

---

wallet/sync.go

This is only encountered if the daemon for some reason decides to send an empty 
response.

Fix an unlikely panic if the bitset returned is empty

---

walletsetup.go

watch-only: Delete created wallet.db if the WoW wasn't created

---

rpc/rpcserver/server.go
wtxmgr/tx.go

The minConf and syncHeight variables were swapped in all calls
to balance functions in AccountBalances.

Fix balance bug in AccountBalances

---

rpc/documentation/api.md
rpc/rpcserver/server.go
wallet/addresspool.go
wallet/wallet.go

Accounts would formerly return the index of the address buffers
for the address manager instead of the last used address index.
The correct value is now set and the version for the gRPC bumped
to 2.2.1

Fix gRPC account address index responses

---

config.go
dcrwallet.go
sample-dcrwallet.conf
wallet/createtx.go
wallet/loader.go
wallet/wallet.go
walletsetup.go

Fixes #211
Now users can either set them on startup with --txfee and --ticketfee
flags or set them in their dcrwallet.conf.  If unused they will default
to 0.01 as before and are using the previous defaults in txrules and
wallet

config: Add txfee and ticketfee to available config settings

---

wallet/wallet.go

Calling wallet.StakeDifficulty or wallet.StakeInfo would cause a panic if the daemon was not connected to the wallet. Now the chain client is loaded by the disconnection-safe w.requireChainClient.

Fix panic when getting StakeDifficulty if dcrd disconnected

---

waddrmgr/manager.go

waddrmgr: check extended pubkey network when creating a WoW.

---

wtxmgr/tx.go

The UTXO notification logic needs to be moved from the transaction
manager to the wallet so that it doesn't cause lockups. The offending
code has been commented out.

Fix lockup by breaking UTXO notifications

---

glide.lock
glide.yaml

Add 'version: master' to all btcsuite and decred projects, since we
always want the latest versions of these.  This works around a bug in
the latest version of glide where it does not track the master branch
correctly.
Update gRPC for the 1.0.0 release and update bolt to 1.3.0 to pick up
a fix for a memory handling error that was exposed by the Go 1.7 SSA
compiler backend.
Fixes #325.
Fixes #328.

Update project dependencies.

---

rpctest/node.go

database update requires `--txindex` for `getrawtransaction` to function.  This means rpctest/rpcharness requires this as a node argument.
This is included in https://github.com/chappjc/dcrwallet/tree/rfp10-m2 but should probably make it into 0.4.0.

Add --txindex to node args.

---

rpctest/.gitignore
rpctest/mkharness/main.go
rpctest/node.go
rpctest/rpcharness.go
rpctest/rpcharness_test.go
rpctest/walletnode.go
version.go
wallet/addresspool.go
wallet/createtx.go
wallet/sync.go
wallet/wallet.go

Milestone 2 of RFP-10 includes the following legacy RPC tests:
Note that transaction fee (aka relay or wallet fee) and ticket fee gets are tested via walletinfo since there are no more direct methods available via dcrrpcclient.  Wallet.RelayFee() is the shared underlying call.  The milestone 3 test, purchaseticket, is also completed.
Final tasks:
This PR also includes the addition of the mkharness command (dcrwallet/rpctest/mkharness/main.go), which brings up a simnet node and wallet configured for mining.  Once set up, mkharness will print the commands for the running node and wallet, and suggested dcrctl command constructions.
Some questions and possible TODO:
* In comparing nominal vs actual/observed fees, an arbitrary tolerance is used.  absFeeDiffTolerance = 0.0005  Is this …

RFP-10 Milestone 2

---

wtxmgr/db.go
wtxmgr/tx.go

While version 2 was added a long time ago, there was never a database
version bump for the new format when there should have been.  After
the database atomicity changes landed, the version checks became
stricter.  To accomidate very old wallets that still record the
version as 1 even though they have been writing using version 2 all
this time, a new upgrade path was added that bumps the version.  No
other upgrade logic is required here as the new format was forwards
compatible with the old format.
Fixes #357.

Upgrade wtxmgr from version 1 to 2.

---

config.go
dcrwallet.go
glide.lock
rpc/legacyrpc/methods.go
wallet/chainntfns.go
wallet/createtx.go
wallet/loader.go
wallet/tickets.go
wallet/wallet.go
wstakemgr/db.go
wstakemgr/error.go
wstakemgr/stake.go
wtxmgr/db.go
wtxmgr/tx.go

This fixes the TODO where wallet could not do the setting of extended
vote bits.  A new function allowing for the setting of multiple vote
bits for many tickets was also added.
The wallet is also updated to the latest dependencies.  Fixes #363.

Update the wallet to begin allowing extended votebits setting

---

rpc/legacyrpc/methods.go
wallet/tickets.go
wstakemgr/db.go
wstakemgr/stake.go

Prior to this there was no updating of PoolTicket state when manually using AddTicket for formerly invalid tickets.  Now they are properly removed from the invalid slice and a new PoolTicket is added to the valid slice.  This along with some more upgrades will help stakepool operators ensure that all of their wallets are in sync with one another.

Fully update PoolTickets when using AddTicket rpc

---

rpctest/doc.go
rpctest/node.go
rpctest/rpcharness.go
rpctest/rpcharness_test.go
rpctest/walletnode.go

Requires unmerged dcrrpcclient PR: https://github.com/decred/dcrrpcclient/pull/35 (and an updated glide.yaml/glide.lock).
Milestone 3 of RFP-10 includes the following legacy RPC tests:
Note that there are no getticketmaxprice or getbalancetomaintain commands and as such walletinfo is used to test the mutators.

RFP-10 milestone 3

---

dcrwallet.go
wallet/notifications.go
wallet/wallet.go

Nothing ever set this value to true, and this was causing the wallet's
notification server to prematurely notify attached blocks, breaking
gRPC block notifications during chain switches and reorgs.

Remove Wallet.ChainSynced/SetChainSynced APIs.

---

chain/chain.go
chain/semver.go
dcrwallet.go
glide.lock

While here, improve the error returned by RPCClient.Connect to include
both the required and advertised API versions.  These versions are
independent of the program and/or project's release versions, but it
should still be useful in determining whether dcrd must be downgraded
or upgraded for compatibility with this wallet software.
Add a 30 second sleep after any connection or compatibility errors
(where compatibility errors are not just incorrect API versions, but
mismatched currency networks as well).  This prevents an immediate
reconnect to the server.
Fixes #379.

Fix a bug in the semver compatibility check.

---

wallet/sync.go
wallet/wallet.go

Errors are no longer hidden by returning in-band values.  Explicit
checks have also been added to test for hdkeychain.ErrInvalidChild
rather than assumming that any random error is an invalid BIP0032
child key derivation.
Some vars that didn't need to be were changed to const and moved to
the top of the file.
Use uint32 everywhere for indexes rather than mixing int and uint32
(I'm guessing this was largely thanks to Go's "type inferrence" rules
which default to int).  Removes a lot of unnecessary type conversions
and makes the code a little less cluttered.
Since all of this code requires the consensus server RPC client, just
pass it in as a parameter and pass it around to all of the helper
functions instead of calling Wallet.requireChainClient from most of
them.

Marginally clean up acct/addr discovery code.

---

rpc/documentation/api.md
rpc/rpcserver/server.go
wallet/chainntfns.go
wallet/notifications.go

Fixes duplicate tx notifications discovered when performing seed
restoring, jumps from 0 to 2 depth transactions, and probably other
bugs as well.
Bump the gRPC API patch version for this fix.
Fixes #402.

  Move decision to send attached block notifications to caller.

---

rpc/documentation/api.md
rpc/rpcserver/server.go

Require seed parameter for LoaderService.CreateWallet RPC.

---

rpc/documentation/api.md
rpc/rpcserver/server.go
wallet/loader.go

This prevents future calls to CreateNewWallet from erroring due to the
database file existing.
Fixes #418.

Remove database if wallet.Loader.CreateNewWallet errors.

---

.travis.yml
goclean.sh

While here update to the latest Go and use a glide release rather than
the latest development version.
Fixes #421.

Reenable tests on travis.

---

glide.lock
rpc/legacyrpc/methods.go
rpctest/rpcharness_test.go
wallet/chainntfns.go
wallet/createtx.go
wallet/tickets.go
wallet/txrules/poolfees.go
wallet/wallet.go
wstakemgr/db.go
wstakemgr/stake.go
wtxmgr/common_test.go
wtxmgr/stakevalidation_test.go
wtxmgr/tx.go

While here, go ahead and update all of the decred deps, and go-spew.
This is required to pull in a change to dcrjson.  Refs #405.

Pull in latest dcrd version.

---

wallet/wallet.go

The wallet.Create func was not creating the transaction manager
bucket.  With dropwtxmgr now gone, the wtxmgr namespace is now always
required.
Fixes #436.

Fix --create by creating the transaction manager.

---

goclean.sh

This just clutters the logs and makes it more difficult to determine
what the actual failing test was.  For tests that do fail, all logs
from the test is already outputted.

Remove -v from go test on travis.

---

rpc/documentation/clientusage.md

While here, switch the indentation of the node example to use two
space indents since this is common practice in javascript.
Fixes #443.

Fix possible exceptions in example gRPC clients.

---

config.go
dcrwallet.go
log.go
sample-dcrwallet.conf

This changes the --profile option from taking just a port and opening
the HTTP profiler on all interfaces, to requiring a listen address.
The old behavior can be restored by using ':port' instead of 'port'.
Fixes #404.

Change --profile to take a listen address (or many).

---

config.go
dcrwallet.go

This will allow attaching stdin as the receive end pipe for a child
dcrwallet process.  Particularly useful for applications that are
unable to create pipes for one reason or another.
Closes #451.

Allow --piperx=0 (stdin).

---

rpc/documentation/api.md
rpc/rpcserver/server.go

Verify that addresses are intended for the active net.

---

ticketbuyer.go

This addresses an issue discovered in #466 
Updated to cleanup and exit the purchaser when a chain client is disconnected.

ticketbuyer: Stop purchaser on client shutdown

---

config.go
dcrwallet.go
rpc/legacyrpc/methods.go
ticketbuyer.go
ticketbuyer/purchase.go
wallet/chainntfns.go
wallet/loader.go
wallet/wallet.go
walletsetup.go

An --enableticketbuyer option has been added.  It must be used to
enable the new ticket buyer.
An --enablevoting option has been added to turn on the wallet's
automatic creation of vote and revocation transactions when using the
new ticket purchaser.
The --enablestakemining option has been deprecated for the above two
options.  To use the old ticket buyer from the wallet package, use
this option and do NOT set --enableticketbuyer (doing so would enable
the new ticket buyer).
All RPCs to interact with the ticket buyer remain, but only affect the
old deprecated ticket buyer, and are also deprecated by extension.
Fixes #468.

Allow running either the new or old ticket buyer.

---

ticketbuyer.go
ticketbuyer/purchase.go
wallet/chainntfns.go
wallet/notifications.go

Improve efficiency of triggering the ticket buyer.

---

wallet/wallet.go

This changes the logged votebits when logging that wallet ticket
purchasing is enabled to always display with leading 0s.  For example,
currently for a votebits value of 1, it will be logged as 0x1.  This
changes it to be logged as 0x0001.

Slightly improve logging formatting.

---

glide.lock

Update 3rd party glide deps (and some internal ones) for 0.8.0

---

rpc/documentation/api.md
rpc/rpcserver/server.go

Bump patch version for bugfix.
While here, remove the patch version from the API spec documentation.
The spec does not cover bugfixes.
Fixes #505.

Prevent panic caused by nil output destinations.

---

config.go
sample-dcrwallet.conf
ticketbuyer/buyer.go

successfully tested this commit on testnet
edit: The idea behind highpricepenalty was presumably to reduce volatility, but in practice it did not work as we can see see from the ongoing high volatility. It was also misaligned with user incentives since it would only cause people to still buy overpriced tickets. It seems most people were just disabling it. Also bad was that the code was very buggy and cumbersome. So, it is being removed. A simple dynamic max price setting is being added to be sure to protect users from buying expensive tickets when they are just running the default config. With this, we can move forward and start looking at other possible ways to reduce volatility that work, while keeping user profits optimized. 
This also fixes the problem caused by the ticket queue where …

add dynamic max price default, remove highpricepenalty queue

---

config.go
sample-dcrwallet.conf
ticketbuyer/buyer.go

Change default so as to not unintentionally join bidding wars.
Do not buy tickets when scaled fee exceeds your specified maxfee.
Closes https://github.com/decred/dcrticketbuyer/issues/71

make maxfee behavior sane

---

config.go
sample-dcrwallet.conf
ticketbuyer/buyer.go
ticketbuyer/mempool.go
ticketbuyer/purchase.go

successfully tested this commit on testnet
Spreads user buys evenly throughout window. Will reduce the rush of competing buys that happen when a new window begins. Will reduce cost of ticket prices. Will help to better estimate the next stake difficulty.

spread buys evenly throughout window, new default behavior

---

dcrwallet.go
ticketbuyer/purchase.go
wallet/loader.go

Purchase workers were trying to read the db after shutdown, causing panic.
Fixed by returning the worker when quit signal is received.
Fixes #482

ticketbuyer: Fix panic on shutdown

---

config.go

This is a breaking change to anyone who is setting votebits from the
hidden --votebitsextended option.  The new option should not contain
any version info.

Set version in extended vote bits per network.

---

wallet/chainntfns.go
wallet/wallet.go
wstakemgr/stake.go

When not in stake pool mode, use the config setting of voteBits instead of anything saved in the sstx record.
We will also still need to fix a way for stakepool users to seamlessly update their vote bits when versions are bumped.

Add stakePoolEnabled check

---

cmd/sweepaccount/main.go
glide.lock
glide.yaml
internal/prompt/prompt.go

This change adds support for illumos (and probably Solaris) operating
systems by switching from the outdated btcsuite fork of
golang.org/x/crypto/ssh/terminal to the upstream repo.
Closes #556.

Add illumos support.

---

.travis.yml
README.md
wtxmgr/tx_test.go

Go 1.8 is out and by policy we only support the latest two Go releases.

Add Go 1.8 support, remove 1.6.

---

version.go

By default, put 'dev' in the prerelease field.
For release builds we can add 'release' with the build scripts.
Update comment for current (post 1.5) usage on ldflags -X while
there.
Closes #577

Differentiate dev and release in -V

---

wstakemgr/stake.go

Previously it was incorrect pulling extended vote bits from the database which
caused mangling of extended vote bits, which in turn, caused invalid vote versions.

Fix extended vote bit setting for stakepool wallets

---

dcrwallet.go
loader/doc.go
loader/errors.go
loader/loader.go
loader/log.go
log.go
rpc/legacyrpc/server.go
rpc/rpcserver/server.go
rpcserver.go
ticketbuyer/purchase.go
walletsetup.go

As mentioned in #463 we need a way to start/stop the ticketbuyer purchaser over gRPC.
This PR allows the loader to be re-usable from `pkg loader`  so as to handle ticketbuyer services to be stopped/started similar to the current handling of wallet load/unload.

loader: Move Loader to new pkg loader

---

glide.lock
glide.yaml
snacl/snacl.go
wallet/createtx.go
wallet/udb/txdb.go
wallet/udb/txmined.go

The github.com/btcsuite/golangcrypto fork is still being pulled in due
to dcrd deps, which will also have to be switched over.

Switch to upstream golang.org/x/crypto package.

---

glide.lock

This also removes the last traces of github.com/btcsuite/golangcrypto
which was previously being pulled in as a dep of a dep.

Update Decred dependencies.

---

wallet/udb/txmined.go

- Include immature coinbase credits
- SSTXs are not coinbase rewards
- Also include unconfirmed in the total.
- Correctly add normal transactions to Spendable when minConf==0
- Handle unmined stake transactions properly.

getbalance: additional balance fixes

---

wallet/udb/addressmanager.go
wallet/udb/initialize.go
wallet/udb/migration.go
wallet/udb/open.go
wallet/udb/stakevalidation_test.go
wallet/udb/txcommon_test.go
wallet/udb/txdb_test.go

This new method takes a read-only database transaction, rather than
the bucket.  This differs from the rest of the API which currently
takes namespace buckets themselves, but this is the direction that I
want to take the API.
To remove some generated garbage created by creating the bucket key
bytes, do the conversion once and save the keys as package variables.
Use these consistently across the entire package.
Closes #602

Add method to retrieve an account branch xpub.

---

rpc/rpcserver/server.go
wallet/createtx.go
wallet/notifications.go
wallet/udb/stakedb.go
wallet/udb/tx_test.go
wallet/udb/txcommon_test.go
wallet/udb/txmined.go
wallet/udb/txquery_test.go

While here, convert existing NewBuffer(make()) users to Grow().

Preallocate the exact number of bytes if known.

---

config.go

Done in a loop so future testnets can be added in as needed.
Closes #620

Add warning on startup about old testnet data.

---

rpc/legacyrpc/server.go
snacl/snacl.go

Drop fastsha256 usage in favor of crypto/sha256

---

wallet/sync.go

This fixes a panic when deriving discovered accounts where 1 would be
subtracted from account number 0 and would continue trying to create
account 0xFFFFFFFF, which is invalid.

Fix derivation of discovered accounts.

---

wallet/addresses.go

We will need to add settings and parameters for the user to choose
what to do in this case.  For now, revert back to the old behavior of
wrapping around to the address after the last used address.

Revert to old wraparound behavior.

---

rpc/documentation/api.md
rpc/rpcserver/server.go

When started with `--noinitialload`, the loader chain client is not being set, causing RPC calls from Paymetheus to fail.
Fixed by setting the loader chain client in `StartConsensusRpc`.

rpc: StartConsesusRpc - set loader chain client

---

rpc/legacyrpc/methods.go
rpc/legacyrpc/server.go
rpcserver.go

This fixes panics caused by dereferencing a nil wallet to determine if
an RPC that requires the --unsafemainnet flag when mainnet is the
active network.  The fix is to pass in the active network parameters
to the RPC server and use those rather than trying to access them
through the nil wallet.
Fixes #650.

Prevent panic in JSON-RPC server.

---

rpc/legacyrpc/context.go
rpc/legacyrpc/server.go
rpcserver.go

Begin adding context parameters to the JSON-RPC server internal
methods.  The client's remote address is added to each request
context.
Improve other JSON-RPC server logs by including the client's remote
address.
For the gRPC server, intercept all streaming and unary RPCs and log
the peer IP and method that was called.

Log RPC method invocations.

---

rpc/documentation/api.md

This change was missed in a previous commit.

Bump API version in documentation.

---

wallet/wallet.go

Dereference the correct RPC client variable.

---

wallet/addresses.go
wallet/sync.go
wallet/udb/addressmanager.go
wallet/udb/upgrades.go
wallet/udb/upgrades_test.go

This fixes two issues:
1. The old code would always hand out new addresses starting at the
discovered last used child index.  This could result in accidental
address reuse after restarting the wallet.
2. When the address gap limit was exhausted and the cursor wrapped
around to the beginning, the next returned address would skip over
the first returned address, because it was used.
To fix this, there needed to be a way to mark no addresses as used,
instead of recording child 0 as used.  This commit makes a change to
the database upgrade code and records the last used child index
^uint32(0) in this case.  This had to be a change to previous update
code as there is no way to otherwise distinguish between no use at all
or usage of just the 0th child after the upgrade has completed.
Fixes …

Fix an off by one in the address buffer.

---

rpc/legacyrpc/methods.go
wallet/addresses.go

The accountsyncaddressindex RPC only extends watched addresses now and
doesn't change any actual index that the account is synced to.
Therefore there is no reason to bother returning an error when a child
index behind the last used address is passed.
This was caught because an account branch without any address use
(lastused=^uint32(0)) was hitting an error when any valid child index
was being passed.
While here, add an additional error to prevent trying to sync to child
indexes for hardened keys.

Remove a silly error from accountsyncaddressindex.

---

rpc/legacyrpc/methods.go
wallet/addresses.go
wallet/wallet.go

While here, improve the AccountBranchAddressRange API to fix the order
of the function parameters and use a saner range, and modify
BIP0044BranchNextIndexes to return the next to use child indexes
rather than the last used index.
Fixes #675

Fix panic in getaddressesbyaccount.

---

internal/prompt/prompt.go

This change checks if stdin is a tty or not, and when it is not, it just reads
the input from stdin without removing terminal echo.  This allows passphrases to
be piped to the process.
For users running into difficult starting dcrwallet from startup scripts or
services due to the passphrase prompt when enabling the ticket buyer, it is now
possible to use the pipe as a workaround:
```
dcrwallet --enableticketbuyer < passfile
echo $pass | dcrwallet --enableticketbuyer
```
Fixes #690

Allow reading passphases from piped input.

---

config.go
wallet/chainntfns.go
wallet/txrules/rules.go
wallet/udb/stake.go

Users can still lower the fees on their own but until the majority of
the network has upgraded to the new mempool policy defaults, lowering
these fees can cause transactions to be rejected and votes to be
missed.
While here, remove the hardcoded constant used for revocations so
these are also created using the wallet's current relay fee.
Fixes #694.

Raise default fees back to 0.01/kB.

---

wallet/udb/stakedb.go

Only attempt to read the extended votebits from a version <=2 DB
ticket purchase record when votebits were recorded.  In very early
versions of the code, these fields were completely skipped over and
zeros were written in their place.
Fixes #384
Fixes #695

Fix old DB serialization code that caused panics.

---

wallet/udb/addressmanager.go

Actually write the new name into the database instead of using the old
account name.
Fixes #712.

Make account renaming work again.

---

wallet/chainntfns.go

If previous p2sh outputs must be discovered, a second rescan should be
manually performed.
Fixes #707.

Remove automatic rescans for discovered scripts.

---

log.go

I've found this helps with general tracing/review of time critical functions.

use millisecond time resolution in logger

---

wallet/udb/initialize.go

This fixes a panic that was caused by creating watching only databases
marked with the latest DB version when they really were in fact the
initial version of the udb database schema.
Watching only wallet databases that were created using the faulty code
(such as that found in the 1.0.0 and 1.0.1 releases) will not open
correctly due to the incorrectly-recorded database version and must be
recreated.
Fixes #725.

Upgrade created watching only DBs to latest version.

---

chain/chain.go
wallet/chainntfns.go

This change moves the handling of missed ticket notifications to the
same notification processing loop used for block and transaction
notifications, leaving vote creation as the only prioritized
notification handler.
Fixes #729.

Only prioritize vote handling.

---

dcrwallet.go
rpc/legacyrpc/server.go
rpcserver.go

This improves the integration of the legacy JSON-RPC server with the
wallet loader so that the wallet does not have to manually set by
external callers to enable wallet RPCs.
Closes #721.

Access loaded wallets through the Loader.

---

config.go

If --createwatchingonly is used without --create and the wallet
already exists, the program will exit with an error.
Closes #724.

Allow --createwatchingonly without --create.

---

wallet/udb/upgrades_test.go

This refactors the udb TestUpgrades function to avoid a data race
(potentially a Go issue, see golang/go#20339) by replacing the
concurrent t.Run and sync.WaitGroup usage with a subtest composed of
other parallel subtests.  This allows cleanup to be run outside of the
outer subtest.
Fixes #711.

Refactor test to avoid data race.

---

cmd/sweepaccount/main.go
config.go
netparams/params.go
rpc/rpcserver/server.go
rpcserver.go
sample-dcrwallet.conf

The gRPC server defaults binding to localhost addresses on port 9111
(mainnet), 19111 (testnet), and 19558 (simnet).
The experimentalrpclisten option has been renamed to grpclisten.
To disable the server, a nogrpc option has been added.  For
consistency with the legacy JSON-RPC server, a nolegacyrpc option has
also been added.
Closes #742.
Closes #743.

Enable the gRPC server by default.

---

wallet/createtx.go

This change improves the transaction creation error handling to handle
failures for rejected transactions or errors storing a transaction
into the database.  When purchasing tickets (a task that requires
creating multiple transactions), a DB update is now opened for each
published transaction.
The code has also been improved to only open DB updates when storing
or publishing the transaction.  Views are used when authoring and
signing transactions.  This reduces the amount of time spent in the
update and should improve the performance characteristics of the
wallet.
In the future, transactions could be published outside of the update,
but this will require a second update to remove any stored
transactions if the send fails.  This can not be done at this time due
to missing the udb APIs to …

Rollback DB updates for failed tx publishing.

---

ticketbuyer/buyer.go

Due to known issue with interval size being greater than ticket maturity 
length (144 and 16, respectively on testnet), estimatestakediff request 
is not allowed.
https://github.com/decred/dcrd/blob/0d48ca0105e0d512f89629e39ef841a4194c448b/blockchain/difficulty.go#L1351-L1356
Instead of removing the request, we will simply only proceed with using it if no err is received.

Comment out EstimateStakeDiff request

---

config.go
wallet/txrules/rules.go
wallet/udb/stake.go

This change was already done for version 1.0.0 but reverted back in
1.0.1 because not enough dcrd nodes had upgraded to make transactions
relay quickly across the network and be mined into blocks.  This is no
longer the case (since the stake v4 lock-in) and fees can again be
dropped to match that of the dcrd default mempool and relay policy.
Closes #749.

Drop default relay fee to 0.001 DCR/kB.

---

wallet/udb/addressdb.go
wallet/udb/addressmanager.go

The previous error messages would format the lookup address or key in
an unreadable manner.

Improve error messages for failed address lookups.

---

rpc/legacyrpc/methods.go
rpc/rpcserver/server.go
ticketbuyer/buyer.go
wallet/addresses.go
wallet/createtx.go

There are three policies defined:
1. Error when the unused address gap limit is violated
2. Ignore the gap limit and generate the next child address
regardless
3. Wrap around back to the first unused address after the last used
address to avoid violating the gap limit
The third wrapping policy was the default and only policy up until
now.  The new default is to error, with the intention of allowing
users to specify the policy they desire.
Because nothing calls the new address methods yet with anything other
than the wrapping policy, this commit introduces no functional change
to the program's behavior, but lays the groudwork for the policy to be
exposed to users elsewhere (such as options in RPC requests or the
wallet config).

Add wallet APIs for controlling the gap limit policy.

---

wallet/createtx.go

Sizes for txInEstimate and sigScriptEstimate had not been updated thereby giving incorrect estimates when calculating fees and possible number of transactions for consolidation.

Update estimateTxSize consts

---

wallet/chainntfns.go
wallet/udb/stake.go

Add warning message when vote version is older than blockheader's StakeVersion

---

glide.lock

In particular, this updates grpc-go to the 1.4.0 release which
contains a fix for an integer overflow that caused HTTP/2 parsing
errors in Paymetheus.

Update all dependencies.

---

internal/prompt/prompt.go

`Once you have stored the seed in a safe and secure location, enter "OK" to continue: ok`
Now accepts `ok | OK` instead of only `OK`

Fixes #806  Prompt accepts "ok"

---

wallet/udb/addressmanager.go

The new checks compare incremented values.  This is done so that the
sentinel value ^uint32(0), when incremented, wraps around to 0 and
when compared against non-zero child indexes, the check will determine
that the update to increase to child index should be performed.
Fixes #813.

Fix calculations of whether to write updated child indexes.

---

config.go

If no file is specified, the current behavior (warn only)
if correct and is not changed.
Closes #835

cfg: error if specified config file is missing.

---

config.go

This reverts commit 1020bdd0bcc4ea416e2efc8af3a228ae0397744e.
Will put this back in when we can check if the config file was
explicitly set or not.

Revert "cfg: error if specified config file is missing."

---

internal/cfgutil/explicitflags.go

This simplifies the handling of checking whether a config option was
explicitly set or not.

Import cfgutil.ExplicitString from btcwallet.

---

config.go
dcrwallet.go
rpcserver.go
walletsetup.go

This uses the new cfgutil.ExplicitString to ensure that the option was
really explicitly set instead of comparing the value itself to a
default.  Unlike the implementation in 1020bdd, this works correctly
when the default config file location is changed due to a modified
appdata directory.
While here, update the rest of the config options that are relative to
the appdata directory to use ExplicitString.

Error for missing expicitly specified configs.

---

internal/cfgutil/explicitflags.go

This allows the option to be passed to the fmt package for conversion
to a string.

Make cfgutil.ExplicitString a fmt.Stringer.

---

config.go

This allows levels to be specified by their shorthand versions (CRIT
vs CRITICAL, for example), works with any capitalization, and adds
support for handling the OFF level (previously the least verbose log
level that could be set was CRITICAL).

Use btclog for determining valid log levels.

---

wallet/udb/txmined.go

This fixes a bug in udb.Store.InsertMinedTx where an error writing the
new mined balance to the database would result in returning early
without indicating any error at all.

Fix incorrect error handling.

---

apperrors/error.go
wallet/chainntfns.go
wallet/udb/txunmined.go
wallet/wallet.go

The database can enter an invalid state when an unmined transaction is
recorded even if it is already recorded mined.  Check for this and
refuse to continue, warning if it ever occurs.  If this does occur,
the notification system will need to be audited.

Warn when attempting to add duplicate unmined txs.

---

rpc/documentation/api.md
rpc/rpcserver/server.go

This should have been included in the last commit but was overlooked.

Bump the gRPC API version for SignMessage addition.

---

wallet/udb/txmined.go

The error now reports the hashes of both transactions and the output
that was double spent.

Improve multisig credit double spend error message.

---

wallet/udb/addressmanager.go

Previously, the child index 0 for both the internal and external
branches of new accounts was marked as returned, so the first returned
address of the account would be those at child index 1.
Fixes #880.

Don't waste the first address of new accounts.

---

config.go
sample-dcrwallet.conf

Due to expected changes to ticket purchasing performance, we can now lower the default maxfee to 0.01 DCR and also lower the maxperblock to 1.  
Closes #868

ticketbuyer: update default config settings

---

glide.lock
wallet/txauthor/author.go

~**NOTE: This contains overrides in `glide.yaml` and `glide.lock` for decred/dcrd#798 and decred/dcrutil#57 that need to be removed/updated before this is merged**.~
This updates the `txauthor` package to set the new serialization type field in the `wire.MsgTx` struct and introduces a local constant which defines the version to create the transaction with instead of using the
latest version in `wire`.  This is important since a change in the transaction version will potentially require changes to the generated transaction and thus using the wire constant for the generated transaction version could allow creation of invalid transactions for the updated version.

txauthor: Update for MsgTx API changes.

---

wallet/udb/addressmanager.go

This reverses the checks for whether to return an error code for
duplicate scripts or a locked address manager so that the duplicate
check is performed first.  This prevents logging errors for duplicate
script imports even when the wallet is locked.

Avoid errors importing duplicate scripts when locked.

---

wallet/sync.go
wallet/udb/addressmanager.go

When called with the wrapping gap policy, RPCs like getnewaddress and
WalletService.NextAddress would wrap around to a previously returned
address in order to avoid violating the BIP0044 gap limit.  However,
this was not correctly handled on restarts due to the last returned
child indexes not being reset down to the lower values.  This changes
the database code so that lower returned child indexes are written and
persisted across restarts.

Handle address wraping policy after restarts.

---

rpc/legacyrpc/methods.go

Closes #896.
There are some other instances where there isn't a network check but ticketsforaddress/stakepooluserinfo should be going away soon and verifymessage should error anyway.

legacyrpc: check network on sendaddress input

---

wallet/tickets.go

Tickets expire after they have 40960 + 256 + 1 confirmations (on
mainnet).  Unfortunately, the confirmation check used by the wallet
was not taking into consideration the extra confirmations required
before the ticket becomes live.  Fix this so it matches consensus
rules.
The consensus rules calculate and compare the height that the ticket
expires at rather than checking the total number of confirmations (the
depth of the transaction in the blockchain), but wallet uses
confirmation checks everywhere so this was kept consistent with the
rest of the wallet code.

Use correct confirmation check for ticket expiry.

---

config.go
dcrwallet.go

Use embedded `Address` instead of the `*AddressFlag` when assigning to `Address` type fields of `ticketbuyer.Config` and `ldr.StakeOptions`.  This previously compiled because `*AddressFlag` satisfies the `dcrutil.Address` interface.  However, this broke later tests against `nil` because it was itself not nil (whether nil `interface{}`, nil `*AddressPubKeyHash`, etc.), but rather a non-nil pointer to a `cfgutil.AddressFlag`.
This fixes the bug introduced in https://github.com/decred/dcrwallet/commit/fe7e5da10bdc6522dde8ece83abf59a2bbdec1c0

Fix PoolAddress and TicketAddress options with new AddressFlag.

---

wallet/chainntfns.go
wallet/tickets.go
wallet/udb/addressmanager.go
wallet/wallet.go

This change skips over all ticket purchase transactions for
getstakeinfo where the wallet does not own the voting rights for the
ticket.  It also avoids creating votes and revocations for selected
and expired/missed tickets.
Fixes #903.

Skip tickets without voting authority.

---

wallet/notifications.go

This corrects an issue where seed-restored wallets report the time of
restore as the transaction time and fixes timestamps for transactions
received when the wallet was not running or connected to the network.
Fixes #905.

Use earliest of block and receive time for tx timestamp.

---

wallet/udb/txmined.go
wallet/udb/txunmined.go

Votes may only be double spent by a revocation if they do not vote on
the current main chain tip block.
Fixes #915.

Allow unmined votes to be double spent by revocations.

---

glide.lock
glide.yaml
wallet/tickets.go

This is required for newer versions of the stakepool that expect added
tickets to be in the gettickets result set.

Include stake manager tickets in gettickets results.

---

wallet/wallet.go

This count was off by one for each account branch.  Issue was noticed
on a fresh wallet that reported watching only 38 addresses when there
should be 40 (20 for each branch in the default account).  This was
only a logging bug and no addresses were being missed.

Log the correct number of watched addresses at startup.

---

glide.lock
wallet/createtx.go
wallet/wallet.go

This change also includes a fix for an txscript API break which
removed the StandardVerifyFlags constant.  Wallet now defines this
constant itself, based on the newly introduced
mempool.BaseStandardVerifyFlags.  As features are enabled, these flags
should be updated.  An even better solution, but not one that can be
performed at the moment, would be for the wallet to know when a
voted-on fork activates and change the flags automatically.

Update Decred and golang.org/x deps.

---

ticketbuyer/buyer.go

Typically this isn't an issue, but you'll get NaN when running SimNet from block 0 since stakeLive and stakePoolSize are 0.

Add check to make sure stakeLive is greater than 0

---

wallet/udb/stake.go
wallet/wallet.go

It has no place being here and is no longer being used after several
stake manager refactors.

Remove dcrd RPC client from stake manager object.

---

rpc/legacyrpc/methods.go
rpc/legacyrpc/server.go
rpc/rpcserver/server.go
wallet/chainntfns.go
wallet/createtx.go
wallet/rescan.go
wallet/sync.go
wallet/tickets.go
wallet/wallet.go

The remaining usages require the additional functionality of the
client wrapper for notifications and syncing.  These will be
eventually removed from the wallet package, allowing the chain package
to keep the wallet up to date.  Removing these usages are required to
avoid a circular dependency.

Remove most usage of chain.RPCClient from wallet package.

---

wallet/tickets.go
wallet/udb/stake.go

The height field of a pool ticket saved by the stake manager was never
being used.  To remove a case of requiring the dcrd RPC client to
query for its height, this field is now left zeroed and a comment has
been added to the field indicating that it is not used and can not be
relied on.
If the height of the transaction is required to be known, it must be
looked up through the transaction manager.

Don't set heights for manually added tickets.

---

wallet/notifications.go
wallet/udb/txmined.go
wallet/wallet.go

The GetBlockHash and GetMainChainBlockHashForHeight methods had the
same functionality: returning the block hash of the block at some
height in the wallet's main chain.  Prefer to use the latter as it is
slightly more efficient by not decoding the entire block record.

Remove duplicate udb method with identical functionality.

---

loader/loader.go
rpc/legacyrpc/methods.go
rpc/legacyrpc/server.go
wallet/wallet.go

This is now being passed into the walletinfo handler to provide
information on whether the ticket buyer is running.  This is
preferable to querying this from the wallet itself since the wallet no
longer purchases tickets and the ticket buyer can be started/stopped
at will (over gRPC) so plumbing the config option to the handler
through the wallet struct is not the correct way to report this.
Remove the old TicketPurchasingEnabled methods from the wallet as they
are simply no longer needed.

Allow JSON-RPC handlers access to the wallet loader.

---

config.go
dcrwallet.go
walletsetup.go

If the terminal is left in a non-echoing state, the reset command
should be used.
Fixes #974.

Exit from passphrase prompts when interrupted.

---

config.go
dcrwallet.go
version/version.go

This allows access to the application version info from other wallet
packages, which is of particular use for useragent strings when using
the wire protocol.

Move application version code to its own package.

---

config.go

Port 0 indicates that the operating system is free to pick an unused
port, so these listener addresses don't actually clash.

Allow duplicate listeners when binding to port 0.

---

config.go
dcrwallet.go
ipc.go
rpcserver.go

This changes adds support for the TX IPC pipe (to complement the RX
pipe) and events to notify the listener addresses used by the JSON-RPC
and gRPC servers.  This is useful for parent processes which start the
wallet with a listener address bound to port 0, causing the operating
system to pick an unused port.  A new config option
--rpclistenerevents must be used to enable these messages.
The pipe messages use the same protocol format as dcrd.
Closes #964.

Add TX pipe and RPC listener events.

---

internal/prompt/prompt.go
prompt/prompt.go
wallet/cointype.go
wallet/sync.go
wallet/udb/addressdb.go
wallet/udb/addressmanager.go
wallet/udb/cointype_test.go
wallet/udb/common_test.go
wallet/udb/txcommon_test.go
wallet/udb/upgrades.go
wallet/udb/upgrades_test.go
walletsetup.go

This change modifies the wallet to prefer the use of the coin types
assigned to Decred in SLIP0044 over the coin types used thus far.  New
wallets that are created with a random seed are created using the
SLIP0044 coin type, and if no address usage from the legacy coin type
is found during address discovery, the wallet is automatically
upgraded to use the SLIP0044 coin type instead.
This change introduces a database upgrade and older versions of the
wallet will not work on upgraded wallet DBs.
Closes #945.

Switch default coin types to those defined in SLIP0044.

---

wallet/sync.go

This prevents a loop where synchronization stops and restarts, hitting
the exact same error again.
Fixes #994.

Log warnings for failed SLIP0044 coin type upgrades.

---

rpc/rpcserver/server.go

The versions in server.go and api.md are different. This updates server.go to respect what is api.md.

grpc: Update grpc version

---

sample-dcrwallet.conf

This flag is listed in several places in the docs but was missing in the sample config.

config: Add enablevoting to sample config file

---

rpc/rpcserver/server.go

This fixes a bug on the DecodeTransaction grpc call that prevented the decoded addresses for the outputs to be sent in the response.

grpc: fix bug on outputs of DecodeMessageService

---

cmd/sweepaccount/main.go

Currently, `sweepaccount` only supports sending from/to accounts. This PR allows to use addresses as well.
There is also two minor tweaks in this PR (see separate commits).
I'm still pretty new to Go so please let me know if some code is not idiomatic and I'll be happy to tweak it.

sweepaccount: allow to use an address for source and destination

---

rpc/legacyrpc/errors.go
rpc/legacyrpc/methods.go
rpc/legacyrpc/rpchelp_test.go
rpc/legacyrpc/server.go
rpcserver.go

Handler dependencies are now fetched via the server.
Thanks to @jrick for the guidance.

legacyrpc: update legacy rpc handler setup.

---

cmd/movefunds/main.go

addresses ./run_tests.sh warning: `cmd/movefunds/main.go:210:36:warning:
should use buf.Bytes() instead of []byte(buf.String()) (S1030)
(gosimple)`

movefunds: resolve linter warning.

---

dcrwallet.go

dcrwallet: advice --walletpass use on err when no passphrase is given.

---

wallet/udb/txdb.go
wallet/udb/txmined.go
wallet/udb/upgrades.go
wallet/udb/upgrades_test.go

The previous database upgrade wrote data to the wrong bits and could
cause ticket outputs to be wrongly chosen as spendable outputs to use
for regular transactions.  This change introduces another database
upgrade which corrects the previous issue and updates comments
describing the format of saved values to make these mistakes less
likely to occur in the future.
Fixes #1057.

Fix previous database upgrade.

---

Gopkg.lock
pgpwordlist/pgpwordlist_test.go

It's not worth pulling this and other transient deps in for a few
calls in one test file.

Remove testify dependency

---

version/version.go

The dot delimiter is used to separate identifiers in semver build and
release metadata.  Adding dot to the alphabet will prevent the
delimiter from being stripped out of the version.

Do not strip . delimiters from semver build metadata.

---

wallet/createtx.go

This will make debugging failed script executions easier as the error
message now includes the previous outpoint being spent, the previous
output script, and the signature script created by us.  There is
little harm in logging these scripts as we default to using
SIGHASH_ALL.

Add context to script execution errors.

---

rpc/rpcserver/server.go

The test for unmined block on the `GetTransactions` grpc call was modified in commit 53457bef94772891934219da6510ac6bbef09cee due to a change in the wallet implementation for GetTransactions.
But the new test (`block.Header == nil`) is the opposite of what is needed (previous version was `block.Height != -1`) so this returns the correct test.

[rpc] Fix unmined block test in GetTransactions

---

wallet/udb/txmined.go

This fixes an issue in the previous commit which updated to the latest
dcrd.

Allocate before copying into first block locator hash.

---

wallet/wallet.go

Remove some loud debug messages that clog logs and provide no real value.

Silence debug messages.

---

config.go
dcrwallet.go
loader/loader.go
walletsetup.go

We had discussed doing this a few times.
`--gaplimit` is very descriptive about what the option accomplishes and is easier to explain to users.

config: Add gaplimit and deprecate addridxscanlen

---

dcrwallet.go

The default config value for the public passphrase is "public" not the
empty string.  Fixing this check will correctly log a message to set
the public passphrase with the appropiate config options.
While here, edit the log message to remove -- from the flag names, as
these are more appropiate to add to the config file anyways.

Fix check for unset public passphrase.

---

config.go

The function which cleans and expands filepaths for config options
erroneously converted the empty string to a single dot.  Correct this
by checking for an empty path as input and returning the empty path
back.
Discovered and previously fixed in dcrd, which contained a ported
version of dcrwallet's filepath cleaning.

Prevent empty filepaths from being cleaned to .

---

wallet/chainntfns.go
wallet/multisig.go
wallet/wallet.go

This fixes a bug introduced with the errors package which began to
return errors for missing unencrypted scripts, instead of just
returning nil.  The calling code has been updated in all places to no
longer assume it returns nil scripts and without error when the script
is not found.

Handle missing unencrypted scripts when processing transactions.

---

Gopkg.lock
Gopkg.toml
chain/log.go
config.go
go.mod
go.modverify
loader/log.go
log.go
rpc/legacyrpc/log.go
rpc/rpcserver/log.go
ticketbuyer/log.go
wallet/log.go
wallet/udb/log.go

dcrd was updated to use the new package github.com/decred/slog for all
logging prior to introducing submodules (which would have required a
version bump).  Update for this dcrd change in anticipation for
depending on dcrd submodules as well as defining our own.

Update dcrd, switch to slog logger package.

---

rpc/legacyrpc/methods.go

The dcrd gettxout JSON-RPC method is invoked by signrawtransaction to
look up previous output scripts that the wallet may not record itself.
When gettxout is queried for an output that is already spent in the
main chain, it will return the JSON null without any error.  This
requires special casing in the signrawtransaction implementation to
avoid a possible nil pointer dereference.
Fixes #1148

Prevent signrawtransaction panic on gettxout result.

---

rpc/rpcserver/server.go

Looks like the version in the docs was bumped in #1113 but not in the server.go.

Bump grpc version for previous change

---

cmd/sweepaccount/main.go
rpc/legacyrpc/methods.go
rpc/rpcserver/server.go
wallet/addresses.go
wallet/createtx.go
wallet/internal/txsizes/size.go
wallet/internal/txsizes/size_test.go
wallet/multisig.go
wallet/txauthor/author.go
wallet/txauthor/author_test.go

This adds the ChangeSource interface which requires two function implementations: Source() & ScriptSize(). NewUnsignedTransaction() has been updated to use this modification as a result. 
EstimateSerializeSize function signature has also been updated to take the change script size instead of assuming a P2PKH script size for the change output. Passing zero (0) as the change script size does not add a change output.
This is work towards #1162

wallet: make ChangeSource an interface.

---

internal/cfgutil/address.go
walletsetup.go

Replace the embedded address with field named Address.  This prevents
AddressFlag from implementing, and accidentally being used as, a
dcrutil.Address interface.

Remove embedded Address from cfgutil.AddressFlag

---

config.go
dcrwallet.go
loader/loader.go
sample-dcrwallet.conf
wallet/addresses.go
wallet/sync.go
wallet/wallet.go
walletsetup.go

Reduce default allowed account gap limit from 100 to 10 accounts to
improve performance of account discovery. Add configurable
"accountgaplimit" in case user need to scan more accounts
https://github.com/decred/dcrwallet/issues/1143

multi: change accountgaplimit and add config option

---

wallet/chainntfns.go
wallet/tickets.go
wallet/udb/txquery.go
wallet/wallet.go

This adds a `FetchOutput` function to the wallet. `Store.Tx` is also modified to return an error (NotExist) if a transaction is not found.
This is work towards #1176

wallet: add FetchOutput.

---

wallet/createtx.go

This adds a value check after output filtering checks to assert the returned outputs set  is at least equal to the desired amount.

wallet: fix findEligibleOutputsAmount.

---

rpc/legacyrpc/methods.go
wallet/wallet.go

These fields are able to be set by SPV wallets while other fields such
as missed and expired can not be.  They are being added to provide a
fuller picture of ticket state counts for SPV wallets, but should be
implemented by other syncing modes as well.

Add unspent and unspentexpired fields to getstakeinfo

---

rpc/rpcserver/server.go
rpcserver.go

This replaces a couple instances of golang.org/x/net/context with the
standard library context package.

Run go fix across project

---

cmd/sweepaccount/main.go
rpc/rpcserver/server.go
wallet/createtx.go
wallet/internal/txsizes/size.go
wallet/txauthor/author.go
wallet/txauthor/author_test.go
wallet/udb/txmined.go
wallet/utxos.go

`txscript.InputDetail` was introduced to bundle what `txscript.InputSource`
returned and also return a slice of input script sizes to improve fee
estimation.
This resolves #1161

multi: add txscript.InputDetail

---

wallet/createtx.go
wallet/internal/txsizes/size.go
wallet/internal/txsizes/size_test.go
wallet/multisig.go
wallet/txauthor/author.go
wallet/txauthor/author_test.go

The interface can be succintly represented as an int. This chance also circumvents exporting txsizes to get access to the interface for utilities like sweepaccount.

wallet: remove ScriptSizer interface.

---

run_tests.sh

The formatting rules have changed for Go 1.11, and with the release so
close several developers are already testing the betas.  To prevent
gofmt formatting from being a blocking issue when submitting pull
requests, gofmt checks on Travis-CI are being temporarily disabled.
Gofmt checks will be reenabled and using Go 1.11 formatting rules when
Go 1.11 is released.

Temporarily disable gofmt on CI

---

chain/sync.go
wallet/wallet.go

The dcrd RPC sendrawtransaction errors if an identical transaction
already exists in mempool.  Therefore, do not end RPC sync if an error
occurs during the publishing of unmined transactions.

Prevent RPC sync loop on duplicate transactions.

---

chain/backendwrapper.go
wallet/discovery.go

When address/account discovery is performed in the RPC sync mode, it must
support features used by voting wallets, such as discovering usage of addresses
as voting addresses in ticket purchases.  These output scripts are not included
in the committed filters by design (to make SPV voting impossible), but without
them it is not possible to correctly restore a voting wallet.
Due to this limitation of using committed filters for address discovery, the
prior algorithm which depends on the dcrd address exists index is being
reintroduced and is used when the Peer implementation is the RPC network
backend.
Fixes #1224

Revert RPC address discovery to prior algorithm

---

config.go

This is not a supported configuration (or even technically possible with the
current filter commitments), so error at startup when both are enabled.
Closes #1226.

Prevent --spv usage with --enablevoting.

---

ticketbuyer/v2/tb.go

The previous logic limited the total number of buyable tickets per block to the
number of picked tickets per block.  This is not the desired behavior, and the
buyer should buy as many tickets as can be mined in the next block but no more.
Noticed by @alexlyp who had to switch back to the v1 buyer temporarily on
testnet3 as the v2 buyer was not buying enough tickets to support the target
ticket pool.

Buy max tickets mineable per block.

---

wallet/difficulty.go

This was modified as part of the testnet reset (instead of only applying new
rules to testnet3).  Pull in the fixes to make it match.

Make testnet PoW diff reduction match dcrd.

---

run_tests.sh

The CI runners currently use a newer version of dep that produces different
output for the lockfile when running dep ensure.  Remove this test since it
doesn't check anything particularly useful and because a switch to module builds
is planned for the 1.4 development cycle.

Do not test Gopkg.lock is tidy.

---

README.md

The building from source section has been simplified for the instructions to
perform a module-aware build.
For the dcrwallet 1.4 development cycle, Go 1.9 is no longer supported, and
module builds must be performed with Go 1.10 or Go 1.11 instead.
While here, remove all references to Windows MSIs, as none are provided.

Update README for Go 1.11 and module builds.

---

rpc/rpcserver/server.go

Fix #1254 
The grpc endpoint ValidateAddress was previously returning the original public key hash address of the requested address instead of the correct public key address. This fixes the problem and bumps the patch level of the api.

[grpc] return pk instead of pkh in validateAddress

---

go.mod
go.sum
rpc/legacyrpc/server.go

The github.com/gorilla/websocket package (from which
github.com/btcsuite/websocket was forked) is already part of the
dependency graph.  Use it to implement the JSON-RPC server as it is
still maintained and to remove the dependency on
github.com/btcsuite/websocket entirely.
Closes #1260.

Remove github.com/btcsuite/websocket dependency

---

run_tests.sh
testmodules.sh

Source files are no longer built inside the container user's GOPATH,
but instead a module build is performed from /src.
The :Z attribute has been added to the -v mount option.  This applies
the correct SELinux settings so the container is able to access the
files inside /src.  Tested on Fedora 28 using the default SELinux
policies.  See [1] for further details about this attribute.
Support for podman (a drop-in replacement for docker) is also added.
To use, call the script as './run_tests.sh podman'.
While here, also remove 'go mod verify' from the test script.  Module
verification is implicitly done for any build/test operation, so this
is unnecessary and running it again marginally slows down CI testing.
[1] https://www.projectatomic.io/blog/2015/06/using-volumes-with-docker-can-cause-pr …

Improve various aspects of run_tests.sh.

---

rpc/rpcserver/server.go

This modifies the ImportScript grpc call to allow it to be called when using a watch only wallet. Watch only wallets do now allow unlocking, so this endpoint was failing for that case.

grpc: allow ImportScript in watching only wallets

---

version/version.go

This takes a different approach to version naming compared to previous
releases.  The version is being bumped at the beginning of the release
cycle to make it more obvious that the version string (1.4.0-pre+dev)
represents a development, work-in-progress build leading up to the
1.4.0 release.

Bump version for beginning of 1.4 cycle.

---

go.mod
rpc/walletrpc/go.mod
rpc/walletrpc/go.sum

The github.com/decred/dcrwallet/rpc/walletrpc package, which contains
the autogenerated gRPC service bindings, is imported by other projects
for service definitions to create wallet RPC clients.  This package
was previously part of the main module, so it was not properly
versioned and separated for use as a library for other projects.
The module is given version 0.1.0 and the current plan is to always
stay at major version 0, while incrementing the minor version for any
modifications.  I am reluctant to give this a major API version (let
alone the same version as the API itself) since the file is
autogenerated.  A switch to major versions is always possible later if
this system does not work out.

Declare a walletrpc module

---

chain/backendwrapper.go
chain/sync.go
errors/errors.go
rpc/legacyrpc/methods.go

This change begins to use standard libary features introduced in Go
1.10, such as calls to hex.New{Encoder,Decoder} as well as use of
strings.Builder.  A custom type used to implement io.Reader for hex
strings is removed as it is no longer necessary given these standard
library APIs.

Introduce Go 1.10 stdlib features.

---

ticketbuyer/buyer.go

The shadowing of the `err` variable inside the if was causing the outer
if test (after the log.Tracef call) to fail, as the outer err was
actually filled.

ticketbuyer: fix stakediff detection via dcrd

---

wallet/udb/txquery.go

58cf828c2 introduced usage of an undefined error kind.  This fixes it.

Fix build.

---

chain/chain.go
dcrwallet.go

Latest dcrd master updated the rpc api version but the wallet does not
currently report any connection errors. This was added to mirror the
spv connection error reporting, which is done is spvLoop().

Report RPC connection errors

---

wallet/createtx.go
wallet/internal/txsizes/size.go

This uses `EstimateSerializeSizeFromScriptSizes` for ticket fee estimation given its standardized format. Constants `doubleInputTicketSize` and `singleInputTicketSize` are also removed.
Resolves #1272

multi: update fee estimation for tickets.

---

wallet/udb/txquery.go
wallet/wallet.go

This fixes two small issues related to the GetTickets grpc call:
- The error was not correctly returned in GetTickets/GetTicketsPrecise,
causing it to not bubble up the stack
- The udb function Store.TxDetails was recently changed to return an
error when a transaction is not found; this kind of error needs to be
ignored in TicketDetails when loading the voting details of a ticket
that hasn't yet voted.

multi: Fix GetTickets on non-voted

---

wallet/createtx.go

When an empty string is used as the voting address in a purchaseticket
JSON-RPC call, the wallet will generate a P2PKH voting address.  This
behavior broke in 9fe6e6b6, and is fixed here by allowing the nil
address in a request.

Allow empty string purchaseticket voting addresses

---

walletsetup.go

When creating a new wallet, the database should be cleanly closed
before the process exits.  Otherwise, even though the database might
be consistent, not all intended changes may be written to it.

Close created DB before os.Exit

---

chain/sync.go

The map of relevant transactions was being cleared too early, causing
all counts of relevant accepted wallet transactions from a block to
always be zero.  This is fixed by setting the map to nil after logs
have been emitted.

Log correct tx counts in RPC sync mode

---

testmodules.sh

Change script so it works on darwin, currently it fails on MAC OSX : 
`./run_tests.sh
+ [[ ! -n '' ]]
+ GOVERSION=1.11
+ REPO=dcrwallet
+ DOCKER=
+ [[ '' == \d\o\c\k\e\r ]]
+ [[ '' == \p\o\d\m\a\n ]]
+ [[ ! -n '' ]]
+ testrepo
+ go version
go version go1.11 darwin/amd64
+ env GORACE=halt_on_error=1 CC=gcc 'GOTESTFLAGS=-race -short' bash ./testmodules.sh
?   	github.com/decred/dcrwallet	[no test files]
?   	github.com/decred/dcrwallet/cmd/movefunds[no test files]
?   	github.com/decred/dcrwallet/cmd/sweepaccount	[no test files]
?   	github.com/decred/dcrwallet/internal/cfgutil	[no test files]
?   	github.com/decred/dcrwallet/internal/prompt	[no test files]
?   	github.com/decred/dcrwallet/internal/rpchelp	[no test files]
?   	github.com/decred/dcrwallet/loader	[no test files]
? …

Fix test script to work on Darwin OS 

---

rpc/legacyrpc/methods.go
wallet/udb/txquery.go
wallet/wallet.go

When a transaction is not yet known, lookups for details of the tx
must return an appropriate error.  This commit modifies the internal
TxDetails function to return non-nil errors rather than nil details
structs if the transaction is not recorded.
This is not a breaking change to consumers of the wallet module as the
udb package is a candidate for becoming internal and is not possible
to use in other projects as an internal walletdb interface is
necessary to create a udb.Store.
This is a backport of 58cf828.

[release-v1.3] Return errors for details of unknown transactions.

---

wallet/udb/txquery.go
wallet/wallet.go

This fixes two small issues related to the GetTickets grpc call:
- The error was not correctly returned in GetTickets/GetTicketsPrecise,
causing it to not bubble up the stack
- The udb function Store.TxDetails was recently changed to return an
error when a transaction is not found; this kind of error needs to be
ignored in TicketDetails when loading the voting details of a ticket
that hasn't yet voted.
This is a backport of 39d3bc0.

[release-v1.3] multi: Fix GetTickets on non-voted (#1289)

---

deployments/deployments.go

The simnet network has been modified in dcrd to perform the current
mainnet deployments beginning at the simnet genesis block.  This
tracks this change in the wallet by updating the hardcoded activation
heights of these deployments.

Activate simnet deployments from genesis block.

---

dcrwallet.go
loader/loader.go

This change moves the opening of an existing wallet DB into a
background goroutine so that main can return and the process will exit
if an interrupt signal is sent to a wallet process that is blocked on
a database lock.
To support this change, the loader mutex must be released during the
loader's open database call.
Fixes #1296

Allow process interrupt when blocked on DB lock.

---

log.go

The previous behavior was to keep at most three rotated log files to
prevent a filesystem from becoming overfilled with old logs.  However,
in practice, this has cause the loss of important logs which could
have been useful in debugging fatal bugs.  This change causes no log
rotation deletions, instead requiring a user (or program set up by the
user) to delete log files after they are no longer deemed necessary.
While this can still cause unnecessary filesystem usage, this is not
deemed an issue since the wallet will already grow to an unbounded
size as it must save the entire header chain and will grow infinitely
long as time progresses.

Do not delete log rotation files

---

wallet/chainntfns.go
wallet/createtx.go
wallet/rescan.go
wallet/tickets.go
wallet/wallet.go

When a transaction is processed, either when discovered over the
network, created by this wallet, or published over RPC, the wallet
must begin to watch relevant outputs of the transaction.  This was
prevously not being performed, resulting in transactions being missed
and double spends occuring due to spent outputs not being marked as
spent by the missed redeeming transaction.
In future versions of the wallet module, I hope to modify the APIs to
return new relevant data that must be watched by a syncing network
backend.  However, this is too invasive of a change to perform now and
would clutter the API with several deprecated functions if attempted
without bumping major module versions.  Instead, if a network backend
is associated with the wallet, it is used to load the relevant outputs …

Watch relevant outputs of processed transactions

---

chain/chain.go

This matches dcrd's RPC server version bump in PR https://github.com/decred/dcrd/pull/1531.
As discussed on Slack, dcrwallet does not depend on the order of reorg and block connected notifications, but the bump is still needed unless a range of major versions is to be supported.

Bump required dcrd JSON-RPC API version

---

wallet/udb/txmined.go

Errors now report the outpoint of the missing credit, the transaction which
supposedly spends the missing credit, and the key used to attempt the lookup.

Improve errors for missing credit value failures

---

chain/chain.go
dcrwallet.go

There are config options and flags that currently exist for using SOCKS proxy, but don't do anything.
This exports `NewRPCClientConfig`, which creates an RPC Client to the `chain` package and uses it in dcrwallet command.
* `NewRPCClientConfig` accepts a `dcrrpcclient.ConnConfig` for even more precise configuration
Resolves #1287

rpc: use SOCKS5 proxy if configured

---

wallet/wallet.go

This fixes the GetTicketInfo/GetTicketInfoPrecise wallet functions to
return an empty block header for unmined tickets, instead of failing.
This makes these calls behave the same way as the GetTickets call.

wallet: Return info for unmined tickets

---

version/version.go

The 1.4 release branch and 1.4.0-rc1 tags have been created branched off from
master.  It's time to start work on 1.5.

Bump version for 1.5 release cycle.

---

wallet/wallet.go

The TransactionSummary method was previously returning the transaction hash
rather than the block hash if the transaction was mined.  This corrects the
method to return the block hash instead.
Fixes #1365

Return correct block hash from TransactionSummary

---

wallet/walletdb/db_test.go
wallet/walletdb/example_test.go
wallet/walletdb/interface_test.go

This fixes the existing walletdb tests and reenables them.
Work towards #425.

walletdb: reenable tests.

---

go.mod
go.sum
wallet/go.mod
wallet/go.sum
wallet/wallet.go

**This requires decred/dcrd#1578**.
Also, update to the latest `chaincfg` module version in the root and `wallet` modules to pull in the latest definitions.

Bump stake versions for 1.4.0 release agendas.

---

spv/sync.go

A connecting peer should be set to not connecting status after failing due to error.  This is causing problems for dcrandroid.
Ps. I'm new.  Plz check my work and any criticisms are welcome.

spv sync: reset peer connection status after error

---

wallet/udb/txmined.go

This modifies `udb` to make use of `txscript.CalcMultiSigStats` instead of `txscript.GetMultisigMandN` since it is being deprecated.
Closes #1383.

udb: Use txscript.CalcMultiSigStats.

---

rpc/legacyrpc/server.go
rpc/rpcserver/server.go

This removes unused `handlerMu` and `handlers` fields in the server struct and adds a couple lint fixes.

multi: remove unused  fields.

---

wallet/tickets.go

The LiveTicketHashes method was not correctly excluding duplicate tickets
managed by both the stake manager and the tx store.  This caused issues for
VSPs, who still use the additional tracking in the stake manager.

Prevent duplicate stakemgr live ticket hashes

---

config.go
dcrwallet.go
loader/loader.go
sample-dcrwallet.conf
wallet/discovery.go
wallet/wallet.go
walletsetup.go

This will require the next wallet module release to be a minor bump for the
introduction of a new config struct option.
Closes #1389.

Add config option to disable coin type upgrades

---

rpc/jsonrpc/types/README.md
rpc/jsonrpc/types/doc.go
rpc/jsonrpc/types/go.mod
rpc/jsonrpc/types/go.sum
rpc/jsonrpc/types/walletsvrcmds.go
rpc/jsonrpc/types/walletsvrcmds_test.go
rpc/jsonrpc/types/walletsvrresults.go
rpc/jsonrpc/types/walletsvrwscmds.go
rpc/jsonrpc/types/walletsvrwscmds_test.go
rpc/jsonrpc/types/walletsvrwsntfns.go
rpc/jsonrpc/types/walletsvrwsntfns_test.go

**This requires decred/dcrd#1607**.
~**DO NOT MERGE -- This currently contains an override in the `go.mod` to use the required pull request so CI will build.  It will need to be updated once the upstream PR is merged and tagged.**~
This moves all of the types specific to `dcrwallet` from the `dcrjson` module into a new module at `rpc/jsonrpc/types` so wallet is able to independently modify them as necessary without needing to submit the changes to `dcrd` directly or requiring new `dcrjson` tags.
It provides full package documentation and also ported all tests over so there is comprehensive test coverage.

jsonrpc/types: Implement new module for dcrjson.

---

ticketbuyer/go.mod

This was added during an attempt to perform both submodule major bumps and main
module updates in a single change.  The attempt failed and this replacement
should have been removed at that time.

Remove non-main module replacement that snuck in.

---

go.sum
wallet/go.mod
wallet/go.sum
wallet/internal/bdb/db.go
wallet/udb/txcommon_test.go
wallet/walletdb/interface_test.go

This updates the wallet's bolt dependency to the current actively maintained branch of bolt. A cursor delete test has been added to the interface tests as well.

multi: switch to go.etcd.io/bbolt

---

go.mod

The go directive describes the minimum target Go version of the module.  If
building with an older version of Go than described by the module, a note will
be emitted if the build fails.

Add go 1.11 directive to main module.

---

config.go

Warnings are logged if the option is modified from the default.  It is recommend
to only set --txfee instead.
Closes #1414

Deprecate --ticketfee option

---

wallet/wallet.go

This makes the wallet not purge unmined transactions when the underlying
error returned by the backend is a dcrjson error with ErrRPCDuplicateTx
code.
Previously, this caused wallets to purge an unmined transaction that was
republished or otherwise already existed in the network even though it
was still valid, and could cause the wallet to produce a double spend
transaction by marking the funds of the (now purged) tx as spendable.

wallet: Ignore duplicate tx error when publishing

---

wallet/chainntfns.go

ChainSwitch will attempt to watch for new addresses when the wallet is
associated with a network backend, but it should be successful in the case where
the wallet is offline or disconnected from the Decred network as well.

Prevent ChainSwitch from erroring with NoPeers

---

go.mod
go.sum

This includes a fix for Salsa20 on amd64 platforms when over 256GiB of the
keystream is consumed.
Salsa20 is used by nacl, which is in turn used by dcrwallet for encrypting
values in the database, but it is improbable that 256GiB of the keystream would
ever be consumed by any wallet usage.
See https://golang.org/issue/30965 for more details.

Update to latest x/crypto for Salsa20 fix

---

wallet/createtx.go
wallet/udb/txmined.go
wallet/wallet.go

Currently only supports solo buying.
This is intended to be used by the auto ticketbuyer and cancelable RPC methods
to terminate ticket purchasing early if the request should be canceled, either
due to RPC client disconnection or new blocks attached to the main chain.

Add PurchaseTicketsContext for request-scoped ticket buying.

---

wallet/addresses.go
wallet/addresses_test.go
wallet/network_test.go

The cursor index was not being set to the correct value, causing addresses to be
returned multiple times after any block or unmined transaction was received.
This has been fixed and tests have been added to ensure the behavior remains
correct, as this is not the first time address reuse has become a problem.
Fixes #1445.

Fix cursor indexes to derive next address.

---

go.mod
go.sum

wallet/v1.2.2 was incorrectly created and it was missing previous improvements
made in 1.2.1.  This is corrected in 1.2.3.

Bump to wallet/v1.2.3

---

go.mod
go.sum
internal/prompt/prompt.go
rpc/legacyrpc/methods.go
rpc/rpcserver/server.go
walletsetup.go

hdkeychain v1.1.1 is still required by the wallet module and due to usage of
package types in public API will require a major version bump to update.

Update main module's hdkeychain require to v2.0.0

---

wallet/createtx.go

The checks to ignore locked outpoints were added, but outpoints selected by the
request were not being temporarily locked, leading to double spends.

Lock selected previous outputs for concurrent UTXO selection.

---

wallet/locking_test.go
wallet/udb/addressmanager.go
wallet/wallet.go

This change simplifies the management of the wallet's locked and unlocked states
when multiple concurrent requests may lock, unlock, or change the passphrase.
It also increases concurrent use of the unlocked wallet as requests to call
unlock with a valid passphrase do not block on current operations which make use
of the unlocked wallet.
The Start/Stop/WaitForShutdown methods are no longer necessary following this
change and have been deprecated.
Closes #1178.

Replace wallet locking management goroutine with mutexes.

---

errors/errors.go
errors/errors_test.go

This will simplify situations where calling code must unwrap the error chain for
other errors and error types.

Add errors.Cause to find inital cause of error.

---

wallet/createtx.go

Fixes PurchaseTicketsContext, which always passed a zero spendLimit.

Require ticket price limit configs to be non-zero to apply.

---

spv/backend.go

Previously, it was spinning a CPU due to the error handling attempting to pick a
different peer.

Return early with context error from spv rescan.

---

config.go

The OS and arch were already being logged by dcrwallet at startup but this adds
the details to the -V output for consistency with the log and with dcrd.

Display OS/arch with -V

---

config.go
rpc/legacyrpc/server.go

also remove two unused ticketbuyer constants.

legacyrpc: prevent leak of cancel

---

spv/sync.go

The first parameter to this notification was named lastHeaderHeight
but the implementation was always calling the notification with the
count of newly-fetched headers.

Fix parameters to SPV FetchHeadersProgress notification.

---

rpc/rpcserver/server.go
wallet/addresses.go
wallet/discovery.go
wallet/hdkeychain.go
wallet/wallet.go

The following new interfaces are introduced:
- V0Scripter: for addresses used to create version 0 scripts
- SecpPubKeyHasher: for addresses created from a secp256k1 pubkey hash
- SecpPubKeyer: for addresses with a known secp256k1 pubkey
- SecpPubKeyHash160er: for addresses paying to a secp256k1 pubkey HASH160
- BIP44AccountXpubPather: for BIP0044 addresses derived from an account xpub
- AddressP2PKHv0: a union interface for v0 P2PKH addrs
- BIP44XpubP2PKHv0: a union interface for v0 P2PKH addrs with known xpubs
These interfaces describe the behavior and features of an address and allow
callers to operate on their distinctive capabilities without switching on a
concrete type.  More interfaces are planned to be introduced in the future as
address and script usage evolves.
The wallet methods …

Add wallet address interfaces.

---

rpc/legacyrpc/methods.go

This change explicitly states whether a ticket is immature or live rather than the previous implementation that grouped both immature & live tickets as live.

rpc: explicitly specify immature & live tickets in StakePoolUserInfo

---

rpc/legacyrpc/methods.go

This API bump represents the fix for the ticket status returned by
stakepooluserinfo.

Bump JSON-RPC API patch version

---

go.mod
rpc/legacyrpc/methods.go
rpc/rpcserver/server.go
spv/backend.go
spv/go.mod
spv/go.sum
wallet/addresses.go
wallet/createtx.go
wallet/discovery.go

Each instance is replaced with additional logic to first check for
implementations of the wallet.V0Scripter interface.  This allows
internal wallet types which txscript does not recognize to return
their own scripts (with script versions implied by the method name).
Fixes #1483.

Remove direct usage of txscript.PayToAddrScript

---

spv/sync.go

When a block is announced and it is attached to and becomes the new
best chain, the previous block locators saved by the SPV syncer are
cleared.  This could cause an slice out-of-bounds panic in getHeaders
since that method required that the locators be at least length 1 at
all times.  This change protects against that logic race by always
checking whether a new locator generation has zero length and if so,
new locators are generated and saved.

Generate new block locators after announced blocks.

---

go.mod
go.sum

Simnet was hard forked for compatibility with the chaincfg/v2 module
(see dcrd commit 1cedd6bbe7c65820489bc38f7f35f98882c6581b for a full
explanation).  This commit updates the wallet to remain compatible
with new simnet networks.

Update to chaincfg/v1.5.2 for simnet compatability

---

README.md
ipc.go
rpc/jsonrpc/config.go
rpc/jsonrpc/server.go
sample-dcrwallet.conf

The package implementing the server was already renamed to reflect the
decision that the server is neither legacy nor unmaintained.  The only
remaining references to the server being legacy are in dcrwallet
command line and config flags, which can't be changed without
deprecating them in at least one release cycle.

Remove additional legacy references to JSON-RPC server

---

.travis.yml

These runners are very slow to start and don't provide a tangible
benefit to the project due to the lack of any platform-specific code
that needs to be tested.

Remove macOS runners from Travis-CI

---

rpc/rpcserver/server.go
wallet/addresses.go

This removes a direct dependency on the secp256k1 package.  In
addition, because the address depends on a particular serialization of
pubkey, it is preferrable to return that serialization instead of a
type that can be serialized in different wrong ways.

Change wallet.SecpPubKeyer to return []byte

---

rpc/jsonrpc/methods.go

The previous code would pass all parameters (including null and the
empty array) as the first parameter to all passthrough requests.

Correct JSON-RPC passthrough parameters

---

errors/errors.go
errors/go.mod

The dcrwallet errors package was created at a time when the stdlib
errors package did not provide any support or wrapping/unwrapping or
detection features.  These have been added beginning in Go 1.13 in the
form of the Is and As functions.
To improve the compatibility between dcrwallet's errors and the new
stdlib features, the following additions are made:
* Kind implements error.
* Error implements the Unrwap method used by stdlib errors.Is.  Unwrap
returns the underlying error if it is not nil, falling back to
returning the Kind error if it is nonzero.
* Error implements the Is method used by stdlib errors.Is.  If the
target is an Error, Is returns if the errors match according to the
rules of Match.  If the target is a Kind, Is returns whether the
Kinds are equal and nonzero. …

Improve compatibility with Go 1.13 errors

---

chain/sync.go

Closes #1542 
We may need further changes in this Run() function to close the client in other places where an error is returned.

chain: Close RPC conn on bad server version.

---

cmd/sweepaccount/main.go
dcrwallet.go
internal/prompt/prompt.go
internal/rpc/jsonrpc/server.go
internal/rpc/rpcserver/server.go
ipc.go
wallet/addresses.go
wallet/internal/bdb/interface_test.go
wallet/udb/addressmanager.go
wallet/udb/stakedb.go
wallet/udb/upgrades.go
wallet/wallet.go
wallet/walletdb/db_test.go
wallet/walletdb/interface_test.go
walletseed/go.sum

This replaces all cases of err == x and err != x, where x is not nil,
with the equivalent usage of errors.Is.  Checking errors with
errors.Is correctly detects error conditions when an error wraps the
target error.
Replacements automated using gofmt -r.

Use errors.Is instead of error value equality

---

internal/rpc/jsonrpc/methods.go

The relative path changed when the jsonrpc package moved under the
internal directory structure.  This fixes the go:generate directive to
point to the correct relative location of the file.

Run correct JSON-RPC method generator

---

wallet/go.mod
wallet/go.sum

This removes the require on v1 secp256k1 since it is not transitively
depended on and does not need to be required at the newer version with
v2 type compatibility.

Tidy the wallet go.{mod,sum}

---

config.go

The 127.0.0.1 and ::1 IPs are already handled using the default dialer
exclusively, but when dialing localhost connections (by that
hostname), Tor proxies would fail to resolve the address.  This change
also adds the localhost host to the proxy exclusion list.
Fixes #1578

Never use proxy when dialing localhost

---

dcrwallet.go

A panic was observed deep in the bbolt module due to database file
corruption after a system crash.  Running the wallet with this
corrupted database would cause an internal consistency error in bbolt
and a panic inside of a database update.  During unwind, the bbolt
mutex was not released.  Attempting to cleanly unload the wallet in
this state caused a deadlock.  Instead, rethrow the panic when
panicing so that the full stack trace can be observed and the wallet
process to exit.

Do not cleanly unload wallet during panic

---

wallet/addresses.go
wallet/addresses_test.go
wallet/chainntfns.go
wallet/createtx.go
wallet/wallet.go

The logic to initally load the transaction filter with watched
addresses is more efficient and avoids TCP timeout issues from loading
too many addresses at once.  In addition, unlike the previous
watchFutureAddresses method, it will never load the filter with
duplicate addresses.

Combine logic for loading and watching future addresses

---

wallet/mixing.go

The length must only be reduced, not increased.

Avoid OOB panic when subslicing outpoints to mix

---

config.go
go.mod
go.sum

This updates the addrmgr and connmgr modules from the dcrd project to
their latest released versions.  These are the same versions as used
by dcrd 1.5.0-rc1.

Update addrmgr and connmgr modules

---

wallet/addresses_test.go
wallet/wallet.go

Some operations delay the database update recording the last returned
address of an account branch.  This may cause the lookahead address
watching code to set a new cursor which does not reflect these new
returned addresses, effectively causing the next child index for a new
address in the account to be reset and go backwards.  This corrects
this bug by considering the current difference between the in-memory
child index management and the values read from the db.

Avoid child index cursor backwards resets

---

assets/assets.go

The assets package is part of the main module.  It provides a single
function, Path, which returns the absolute path to any file in the
dcrwallet main module, relative to assets package.  This function is
usable by release tooling to access module file contents without
needing to copy the contents into a Go variable or constant.

Add assets package for accessing dcrwallet file assets

---

ticketbuyer/tb.go

There was a bug in the detection of insufficient balance errors
(reversed parameters passed to errors.Is) that was causing these
errors to be logged when they were intended to be silenced.  Since the
calling code already logs errors (and correctly silences the logs for
insufficient balance errors), just remove this unneeded code.

Silence ticketbuyer insufficient balance errors

---

walletseed/go.mod
walletseed/go.sum

The previous tagged walletseed release depended on pgpwordlist 1.0.0
which caused a transitive module dependency on the v1 errors module.

Prepare walletseed/v1.0.3 with pgpwordlist 1.0.1

---

go.mod

During the last series of major module bumps, the main module was
updated with pseudo zero versions (00010101000000-000000000000), which
go get cannot deal with.  This change updates all dcrwallet modules to
their latest tagged versions.

Remove pseudo-versions from main module

---

config.go

The `CSPPServer.ca` option didn't accept the same file spec's as `--cafile`, i.e. `~/.dcrwallet/cspp.pem`.

apply cleanAndExpandPath() on CSPPServer.ca option

---

internal/rpc/rpcserver/server.go

A breaking change to the ticketbuyer module introduced a ChangeAccount
field to the config.  This was a breaking change due to the field now
being required to keep previous behavior, otherwise the change account
would default to the zero account.  Specify this account explicitly in
the gRPC RunTicketBuyer method handler, so that the previous behavior
is retained.

Use source account as change account for gRPC ticketbuyer config

---

wallet/addresses_test.go
wallet/discovery.go
wallet/discovery_test.go
wallet/main_test.go
wallet/peer_test.go

This is a similar fix as 848d33040d, where the address cursor was
occasionally being reset.  In this case, the cause was occuring during
address discovery, and it was possible to introduce address reusage
this way when the RPC syncing process temporarily disconnected and
reconnected.
Tests have been added to ensure the the reset fix works as intended.
These tests fail without the changes in discovery.go.
A few minor changes to the wallet package's testing features were
added.  A peerFuncs type was introduced to allow definitions of custom
implementations of the Peer interface.  Wallet logs may also be viewed
now when running tests, though due to the package global logger, it is
recommended to only use this feature when running one test at a time
to avoid intertwined logs.  For example, to …

Avoid address cursor resetting during address discovery

---

internal/rpc/jsonrpc/server.go

Panics during RPC handlers were causing the waitgroups to not be
decremented, as the stack began unrolling before the Done call.  This
would cause the wallet process to hang at shutdown.
To remedy, these calls are now deferred so they are never missed in
the case of a panic.

Defer waitgroup Done calls in JSON-RPC server

---

internal/rpc/jsonrpc/methods.go

A copy of the variable is created which the closure now closes over,
rather than closing over the mutating iterator variable.

Avoid race accessing a range loop iterator

---

version/version.go

Releases will now use the empty string for the prerelease field, and
"release.local" for build metadata.  This indicates that the code is
for a release, but the release was built from the repo or using go get
without the release build tool.
Development versions will use "pre" for the prerelease and default to
no build metadata.
This PR contains a series of two commits.  The first will be tagged and then required from the release branch.  The second exists so that builds from master do not display as release builds.

Update version prerelease and build metadata naming scheme

---

internal/uniformprng/prng.go
wallet/shuffle.go
wallet/txauthor/cprng.go

This is significantly safer than using math.Rand.Shuffle for wallet's
purposes because the PRNG is cryptographically secure.

Add uniformprng package and use for shuffling

---

go.mod
go.sum

This cspp version no longer contains a copied internal chacha20
package, allowing for the reuse of the one provided by x/crypto.
This also transitively requires a newer version of wsrpc with improved
ping handling.

Upgrade to cspp 0.3.0

---

chain/log.go
internal/loader/log.go
wallet/log.go
wallet/udb/log.go

These functions are unnecessary and any usage can be replaced with
UseLogger(slog.Disabled).

Remove DisableLog functions

---

internal/rpc/jsonrpc/methods.go
internal/rpc/rpcserver/server.go
ticketbuyer/tb.go
wallet/createtx.go
wallet/wallet.go

Rename the only remaining method (PurchaseTicketsWithResponse) to
simply PurchaseTickets.

Remove deprecated ticket purchasing methods

---

wallet/createtx.go

When the context passed to the ticket purchasing methods is cancelled,
an error log was being created for the failed deferred call to
watchHDAddrs.  Rather than continuing to call this method, if the
context is cancelled, return early from the deferred function.
Because the automated ticketbuyer uses context cancellation to stop
ongoing purchases whenever the ticket price changes, this was causing
unnecessary and unhelpful errors to be logged.

Avoid spurious error logs caused by cancelling ticket purchasing

---

internal/rpc/jsonrpc/methods.go
internal/rpc/rpcserver/server.go
wallet/udb/addressmanager.go
wallet/wallet.go
walletsetup.go

This changes the names of the wallet methods to access BIP0044
extended public and private keys.  The use of "master" in the method
names was misleading, as this can be confused with the master BIP0032
key.

Use better names for accessing BIP0044 xpubs/xprivs

---

wallet/udb/addressmanager.go
wallet/udb/initialize.go
wallet/udb/internal_test.go

Close #1470 
This adds a new package-level type and variable to the `wallet` package that allows consumers to set their preferred PBKDF algorithm.
This allows external tests to use a faster (albeit unsafe) algorithm to speed up wallet creation.
It also adds a grpc endpoint to the `WalletLoaderService` so that remote users can also setup this parameter before creating a wallet.

Switch to per-network scrypt options

---

wallet/wallet.go

In watchHDAddrs, if the context is cancelled before an error is
received on the watchError channel, a goroutine closing over the
returned count may still be running, introducing a data race on the
count variable.  This is fixed by replacing the multi-channel select
operation on both the watchError and the context's Done channel with a
single read of the watchError channel.  This prevents count from being
read while the goroutine closure may still modify the count, and is
context safe since the closure will send any context errors down the
watchError channel.
Fixes #1682.

Fix data race

---

internal/rpc/jsonrpc/methods.go
internal/rpc/rpcserver/server.go
wallet/wallet.go

When the P2SH address for the script is already known by the wallet,
skip doing any further imports or rescans in the importscript method.
Fixes #1412.

Avoid duplicate JSON-RPC script imports

---

internal/rpc/jsonrpc/methods.go
internal/rpc/rpcserver/server.go
spv/backend.go
wallet/addresses.go
wallet/addresses_test.go
wallet/coinjoin.go
wallet/createtx.go
wallet/mixing.go
wallet/multisig.go
wallet/wallet.go

Address is a generic address type, which may or may not represent an
address or key managed by the wallet.  Unlike dcrutil.Address, this
interface defines the method to produce the script bytes and version,
whereas dcrutil.Address cannot create a script and instead the
txscript package must be used (but this operation does not work for
every possible dcrutil.Address implementation).
KnownAddress is an Address with additional methods providing details
regarding the wallet account associated with the address.  A new
wallet method, also named KnownAddress, replaces the previous AddrInfo
method which returned an udb type.
Three other address interfaces are defined which add to the methods of
the KnownAddress interface.  These are:
* PubKeyHashAddress: a KnownAddress for any P2PKH output …

Define Address and KnownAddress interfaces

---

internal/rpc/jsonrpc/methods.go
wallet/addresses.go

The wrong implementation for P2SH addresses was being returned by
KnownAddress.  This caused a type conversion panic from
validateaddress after the address was handled like a P2PKH address.
Fixes #1693.

Fix type confusion

---

internal/rpc/jsonrpc/marshaling.go
internal/rpc/jsonrpc/methods.go
wallet/addresses.go

An ImportedAddresses method is added to Wallet which returns
[]KnownAddress for each imported address of an account.  The method
takes an account name, but currently the only valid account name is
"imported".
Some infractructure was added to the jsonrpc package to simplify the
marshaling of address arrays and reduce memory usage.  This can be
reused for other methods later, to avoid the need to allocate []string
objects for JSON serialization.

Fix getaddressesbyaccount for the imported account

---

rpc/api.proto

This option enables consumers of the API to `import` `api.proto` into other protobuf packages.

Added go_package option

---

internal/rpc/jsonrpc/methods.go
internal/rpc/rpcserver/server.go
ticketbuyer/tb.go
wallet/udb/addressmanager.go
wallet/udb/txmined.go
wallet/wallet.go

This is done by defining types idenical to the old udb.Balances and
udb.AccountProperties in the wallet package, and modifying udb's
definitions to be type aliases of an unnamed struct type.
While here, clean up some method names and change the return on
AccountBalances to a slice instead of a map.  The map served no
purpose and the only caller simply created a sorted slice from the map
values anyways.

Remove more udb types from public wallet API

---

wallet/wallet.go

The previous limit used to be 100, but was reduced to 10, however the
error message was never updated for this change.

Describe current account gap limit in error message

---

rpc/Dockerfile
rpc/regen-docker.sh
rpc/regen.sh

The addition of the go_package directive in commit 3710c8d8 broke
regenerating the scripts locally.
This fixes the issue by using the source_relative option when generating
bindings.
It also fixes the docker version by updating to the latest golang docker
image and mounting from the root wallet source dir so that module
directives are correctly accounted for inside the image.

rpc: Fix grpc binding generation

---

wallet/chainntfns.go

A non-nil pointer to the zero value was being passed previously.  This
was causing unmined transactions to panic the wallet after a block
header was failed to be looked up for the zero hash.
Fixes #1719.

Pass nil udb.BlockMeta when processing unmined transactions

---

rpc/jsonrpc/types/methods.go
rpc/jsonrpc/types/methods_test.go
rpc/jsonrpc/types/results.go

Most of these appear to have been merged into prior versions of
dcrjson, without the associated dcrwallet change ever being
implemented or approved, before the types package was split into the
dcrwallet module.  Because this package globally registers commands
into dcrjson for command listing and help, these types and the init
registration for them should be removed.
After dcrctl is updated with this change, it will no longer present
listings for the unimplemented dcrwallet RPCs.

Remove request/response types for unimplemented RPCs

---

rpc/client/dcrwallet/methods.go

The RPC returns a JSON object, but the client was unmarshaling this as
[]string instead.

Fix JSON deserialization of gettickets result

---

rpc/client/dcrwallet/client.go

Implementations of Caller are to avoid any unmarshaling of a result
when the result variable passed to the call is nil.  This was not
being performed for the RawRequest wrapper, which caused failing
client calls when results were not needed or discarded.

Avoid unmarshaling result when result variable is nil

---

wallet/createtx.go

The %v format verb creates poorly formatted errors when used with byte
slices.

Format signature validate errors with hex

---

rpc/client/dcrwallet/marshaling.go

The JSON-RPC server expects that transactions be sent as JSON strings
in hex encoding.  The previous client code was not performing the hex
encoding, which would result in various escape codes in the JSON and
errors at the server during hex decoding.

Hex-encode marshaled transactions

---

internal/rpc/jsonrpc/errors.go

When a passthrough RPC is performed, any RPC errors will be of type
*wsrpc.Error.  These describe the JSON-RPC error object, and a
suitable server error can be created from its fields rather than using
a generic error code.

Do not clobber RPC passthrough error codes

---

wallet/createtx.go
wallet/wallet.go

txToOutputs no longer publishes the new transaction to the network
automatically.

wallet: add publishAndWatch function

---

rpc/client/dcrd/calls.go

A return statement was missing in the error handling path, which would
result in a nil pointer dereference in the happy path.

Return from CFiltersV2 on error

---

internal/rpc/rpcserver/server.go
wallet/wallet.go

PublishTransaction will now serialize the passed tx itself.

wallet: remove serializedTx from PublishTransaction function

---

wallet/mixing.go

When large UTXOs are mixed, the mixed output amount was chosen as the
smallest preprogramed amount which would result in one or more mixed
outputs.  This had the unfortunate side effect of advertising seldom
used mixed output amounts to a CoinShuffle++ server which were
uncommon relative to amounts advertised by clients participating in
mixed ticket buying.
As a workaround, the current sdiff is queried, and a decision is made
whether to use an even smaller mixed amount which will allow for
better pairings.

Avoid uncommon CoinJoin output amounts

---

wallet/chainntfns.go

When a transaction is processed (whether it is mined or in mempool),
any referenced previous outputs should be unlocked by the wallet.
Transaction creation already unlocked selected outputs when
transactions were created by the same wallet, but transactions seen
from the network were not causing spent locked outpoints to be
removed.
Fixes #1752.

Unlock previous outpoints during transaction processing

---

wallet/createtx.go

~~Right now on grpc calls, we are returning the unsigned ticket hash at our TicketHashes.~~
~~This PR fixes it so we send the proper hash after signing the ticket.~~
The ticket expiry is not being calculated before appending the hash. This PR fixes it

Fix returning ticket hash on purchaseTicket with no expiry

---

internal/rpc/jsonrpc/server.go

The method name is user input and was being printed to standard
output, so it must be sanitized.
Fixes #1756.

Format logged RPC method names with %q verb

---

dcrwallet.go

This also fixes the zeroing to correctly operate on a prompted
passphrase, instead of zeroing one set through the config or flags.

Avoid race on zeroing wallet public data passphrase

---

go.mod
go.sum

https://github.com/etcd-io/bbolt/releases/tag/v1.3.5
https://github.com/gorilla/websocket/releases/tag/v1.4.2

build: bump bbolt and websocket versions

---

rpc/regen.sh

As discussed at matrix, using dashes `-` on the method name will throw an error when using dash, as /bin/sh: 
```
vctt@vctt:~/projects/decred/dcrwallet/rpc$ ./regen.sh 
./regen.sh: 3: ./regen.sh: Syntax error: Bad function name
```
This PR changes it to use underscore `_`, instead.

Change regen.sh methods name to use underscore instead of dashes

---

ticketbuyer/tb.go

Larger limits are still possible but must require manually setting
the larger limit (--ticketbuyer.limit).

Limit mixed ticketbuying to one when limit is unset.

---

README.md

This updates the main README so that it is formatted similarly to dcrd's README.
Added new clarity in installing binaries and building from source.
My primary goal is to have some commonality between repo docs and formatting, so I used dcrd as a starting point. If things needed to be exclusive to dcrwallet, I tried to capture that nuance.

docs: Update main README.md and standardize with dcrd

---

wallet/mixing.go

The math was wrong here, and was causing the next smallest split
denomination to be chosen below the sdiff, instead of the one
immediately below it.

Fix denom chosen for change mixes of large outputs

---

run_tests.sh

While here, switch the shell interpreter to /bin/sh instead of bash.
There is nothing about this script that requires bash.

Update test script to run all vet checks

---

wallet/wallet.go

A tree variable was declared but never changed from the zero value,
causing all stake tree outputs to be overwritten with the regular tree
in the loop below.

Fix setting of output tree

---

internal/rpc/jsonrpc/methods.go
wallet/chainntfns.go
wallet/createtx.go
wallet/mixing.go
wallet/wallet.go

Outputs should be locked or unlocked even when the tree is not
necessarily known (tx hash collisions can be disconsidered) and this
solves a bug with listunspent reporting stake outputs even when they
were locked over RPC (where the tree is, again, unknown).

Remove stake tree distinction from locked outpoint handling

---

rpc/client/dcrwallet/methods.go
rpc/client/dcrwallet/methods_test.go

A new type SignatureErrors is defined, which is declared as a
[]types.SignRawTransactionError.  This type implements the error
interface and is used to return any signature errors in the response,
along with the partially signed transaction.

Unmarshal and return signrawtransaction errors

---

dcrwallet.go

The client should be nil when a vspd server is not configured.

Fix ticket autobuyer when no VSP is configured

---

wallet/addresses.go
wallet/udb/addressdb.go
wallet/udb/addressmanager.go
wallet/udb/upgrades.go
wallet/udb/upgrades_test.go

Note to reviewers: this contains a database upgrade. Back up your DB before testing.
___
A database upgrade is introduced which rewrites all BIP0044 accounts into a new serialization format.  The account "row" is modified to only contain the information that never changes (such as the account's extended pubkey and privkeys) and a "variables" buckets are created for each individual account to record, in separate key/value pairs, account fields that do change over time (such as the account name and last used/returned child indexes).  This allows faster access to read and modify the particular field(s) in question, rather than requiring all account metadata to be read or written back to the db when only a small amount of data must be changed.
Upcoming PRs will take advantage of the account …

Upgrade database account format

---

rpc/client/dcrd/calls.go

PublishTransactions was calling PublishTransaction, so both names were
included in the error.  This change adds a helper function so that
only PublishTransactions is included in these errors.

Reduce verbose function names in error logs

---

walletsetup.go

This prevents issues with the printed mining address from turning
invalid if a cointype upgrade from legacy to SLIP0044 occurs when the
wallet is first started.

Unconditionally use SLIP0044 cointype on simnet

---

p2p/peering.go

A limit of 4096 bytes is imposed on the response body, of which the
first 16 results must fit.  This leaves room to add more fields to the
seeder response objects without being too large, while limiting
attacks from malicious seeders that send non-terminating json object.
While here, improve the log messages to report which seeder any errors
occurred for.

Limit how much of seeder response may be decoded

---

vsp/feeaddress.go
vsp/payfee.go
vsp/poolfee.go
vsp/ticketstatus.go

vspd was accepting `VSP-Client-Signature` base64 encoded, but then returning `VSP-Server-Signature` hex encoded.
This was changed in decred/vspd#179 so both are using base64 encoding.

vsp: base64 decode server signature

---

internal/rpc/jsonrpc/methods.go

The check for maximum output value in a createrawtransaction JSON-RPC
call was performing a check against an untyped constant of max atoms,
when the value being compared was floating point.

Perform correct range check for amount type

---

errors/errors.go
go.mod
wallet/udb/addressdb.go

The xerrors package was used by dcrwallet's errors package to
implement error wrapping for older versions of Go (1.12 and earlier)
which did not support these features in the stdlib.  Since these Go
releases are unsupported by the project, the wrappers can be switched
to calling the stdlib instead.
With this change, go vet was able to report one invalid format string
that was not noticed before.

Remove requirement on golang.org/x/xerrors

---

dcrwallet.go

The VSP client instance must be created with a change account, and
this should be the same as the purchase account if CoinShuffle++
mixing is disabled and the --changeaccount option is not set.

Handle unset change account for unmixed ticketbuying

---

wallet/createtx.go
wallet/wallet.go

Vote transactions passed to Wallet.SignTransaction (which is never
done except possibly through an RPC request) are expected to contain
the correct stakebase input script as demanded by consensus for that
network.

Fill stakebase script during vote creation, not signing

---

wallet/chainntfns.go
wallet/createtx.go
wallet/difficulty.go
wallet/discovery.go
wallet/notifications.go
wallet/rescan.go
wallet/sidechains.go
wallet/tickets.go
wallet/udb/stakevalidation_test.go
wallet/udb/tx_test.go
wallet/udb/txdb.go
wallet/udb/txmined.go
wallet/udb/txunmined.go
wallet/udb/upgrades.go
wallet/udb/upgrades_test.go
wallet/utxos.go
wallet/wallet.go

Note to reviewers: this contains a database upgrade. Back up your DB before testing.
---
Unpublished transactions are unmined transactions which are
specifically recorded as unpublished to the network.  These
transactions are not rebroadcast on startup.  It is necessary to save
unpublished transactions to prevent some previous wallet outputs from
being double spent across application restarts, or to persist
partially signed transactions.
This commit adds the database handling for recording unpublished
transactions but does not yet record any transactions in this state.
This will be used by vspd clients in the future to record unpublished
fee and ticket purchase transactions.

Allow unpublished transactions to be saved to DB

---

chain/sync.go
config.go
dcrwallet.go
internal/loader/loader.go
spv/sync.go
wallet/chainntfns.go
wallet/wallet.go
walletsetup.go

With this mode enabled, any ticket added to the wallet must be done so
manually over RPC using the addtransaction method.  This allows wallet
owners to selectively add tickets to their wallets and prevent other
ticket buyers from reusing a voting address to get free votes.

Add config flag to never add tickets from network syncers

---

wallet/internal/snacl/snacl.go

Seal may be passed a byte slice to append the ciphertext to, so pass
an appropriately sized byte array with the leading nonce bytes.

Modify secretbox.Seal usage to avoid extra alloc

---

go.mod
go.sum

This allows UTC to be added to the LOGFLAGS environment variable to
log all timestamps in UTC.

Bump slog to v1.1.0

---

wallet/wallet.go

Look up the redeem script for p2sh outputs in `(*Wallet).ListUnspent`. The `ListUnspentResult` struct already had the field, it was just unused.

wallet: add redeem script for p2sh listunspent results

---

ticketbuyer/tb.go
vsp/payfee.go
vsp/vsp.go
wallet/createtx.go
wallet/wallet.go

On this PR I am spliting changes which are related to vsp from https://github.com/decred/dcrwallet/pull/1819 to this PR. 
I will rebase https://github.com/decred/dcrwallet/pull/1819 to keep only changes related to db.

Vsp changes 

---

vsp/vsp.go
wallet/createtx.go
wallet/udb/upgrades.go
wallet/udb/vsp.go

**contains db upgrade -- backup db before testing**
This PR depends on  #1840
~~This PR stills a wip.~~
~~Right now it is not possible to know the status of a registered vspd ticket. This PR updates the wallet db so we can know if a ticket fee is paid, and its txid.~~
This PR fixes the double spend bug, which a ticket fee tx would be double spend with the ticket auto buyer.
- I Created a new vspBucket and two subbuckets `pendingFeeKey`, `VotingPreferencesKey` (right now still not using the voting preference bucket, but the idea is saving ticket's voting preference.
- vsp tickets are being saved on the vspBucket keyed by timestamps.
- vsp tickets fee are being saved on the pendingFeeKey bucket, keyed by ticket's hash
- changed how vsp ticket fee processments are being done
- added …

Add VSP ticket and fee txs into wallet db 

---

go.mod
rpc/jsonrpc/types/methods.go
rpc/jsonrpc/types/methods_test.go
rpc/jsonrpc/types/walletsvrwscmds_test.go

This updates the `rpc/jsonrpc/types` package to properly mark the authenticate command as only being available via websockets.
While here, it also corrects the registration for the shared `dcrd` methods which were doing double registration with the second one being ignored.
Finally, the tests are updated for `dcrjson` v3 accordingly.

rpc/jsonrpc/types: Authenticate websocket only.

---

config.go
internal/cfgutil/curve.go
internal/cfgutil/file.go
internal/rpc/jsonrpc/server.go
ipc.go
rpcserver.go
x509_test.go

Client authentication for JSON-RPC previously required configuring a
user and password, with both client and server holding knowledge of
the secret.  By allowing client authentication to be performed with
TLS client certificates, only the client side must hold a private key,
as long as the dcrwallet server is configured to trust the public key.
The gRPC server had no client authentication at all previously, and
the only reason this was marginally safe was that all requests that
could use a wallet key also required supplying and checking the wallet
private passhprase in the request.  However, with per-account
passphrases, this is no longer a suitable mechanism, and instead the
entire transport layer must be authenticated.  The simplest way to
perform this is by requiring and verifying …

Require client cert auth for gRPC, allow for JSON-RPC

---

internal/cfgutil/curve.go

This elliptic curve is not a supported algorithm for the TLS server.
dcrctl clients are unable to talk to a server that generated one of
these keys, and the server will log an error in this case:
http: TLS handshake error from [::1]:46531: tls: unsupported certificate curve (P-224)

Remove --tlscurve=P-224 support

---

x509_test.go

This test failure was observed on Github CI, but I am not able to
reproduce locally after many tries.  If this occurs again, show the
full error to give more insight.

Show full error when test fails

---

p2p/peering.go

This bumps the maximum supported protocol version to the upcoming
version 8, which adds the getinitialstate/initialstate pair of messages.
It also fixes a bug that could happen if the wire package was upgraded
to a version with a new protocol version but the wallet's p2p package
was not updated: in that case SPV clients could negotiate an incorrect
version and fail in undefined ways.
This is fixed by ensuring the protocol version advertised by the wallet
is always the maximum one the wallet understands as opposed to the
default one for NewMsgVersion().

p2p: Bump max supported pver

---

p2p/peering.go

This prevents nodes from dropping our connection due to believing we
stalled replying with an appropriate miningstate/initstate msg.

p2p: Reply to getminingstate/getinitstate

---

README.md

Encrypting public data in the wallet database is a non-default option,
and generally discouraged due to all of the other public data which is
not encrypted.  Despite what the README said, there are currently no
plans to encrypt the rest of this data, as it would break some of the
ways cursors are used to iterate over saved values.

Remove paragraph about public data encryption

---

internal/rpc/rpcserver/server.go

Since the client is now authenticated using TLS client certificates,
it is safe to allow gRPC methods to be called and use wallet private
keys even if the request itself does not provide the private
passphrase.  For backwards compatibility, keep the existing behavior
when a nonzero passphrase is provided, but do nothing to unlock the
wallet or check the passphrase when it has zero length.
In order for this to be useful, a future commit must add the ability
to lock or unlock the wallet from separate methods.  This
functionality already exists for individually-encrypted accounts.

Make passphrases optional in most gRPC methods

---

config.go
rpcserver.go

We need to not necessarly require TLS client cert authentication for
JSON-RPC simply because the gRPC server is running and requiring it.
This change removes the --authtype flag, replacing it with only a
--jsonrpcauthtype flag to change the behavior of the JSON-RPC server.
TLS client cert authentication remains required for gRPC, and requires
the presence of a file containing trusted client certificates.
While here, improve logging to warn when gRPC listeners are
configured, but no trusted client certs exist to authenticate any
connections.

Allow gRPC and JSON-RPC auth types to be separately specified

---

rpcserver.go

Even if these user/pass settings are provided, do not use them except
with the basic authentication mode.

Do not require HTTP basic auth with client certs

---

dcrwallet.go
internal/rpc/rpcserver/server.go
internal/vsp/vsp.go

At least this should allow all of the background goroutines vsp.New
starts to exit.

Provide a context when creating vsp clients

---

internal/rpc/rpcserver/server.go

the GetVSPTicketsByFeeStatus grpc request is bringing hashes with same value. 
This PR fixes it

fix all hashes with same byte

---

internal/rpc/rpcserver/server.go

This fixes the change account from always using the default account
without CSPP ticket purchasing, when a non-default funding account is
used.  In other words, the new change accout field is now required to
be specified to be the same as the funding account to keep the old
behavior.

Use change account as is in PurchaseTickets gRPC method

---

go.mod
go.sum

The v1.33.0 tag was pushed by accident, and the gRPC project
recommends to stick with v1.32.0 until v1.33.1 is available.
See https://github.com/grpc/grpc-go/issues/3945 for more details.

Downgrade gRPC to v1.32.0

---

internal/vsp/client.go
internal/vsp/feeaddress.go
internal/vsp/payfee.go
internal/vsp/poolfee.go
internal/vsp/ticketstatus.go
internal/vsp/types.go
internal/vsp/vsp.go

This commit adds a client type which handles both GET and POST
requests for the vspd API.  The server signature is always checked,
and during POSTs, the request body is signed using the private key of
some wallet address.
This also fixes the handling of HTTP 400 status codes for bad client
requests, and will unmarshal these into a BadRequestError type.

vsp: Remove code duplication

---

internal/rpc/jsonrpc/methods.go

They were using the default value 0 as the transaction version, which
is invalid.
Fixes #1911.

Fix redeemmultisigout(s) methods to set transaction version

---

internal/vsp/vsp.go

The tx must be recorded to the db to prevent double spends across
wallet restarts.

vsp: Save unpublished fee tx to database

---

internal/rpc/jsonrpc/methods.go

When --csppserver was configured, but --mixaccount and
--mixchangeaccount were not, the sendtoaddress/sendfrom/sendmany
JSON-RPC calls were failing due to a failed lookup of account "", as
there was no verification that either --mixaccount or
--mixchangeaccount were configured with a nonzero value.  This change
modifies the logic to pick the appropriate change account for sends
from the mixed account only when all of these options are configured.

Fix change account detection for incomplete configs

---

wallet/createtx.go

The refactors to support the new vspd mode for ticket purchasing ended
up breaking support for generating unsigned tickets.
This adds the appropriate checks to ensure when ticket purchasing was
requested to be unsigned, the wallet doesn't attempt to publish and
register the ticket with the remote VSPs.

wallet: Skip publishing unsigned split and vsp fee txs

---

config.go
rpcserver.go

Respect alt --appdata default location of clients.pem

---

spv/sync.go

This service flag indicates v1 gcs cfilters, which the wallet no
longer requests or uses.
Depends on #1924

Remove SFNodeCF from required services

---

internal/vsp/errors.go
internal/vsp/vsp.go
wallet/wallet.go

When the VSP has already received a fee payment as valid, the wallet
should update its status for the ticket when trying to process the
payment again on a later restart or due to a RPC request from
Decrediton.  This was not being done, and instead the API error
returned by vspd for this situation was being silently ignored by the
SyncVSPFailedTickets gRPC method and never logged, because that method
was erroneously assuming the error would always be logged elsewhere
(nevermind that dcrwallet logs are not the method by which RPC clients
should obtain error information).

Handle VSP's successful processing of fee payment

---

config.go
dcrwallet.go
internal/vsp/feeaddress.go
internal/vsp/vsp.go

The default maximum fee is set to 0.1 DCR, and matches the previous
hardcoded fee check.

vsp: Make maximum fee configurable

---

wallet/createtx.go

The input selection was not randomized previously (as this code did
not use the randomized InputSource that was previously added for input
selection for all funded transactions).
Randomizing these chosen inputs may (randomly) allow VSP-using ticket
purchasing to succeed where it would have reliably failed before, if
the user's high-valued UTXOs are not selected for fee payments.  This
would then enable a user or a client to reattempt the purchase.

Randomize inputs selected for paying VSP fees

---

wallet/createtx.go
wallet/wallet.go

Rebased over #1937 
---
This removes the wallet's unexported txToOutputs method by replacing
it with an authorTx method that instead of taking a dozen parameters,
uses a struct.  While not only cleaner, this also allows more fields
of the struct to be set by the method, which will be used in upcoming
commits to change where and how the created transactions are added to
the wallet and published to the network.

Replace txToOutputs method, use struct for many parameters

---

wallet/createtx.go
wallet/wallet.go

Rebased over #1938
---
This will help callers use the correct ordering for recording,
notifying, and publishing transactions after they are created and
signed.

Split out recording and notifying new txs from authorTx

---

internal/rpc/jsonrpc/errors.go
wallet/udb/addressmanager.go

This error no longer returned a helpful error message about what to
run ever since the per-account encryption was implemented, because
walletpassphrase was not in all cases the correct method to run if the
account was encrypted by unique keys.  Fix this error message to
suggest either walletpassphrase or unlockaccount, and wrap
errors.Locked errors when the account is locked and created from an
xpriv, not an xpub.

Fix JSON-RPC error message when sending from locked wallet

---

spv/sync.go

The map key must be chainhash.Hash, not *chainhash.Hash.
Spotted by @chappjc.

Fix type in sync.Map.Delete call

---

chain/sync.go
internal/rpc/jsonrpc/methods.go
wallet/tickets.go

This also includes a change for the gettxout requiring adding an
additional parameter for the tree of the output.

Bump required dcrd RPC server version to 7.0.0

---

wallet/mixing.go
wallet/wallet.go

Only consider regular transactions, never any stake ones.
If multiple outputs with zero values are found in the transaction,
these are not considered a mix for having similar output values.
If any output script is reused in the transaction, the tx is not
considered a mix.

Narrow rules of what is considered a possible coinjoin

---

errors/errors.go
errors/errors_test.go

This fixes an issue where a wrapped errors.Error can lose its Kind
matching when another error object is used in the E function.  There
is still the issue of the earlier error being forgotten dropped
entirely, but this at least fixes most detection issues that depend on
the Kind matching.
A test (which fails without the patch) is added to demonstrate the
issue.

Promote error kind even if wrapped error would be overwritten

---

internal/vsp/feepayment.go

Base64 encoding the request is the only safe way to receive the
original bytes without any modifications, and is performed
automatically when marshaling and unmarshaling []byte using
encoding/json.

Expect VSP's echoed requests to be base64 encoded

---

sample-dcrwallet.conf

It should read "authenticate a TLS connection" or "authenticate TLS
connections".  We choose the latter since multiple connections may be
established during program lifetime.

Fix grammar in the sample config

---

internal/rpc/rpcserver/server.go
ticketbuyer/tb.go

This PR checks for password when running the buyer. This is necessary for sending grpc commands without the password.
This is needed for running ticket buyer or account mixer, without sending the passphrase through grpc

check for password when running buyer

---

go.mod
go.sum
wallet/udb/upgrades.go

This module was used to create a version 1 cfilter for the genesis
block in an upgrade path.  It does not need to do this any longer, as
version 2 cfilters replace these filters in a later DB upgrade.

Remove old gcs/v2 module from build

---

wallet/udb/txmined.go

When selecting UTXOs, skip over those unmined transactions which are
marked unpublished, not mined transactions.
Unset a transaction from being marked unpublished if it is moved from
the unmined buckets to the mined transaction buckets.
Issue discovered and debugged by @alexlyp.

UTXO selection fixes for unpublished transaction outputs

---

wallet/udb/txmined.go

Same fix as previous, but in the ForEachUnspentOutpoint method.

UTXO selection fix for unpublished transaction outputs

---

wallet/udb/txmined.go

When selecting UTXOs, skip over those unmined transactions which are
marked unpublished, not mined transactions.
Unset a transaction from being marked unpublished if it is moved from
the unmined buckets to the mined transaction buckets.

[release-v1.6] UTXO selection fixes for unpublished outputs

---

wallet/mixing.go

Ignoring this can lead to unmixable outputs, as they will always be
rejected when submitted as a single input to the CoinShuffle++ server.

Consider tx fees when choosing a mix amount and count

---

wallet/mixing.go

This would be eventually be fixed during the dust check, but it's
clearer to just leave it zero, as we expect no change at all.

Zero change value when change cannot be included

---

wallet/createtx.go
wallet/udb/txmined.go
wallet/wallet.go

When a wallet account only contains a single UTXO, it is not possible
to perform VSP ticket purchasing, because at least two UTXOs are
required: one to fund the ticket purchase, and a second to pay the
VSP.  When UTXO exhaustion is detected during a ticket purchasing
attempt with a VSP configured, attempt to split a UTXO into two
outputs, followed by a reattempted ticket purchase.
The ticket purchase reattempt must be done with a zero minconf policy,
since it still uses the normal UTXO selection instead of precisely
using the newly created outputs from the extra split transaction.
This is not ideal, and may also result in spending other unconfirmed
outputs in the account that were not considered earlier during the
failed purchase attempt.

Split a single UTXO into two outputs for VSP ticket purchasing

---

wallet/mixing.go

The mixValue variable was not being assigned to the expected value in
the splitPoints array, causing the loop to skip to the last common mix
denomination and result in an insane fee contributed to the coinjoin
transaction due to the mixed output count being limited to a maximum
of four per input.
Fixes #2000.

Fix output mixing from using lowest denom with insane fees

---

wallet/createtx.go
wallet/wallet.go

After we create an extra split output to deal with UTXO contention in
a VSP ticket purchase, there is no need to perform UTXO selection
again to reserve an output for a single VSP fee payment.  Add an
unexported field to the purchase ticket parameters so that upon
reentry, this output can be used directly.

Use extra split output rather than selecting random UTXOs

---

wallet/mixing.go

The low fee check was not being performed after iterating down to the
lowest mix amount.  This resulted in low-fee submissions to the
CoinShuffle++ server, which are now being rejected as an invalid
submission.

Perform low-fee check for smallest mix denom

---

wallet/mixing.go

The low fee check was not being performed after iterating down to the
lowest mix amount. This resulted in low-fee submissions to the
CoinShuffle++ server, which are now being rejected as an invalid
submission.

[release-v1.6] Perform low-fee check for smallest mix denom

---

config.go
dcrwallet.go
log.go

This works the same as dcrd's flag by the same name.  When enabled,
logs will only be written to standard output, and not to any log files
managed by dcrwallet itself.
Of course, persistent logs are useful, so any production setup using
this flag is expected to capture standard output and redirect it to
syslogd, the systemd journal, etc.

Implement nofilelogging config flag

---

dcrwallet.go
internal/loader/vsp.go
internal/rpc/rpcserver/server.go

Add to the map when the VSP client is created for the ticket autobuyer
with the global application settings.
This will be used by an upcoming change to the JSON-RPC server to
allow voting preferences to be set and updated through this server.
Currently, it is only possible to modify VSP voting preferences for
registered tickets through the gRPC server.

Move package-global VSP client map to loader package

---

internal/rpc/jsonrpc/config.go
internal/rpc/jsonrpc/methods.go
rpcserver.go

There was previously no way using dcrwallet to update the choices for
VSP-bought tickets through the command line autobuyer.  This fixes
this, by performing the API call(s) whenever vote choices are set
using the setvotechoices method, and a VSP host is configured in the
dcrwallet settings.

Set VSP choices from setvotechoices JSON-RPC method

---

wallet/createtx.go

recordAuthoredTx records a transaction to the database, which requires
the mutex to be acquired prior to opening the database transaction.
Without this added locking, a data race from both reading and writing
to the w.lockedOutpoints map is possible.

Add missing locking for UTXOs, locked outputs

---

wallet/createtx.go
wallet/udb/addressmanager.go

This backports commits d963f169f3eb0d0d294c2d4ed6a1108ca8e3d669 and 445ae2a0cf878548411d1a341e26f611e39d9575.

Backport more fixes from master

---

internal/vsp/client.go

The header name "VSP-Server-Signature" is already stored in a package
variable so there's no need for it to be hard-coded in the do() func.

vsp: Remove hard-coded header name.

---

internal/vsp/client.go

Between the original pull request being created, and this being
rebased over master, the variable used here no longer exists and broke
the build.

Revert previous

---

internal/vsp/feepayment.go

The "received" status is expected during normal operation. The wallet should not just log a warning, it should handle this status the same was as the "broadcast" status - continue waiting for the status to update to "confirmed".

Handle VSP ticket status "received".

---

wallet/createtx.go

When the additional split transaction must be created, the total
balance from the account that had been reserved for all fee txs and
all ticket purchases can be summed together, to determine if it is
enough to create the additional split transaction.  Previously, only
the partial balance of some of the selected inputs were being used,
and this had been triggering an unnecessary insufficient balance error
when attempting to create the additional split transaction would have
been a better idea.

Improve heuristic for creating additional split tx

---

internal/vsp/feepayment.go
internal/vsp/vsp.go

The vsp package contained a bug where the partial transaction provided
by the wallet package through a callback function was being completely
ignored, and a new fee tx was being constructed from scratch.  This
caused two bugs:
1. The inputs selected by the wallet, specifically for paying the VSP
fee, were not being used.  This could result in these inputs not being
spent, and remaining locked.
2. If the VSP client was configured with an account policy that
differed from the purchase tickets request used by the wallet, the VSP
fee would be paid out of the wrong account.  This also had the
potential to break privacy guarantees in mixing wallets, by possibly
correlating mixed funds with change.
This change fixes this bug by always using the provided transaction
inputs for constructing the …

Use wallet-provided inputs for paying VSP fee

---

signal_unix.go

When the SIGHUP signal is received, the process should perform
graceful shut down rather than dying from the unhandled signal.
For clarity, the signals which will cause shutdown have been moved to
new filename so it does not remain specific to only SIGTERM handling.
Refs decred/dcrd#2644.

Handle SIGHUP with clean shutdown

---

internal/vsp/feepayment.go

I had this in an earlier version of the previous commit but removed it
because fp was being unconditionally set to a non-nil struct.
However, some of the early returns will return nil, and this will
modify the returned fp variable which is closed over by the deferred
function.

Do not record nil feePayment in jobs map

---

internal/vsp/feepayment.go
wallet/wallet.go

This includes the following fixes for vspClient tracking:
- Schedule all fee payments for reconcile payment, regardless of fee tx status.
- Remove unvotable tickets from jobs and attempt to revoke tickets
- Catch signature errors from SignTransaction attempt
- Handle payfee error for expired fee tx from vspd.  Abandon current fee tx and then retry to make a fresh one.

vspclient: More fixes for vsp fee confirmation tracking

---

wallet/chainntfns.go
wallet/common.go
wallet/rand.go

Add a helper function to call Int63n with the prng mutex held, so
locking does not need to be performed manually in deeper wallet code.

Reorganize prng and shuffle code into rand.go

---

wallet/chainntfns.go
wallet/tickets.go
wallet/udb/addressmanager.go
wallet/wallet.go

This error is commonly seen on ticketbuyer wallets which will attempt
to revoke any missed tickets, even though an importing voting xpub
account prevents access to the private keys to do so.  This is not an
error, and should be detected up front before ever constructing the
unsigned vote/revocation.
When the private key is recorded by the wallet, but the wallet or
account is locked, the wallet will still error when failing to sign
the revocation.

Don't attempt to vote/revoke without the private key

---

wallet/udb/addressmanager.go

The documentation states this works with P2PK addresses, but it did
not because P2PK addrs were not being normalized to their P2PKH form.

Normalize addresses in HavePrivateKey

---

wallet/udb/addressmanager.go

Using the hasher mutates its state, but it was being used by the
UnlockedWithPassphrase method with the manager's read mutex held.
This adds an additional mutex for protecting just the hasher.
This fixes a data race caused when concurrently unlocking the wallet
from several goroutines, and the invalid passphrase errors that were
caused by racing on the hasher.

Protect passphrase MAC hasher with mutex

---

internal/rpc/jsonrpc/config.go
internal/rpc/jsonrpc/methods.go
rpcserver.go

Previously, the jsonrpc purchaseticket request would simply use the provided account in the request and purchase a ticket without mixing or VSP processing, no matter what the user has set in their options.  Now the options that they have set will be used.

[jsonrpc] Add mixing and VSP to purchaseticket

---

internal/rpc/rpcserver/server.go

The last returned counts are more useful as they indicate the true
number of keys derived for an account, rather than the last one that
has been marked as used.
While here, remove the hardcoded addition of 20 for the gap limit.
The gap limit is configurable so this hack was incorrect.
A later commit can add additional fields to this message to include
the last address index marked used, under a more appropriate field
name.

Use last returned key counts in grpc Accounts response

---

wallet/wallet.go

The last watched indexes were never being increased except on the very
first call to watchHDAddrs during the wallet sync.  Because this index
is used as the starting point for watching new addresses, the wallet
would increasingly watch more and more of the same addresses each
time, sending each of these in a series of 'loadtxfilter' calls to
dcrd.  This was bottlenecking block processing on long-running
heavily-used wallets which create and watch many addresses (especially
in the case of mixing ticketbuyers).
There are still some duplicate addresses being watched, but this
prevents the worst case situation of what is effectively a memory leak
of data that gets sent over the network on every new derived address.

Bump the last watched indexes of HD accounts

---

wallet/locking_test.go
wallet/mixing.go
wallet/wallet.go

This mechanism has not worked properly ever since accounts have been
able to be individually encrypted with a separate passphrase, as it
only applied to the accounts covered by the wallet's global
passphrase.  It also appears to be the cause of at best a bad UX and
at worst a deadlock whenever an unlocked mixing wallet is locked.
Probably fixes #1984.

Remove sync mechanism which held wallet unlocked

---

config.go
log.go

The logsize option enables configuration of the currently-hardcoded
value of 10MB log files before they are rotated and compressed.  The
default remains 10MB.
This is a string option and requires using a suffix such as KB, MB, or
GB to specify the units as kibibytes, mebibytes, or gibibytes.

Add logsize config option.

---

dcrwallet.go

Remove the dependency of the ticketbuyer being on. This allows
processing already bought tickets when the ticketbuyer is off.
closes #1913

dcrwallet: Set up vsp client if url provided.

---

wallet/createtx.go

A multisig transaction will sometimes need a change output. Add that
scipt size to the worst case size estimation that is used in fee
calculation.
closes #1972

createtx: Add change output to size estimation.

---

config.go

The previous default of 0 now prevents any ticketbuying from occurring
at all, due to changes with how multiple tickets bought per block are
done with separate CSPP clients and with separate UTXO sets.  Set this
to 1 so at least some ticketbuying still happens.  Increasing this
further will require users to increase the limit in their configs.

Change ticketbuyer.limit default to 1

---

chain/sync.go
spv/sync.go

This allows client users of the wallet package to disable account
discovery if the syncer is started with the wallet already unlocked.
This happens (for example) in dcrlnd, where the wallet is always unlocked 
after being opened and thus the current code for the syncers
unconditionally performs account discovery every time.

Add DisableDiscoverAccounts to syncers

---

p2p/peering.go

The error `Group` that disconnects and allows `serveUntilError` to return must be triggered by cancellation of the `gctx`, not it's parent.

p2p: trigger disconnect with group context cancellation

---

wallet/sidechains.go

When a sidechain header was previously received via a header
announcement msg but then the cfilter was fetched via a getheaders msg
with a different peer, the filter was not filled to the blocknode due to
a missing check on the duplicateNode() function to account for the root
of the sidechain forest.
This could cause issues with 1-deep reorgs due to the missing cfilter
later on when switching to the new sidechain as a best chain.
This fixes the issue by also testing the root of the sideforest for
duplicates and filling the fetched cfilter as needed.

wallet: Fix cfilter missing on 1-deep reorg

---

internal/rpc/jsonrpc/server.go

The equivalent gRPC method invocation messages are already debug logs.

Move JSON-RPC invocation logging to debug level

---

run_tests.sh

Default to 'go' to retain existing behavior.
This more easily allows to run all tests with other supported or
upcoming Go versions, e.g.
$ GO=go1.16.10 ./run_tests.sh
or
$ GO=gotip ./run_tests.sh

Parameterize run_tests.sh go executable with GO env var

---

internal/rpc/rpcserver/server.go
rpc/grpc_example/main.go
wallet/addresses.go
wallet/udb/addressmanager.go

Extract all possible data from unknown as well as known addresses. In
particular, always return the correct address type. Also allow creating
an address id for PubKeyEd25519V0 and PubKeySchnorrSecp256k1V0 types.

grpc: Return more info for ValidateAddress.

---

config.go
dcrwallet.go
internal/loader/loader.go
wallet/mixing.go
wallet/wallet.go
walletsetup.go

This allows changing the previously-hardcoded value of 10 allowed CSPP
client connections per any change downmixing amount.

Introduce mixsplitlimit config option

---

version/version.go
version/version_buildinfo.go
version/version_nobuildinfo.go

VCS build info is only available when built from a VCS checkout using
Go 1.18 or later.

version: Include VCS build info in version string

---

internal/rpc/rpcserver/server.go
rpcserver.go

Streaming calls are supposed to be client controlled and can remain
active for a long time. When their underlying context is canceled, that
is not a client or server error: it's an expected condition to mark the
end of the streaming call.
This reduces the log level of canceled streaming calls to debug.
This is implemented by detecting the underlying context.Canceled error
(or the corresponding grpc status code of Canceled), then switching the
logging function appropriately.

rpcserver: Reduce log level of canceled stream calls

---

deployments/deployments.go
wallet/chainntfns.go
wallet/createtx.go
wallet/tickets.go

This is currently being done using an extra getblockchaininfo RPC call
any time votes may need to be created.  While not ideal, and caching
of previously observed active and lockedin statuses could be utilized,
this is the bare minimum needed to make wallet follow the DCP0010 hard
fork if it is approved.

Follow DCP0010 once activated

---

go.mod
go.sum

This fixes a protocol bug which caused signature validation failures
if the client and server used different sizes of the uint type, such
as a 32-bit client connecting to a 64-bit server.

Update cspp module

---

config.go
internal/rpc/jsonrpc/methods.go
wallet/chainntfns.go
wallet/createtx.go
wallet/txrules/poolfees.go
wallet/txrules/poolfees_test.go
wallet/wallet.go

The VSP fee is a proportion of the subsidy received due to voting.
This value should change if/when DCP0010 activates so VSPs continue to
take the proper percentage of their fees.
Old stakepoold vestige code will continue to use the original subsidy
split rules.  Nobody should be purchasing stakepoold tickets anymore,
and this code should be removed when possible.

Use DCP0010 activation for VSP fee calculations

---

ticketbuyer/tb.go

Errors when purchasing tickets through the automated ticketbuyer are
already logged provided that they are not one of the various expected
errors.  However an additional log message was introduced before this
which would log these anyways, and result in other errors being logged
twice.  Remove this extra log statement.

Remove extra ticketbuying error log

---

rpc/grpc_example/main.go
wallet/addresses.go

grpc_example: Add ImportVotingAccountFromSeed example.
wallet: No taking voting addresses.
Prevent methods from getting voting account addresses. These addresses
should not be sent funds and are intended to be used only for submission
scripts and signatures.

wallet: No taking voting addresses.

---

internal/rpc/rpcserver/server.go

Now only update vote choices for the vsps that are associated with that ticket.

rpc: Only set vote vsp choices for known tickets

---

internal/rpc/jsonrpc/methods.go
internal/rpc/rpcserver/server.go
internal/vsp/feepayment.go
internal/vsp/vsp.go
wallet/wallet.go

This PR ensures tspend and treasury voting preferences are sent to VSPs. This occurs when tickets are initially purchased, or when preferences are changed via RPC.

Set tspend & treasury policies on VSP

---

.github/workflows/go.yml
README.md
go.mod
internal/rpchelp/genrpcserverhelp.go
internal/rpchelp/helpdescs_en_US.go
internal/rpchelp/methods.go
signal_unix.go
version/version_buildinfo.go
version/version_nobuildinfo.go
wallet/udb/txexample_test.go
wallet/udb/txquery_test.go
wallet/walletdb/example_test.go

Bump module version to Go 1.17.
Remove all +build directives now that the minumum supported Go version
understands //go:build.
Run 'go mod tidy' to include all indirect requirements in the go.mod
file.
Remove references to older Go versions in the README.

Updates for Go 1.18

---

internal/rpc/jsonrpc/methods.go
internal/rpc/rpcserver/server.go
wallet/wallet.go

This corrects the main logic that verifies messages to create a p2pkh address from the recovered public key instead of a p2pk since p2pkh is what is produced when signing and therefore what is required when verifying (as can be verified in dcrd as well).
This also updates the call sites that decode the addresses to properly reject p2pk addresses for the same reason.

rpc: Correct JSON-RPC and gRPC verifymessage.

---

sample-dcrwallet.conf

The config parser parses options until the end of the line, so
uncommenting a commented out config value which contains another
comment on the same line would result in parsing errors or trying to
use bogus values.

Move sample config comments to their own lines

---

chain/sync.go
internal/rpc/jsonrpc/methods.go
rpc/client/dcrd/calls.go
rpc/client/dcrd/notifications.go
wallet/tickets.go
wallet/wallet.go

dcrd's JSON-RPC version received a major version bump for the removal
of several RPCs related to querying expired and missed tickets.  With
the activation of DCP0009 and the revocations of all older unspent
tickets, these methods are no longer needed by the wallet.
The "revoked" status for getstakeinfo is no longer used, and instead,
a status of "expired" or "missed" is used (which also implies that the
ticket has been revoked).  For this subtle breaking change,
dcrwallet's JSON-RPC API version also receives a major bump.

Fix compatibility with latest development dcrd

---

spv/sync.go

This removes the SFNodeCF from the required services for nodes when
querying for nodes in the https seeder.
This service was removed from dcrd on commit
b04e2456c8dc842b285b509b8fe1e6f7f8306aa7 as part of the work to
deprecate V1 CFilters.
V1 CFilters are no longer used by dcrwallet, and the fact that nodes
no longer advertise support for this service, means the list of nodes
returned by the seeders to dcrwallet is severely limited. In particular,
for testnet as of this writing only a single (outdated) node is
returned, making it harder to sync testnet nodes.

spv: Remove SFNodeCF from required services

---

internal/rpc/jsonrpc/methods.go

When the wallet was updated to use `stdaddr` it did not account for the fact that p2pk addresses no longer automatically convert their stringized output to p2pkh addresses, so only the p2pk address ends up in the map while utxos are often p2pkh address.
As a result, the signing code attempts to look up the key based on the p2pkh address which is not in the map and errors despite the private key being provided.
This resolves the issues by additionally adding the p2pkh variant to the keys map for address that support it.

rpcserver: Allow signrawtransaction private keys.

---

internal/rpc/jsonrpc/methods.go

This is a backport of #2173 to the 1.7 release branch.

[release-v1.7] rpcserver: Allow signrawtransaction private keys.

---

chain/sync.go
spv/sync.go
wallet/chainntfns.go
wallet/checkpoints.go
wallet/sidechains.go
wallet/wallet.go

In order to follow the intended chain after the unvoted testnet3 hard
fork, we implement checkpointing and require a block from the fork to
be present in the main chain.  This is performed by rollbacking the
main chain at startup if an invalid checkpoint is detected, and
refusing to extend the main chain unless a checkpoint rule is
satisfied.  We use checkpoints to push wallet onto the intended
unvoted chain due to it having significantly less total work than the
chain being reorged.

Add checkpointing and enforce testnet3 hard fork

---

go.mod
go.sum
wallet/difficulty.go
wallet/wallet.go

This backports the testnet difficulty throttling from the difficulty
code that wallet had copied from dcrd.  This is required to avoid
consensus violations when syncing testnet3.
While here, also update to the latest version of the dcrd's blockchain
module to avoid any more surprises.

Update difficulty checks for work throttling hard fork

---

internal/prompt/prompt.go

This allows piping the answers to the --create prompts to work properly for not only the initial passphrase prompt, but the confirmation as well.  Seems to have been missed the last time this code was touched.
```
$ cat answers.txt                                                                                                                     
banana
banana
no
yes
0001020304050607080910111213141516171819202122232425262728293031
$ dcrwallet --appdata=/tmp/tmpwallet --create <answers.txt 
2022-11-09 10:41:30.988 [WRN] DCRW: open /tmp/tmpwallet/dcrwallet.conf: no such file or directory
Enter the private passphrase for your new wallet: 
Confirm passphrase: 
Do you want to add an additional layer of encryption for public data? (n/no/y/yes) [no]: Do you have an existing wallet seed you want …
```

Allow passphrase confirmation to be read from non-tty

---

internal/prompt/prompt.go

We currently require an extra blank line following the seed during creation of a restored wallet.  This is due to two factors:
* During creation of a new wallet, we print the seed in PGP word list encoding using multiple lines, and users copy and paste this as is, newlines included.  This means our prompt must support reading multiple lines of input.
* Because the seed length is not required to be exactly 32 bytes (33 words), we don't know when to stop prompting for seed words that are split across multiple lines.  An extra blank line after the seed is used to stop the prompting.
This prompting behavior is only needed for seeds encoded with the PGP word list, and not seeds encoded in hex.  If the first line of input is valid hex encoding, stop prompting immediately and do not require the …

Do not require additional newline prompting a hex seed

---

config.go
dcrwallet.go

This generates a full CPU profile output.
It also changes the memory profile to not stop after 5 minutes and instead continue until the execution ends.

dcrwallet: Add --cpuprofile option

---

p2p/peering.go
spv/sync.go
wallet/wallet.go

This fetches tspends via the p2p network in SPV mode using a `getinitstate` message and adds them to the tspends cache.

Fetch tspends in SPV mode

---

config.go
dcrwallet.go
internal/loader/loader.go
wallet/wallet.go
walletsetup.go

Very large wallets have many addresses that may not be needed anymore, but these addresses were always being loaded into the address transaction filters (cfilters in SPV mode, and given to dcrd to watch when running in full node mode).  To improve startup resource usage and performance, add a new watchlast option that counts backwards from the current address index of every HD account branch, and ignores loading addresses prior to the cutoff during the initial sync.
Future iterations on this idea may allow custom values for different accounts and branches, or perhaps something automatic for mixed accounts where we don't expect old addresses to ever be used again, but for now this seems good enough.

Add watchlast option to limit initially watched addresses

---

go.mod
go.sum

This allows a successful build for openbsd/riscv64 (using OpenBSD's patched port/package that implements the riscv64 port).

Bump golang.org/x/sys module

---

p2p/peering.go

p2p.RemotePeer.Blocks performs some internal management on requested block hashes that was continuing to execute after Blocks had returned. This caused a race to be exposed by the rescan code when running in SPV mode.
Fixes #2200.

Avoid spv data race on rescanned block hashes

---

ticketbuyer/tb.go

When the ticketbuyer.balancetomaintainabsolute flag is unset/zero,
there is no reason that the account balance needs to be calculated.
On busier wallets, avoid this results in a significant performance
improvement.
This flag is already broken for a different reason (change can land in
other accounts, causing the account balance to drop below this
setting) but there are still some people using the flag despite this,
and compensating by setting it higher than they need.

Avoid needless balance calculations from ticket autobuyer

---

wallet/rescan.go

This is only called by (*Wallet).rescan; there's no need for it to be called from outside the wallet package.

Unexport wallet SaveRescanned method

---

wallet/createtx.go

In the event that a purchase tickets request context from the ticket autobuyer is cancelled due to the changing sdiff window, addresses and outpoints must still be watched.  Not doing so eventually leads to an invalid UTXO set as relevant transactions become missed.
There is a small chance that this change may cause a hang during process shutdown.  A better solution for this is included in a comment.

Avoid context cancellation race

---

wallet/createtx.go
wallet/mixing.go

The mix with the smallest denomination never creates change; instead, the extra value is rolled into the transaction fee.  Do the same for all other mixing (ticket splitting, and the larger denominations of account mixing) so that the unmixed account is not filled with these outputs that are too small to mix, and too tempting to spend together.

Always avoid creating small mix change

---

dcrwallet.go
internal/rpc/jsonrpc/methods.go
internal/rpc/rpcserver/server.go
internal/vsp/feepayment.go
internal/vsp/vsp.go
wallet/wallet.go

The goal of this PR is to clean-up and simplify the public API of the `internal/vsp` package prior to it becoming an import from vspd. Purely refactoring with no functional changes.
I will rebase decred/vspd#382 on to this before merging it.

internal/vsp: Clean-up public API 

---

internal/vsp/feepayment.go

This removes a significant dependency from the VSP code, and it is unnecessary anyway because revocations are automatic since DCP0009.

vsp: Don't revoke tickets.

---

dcrwallet.go
p2p/peering.go

Remove the address of the local peer from the handshake.  This is to prevent leaking internal network details and if a proxy is in use. Peers are also no longer informed of their external address if the address is loopback or a private or shared address.
Backport of 18d4c023835206e455b65a71df82df8fc28255b6.

Respect proxy config for SPV and seeder connections

---

deployments/deployments.go
go.mod
go.sum
wallet/chainntfns.go
wallet/createtx.go
wallet/tickets.go

This is currently being done using an extra `getblockchaininfo` RPC call any time votes may need to be created.  While not ideal, and caching of previously observed `active` and `lockedin` statuses could be utilized, this is the bare minimum needed to make wallet follow the DCP0012 hard fork if it is approved.

Follow DCP0012 once activated

---

config.go

Revocations are no longer created by the wallet, so this option should only refer to voting.

Remove mention of revocations for --enablevoting option

---

dcrwallet.go
internal/rpc/jsonrpc/methods.go
internal/rpc/rpcserver/server.go
internal/vsp/feepayment.go
internal/vsp/vsp.go
wallet/wallet.go

The goal of this PR is to reduce dependencies between the VSP client and other wallet code.
The first 3 commits are bringing the dcrwallet client up-to-date with some changes made in decred/vspd#382.
As a result of this PR, `feepayment.go` no longer has any dependency on `decred.org/dcrwallet`, and the [interface](https://github.com/decred/vspd/blob/203bf7d2e62f0e263740b36552c33fb4689bcd60/client/autoclient.go#L39C3-L68) between dcrwallet and vspd can be reduced by 6 funcs.

vsp: Reduce dependencies on wallet packages.

---

x509_test.go

An error that could only be detected through string parsing needed to be updated for the new error message.

Fix tests to account for Go 1.21 changes

---

spv/sync.go

These logs were only really useful during development of the tspend feature and produce a large amount of noise due to logging for every transaction.

spv: Drop extraneous tspend logging for txs

---

wallet/udb/vsp.go

Remove the mismatched pubkey check from SetVSPTicket. This check is totally redundant - the VSP pubkey is checked every time a reponse is received from VSP,  so the process would have already errored out long before this condition was
ever hit.

udb: Remove redundant VSP pubkey check.

---

wallet/udb/upgrades_test.go

This test was brittle because it assumed the post-upgrade database to be exactly version 25. This has not failed so far because the assumption happens to be correct, but it will fail in future when newer DB versions are created.

udb: Make v25 upgrade test less brittle.

---

internal/rpc/jsonrpc/methods.go
internal/rpc/rpcserver/server.go
internal/vsp/feepayment.go
internal/vsp/vsp.go
ticketbuyer/tb.go
wallet/createtx.go
wallet/wallet.go

The VSP client code was not handling contexts correctly. It was receiving short-lived contexts bound to the lifespan of a single RPC request, and using them for long-lived tasks.
This change fixes that specific problem by hard-coding the VSP client code to use context.Background everywhere.
Closes #2239

multi: Hard-code background context for vsp client

---

internal/loader/loader.go
wallet/createtx.go
wallet/wallet.go

This had been previously removed from the main package's application config but was left in the wallet package to preserve API compatibility at the time.

Remove AddressReuse from wallet config

---

internal/rpc/rpcserver/server.go
internal/vsp/vsp.go
wallet/wallet.go

Move the logic to select unmanaged tickets from the wallet database up into the wallet code. No need for this to be done in the VSP client.
This also saves on database access by running ForUnspentUnexpiredTickets only once.

multi: Select unmanaged tickets outside VSP client

---

errors/errors.go
errors/errors_test.go
internal/rpc/rpcserver/server.go

It's not clear how errors.Cause should behave if it encounters an error returned
by errors.Join.

Remove errors.Cause, rely on Is/As instead

---

wallet/addresses_test.go
wallet/discovery_test.go
wallet/locking_test.go
wallet/reorg_test.go
wallet/setup_test.go

Make address_test.go use the existing testWallet func rather than unnecessarily defining a separate version named setupWallet. Also reuse some of the existing test values (public/private passphrase, cfg).

wallet: Remove duplication from testing code.

---

internal/vsp/feepayment.go

The only way to be certain a VSP has acknowledged a fee tx and added a ticket to its voting wallets is to check FeeTxStatus == "confirmed". Checking for 6 confirmations on the fee tx is not an adequate substitute.
For example, if a client has broadcast it's own fee tx rather than waiting for the VSP to do it, it's possible that the tx could be mined and have 6+ confs, but the amount paid is not enough, or the payment is sent to the wrong address.

vsp: Dont remove payments unless confirmed by VSP. 

---

internal/rpc/jsonrpc/methods.go
internal/rpc/rpcserver/server.go
wallet/udb/txquery.go
wallet/wallet.go

First commit contains a bug fix which I think was preventing all tickets from being iterated over.

multi: Always iterate over all VSP tickets.

---

wallet/rescan.go
wallet/udb/txquery.go
wallet/wallet.go

For all rescans except for the initial one when a wallet is first synced (during reseed, or after process restart), log those transactions that are changed status from unmined to mined in a block, and any newly-observed transaction that is added to the wallet.
These later rescans are typically done to fix a problem syncing blocks and/or transactions, and these transaction hashes should be useful information to discover what previously went wrong.

Log transaction changes for non-initial rescans

---

wallet/createtx.go

This context check was missing from the non-mixed purchasing path.  May improve the simnet script.

Always check context cancellation before publishing tix

---

internal/vsp/feepayment.go

Backporting various fixes for the VSP client to 1.8 release branch. Most important of these is the hard-coded background context which fixes an issue where VSP client is unable to retry failed fee payments. Without this fix, the only work-around is to re-register tickets with failed fee payments to another VSP via manual intervention. Thanks to @kandiru for help investigating and testing this.

Backport VSP client fixes to 1.8 

---

dcrwallet.go
internal/rpc/rpcserver/server.go
internal/vsp/vsp.go
wallet/wallet.go

The first two commits are bug fixes which I feel warrant review individually.
The third is simply moving some logic around following precedent set in #2257

multi: Select managed tickets outside VSP client

---

rpc/Dockerfile

This updates the docker image used to regenerate the gRPC files to use go1.21.0-bookworm as the base image which in turn uses protoc v3.21.12 and matches the latest checked in generated code.

gRPC: Update docker image for protobuf-builder.

---

wallet/chainntfns.go
wallet/createtx.go
wallet/txrules/poolfees.go
wallet/txrules/poolfees_test.go
wallet/wallet.go

Update StakePoolTicketFee so it considers whether DCP0012 is active. This is acheived by swapping the deprecated CalcStakeVoteSubsidyV2 for its replacement CalcStakeVoteSubsidyV3.
Extra test cases are added to validate that the dcp0010Active and dcp0012Active flags work as expected.

txrules: Consider DCP0012 in VSP fee calculations.

---

rpc/documentation/clientusage.md
rpc/grpc_example/main.go
rpc/rpc_example/main.go

os.ReadFile is a direct replacement for ioutil.Readfile.

rpc: Don't use deprecated ioutil.

---

go.mod
go.sum

This release includes a fix avoiding syscall(2) on OpenBSD (which is being
removed).

Update bbolt to 1.3.8 

---

wallet/difficulty.go
wallet/udb/txmined.go

This commit improves initial chain sync performance by switching the calcNextBlake256Diff function to traverse the chain by height instead of following the header hashes.
calcNextBlake256Diff is used to calculate the difficulty required for block headers before DCP0011 is activated (which at this point in time is the majority of the chain). This requires traversing the chain backwards, down to the block prior to each work difficulty window change.
Previously this was done by following the header chain backwards. This involved loading and decoding each header in sequence, in order to extract the previous block hash, until each relevant block is reached.
This is a significant component of the cpu and memory loads for the initial chain sync of the wallet.
This commit improves this process by …

wallet: Traverse by height in calcNextBlake256Diff

---

p2p/peering.go
spv/sync.go
wallet/chainntfns.go
wallet/udb/stakevalidation_test.go
wallet/udb/txmined.go

This PR makes some changes to the wallet, spv syncing and peer packages to avoid having to hash the exact same header multiple times.
This improves both cpu and memory allocation performance during the initial sync process.
On an informal sync on mainnet using spvconnect, this reduces the space allocated by `BlockHash()` calls by ~60% and the time spent in these functions by ~72%.

wallet: Avoid multiple BlockHash() calculations

---

wallet/difficulty.go

This makes the branch that handles the error for
checkDifficultyPositional() return the invalid chain in validateHeaderChainDifficulties.
Previously this branch failed to fulfill the contract of the function.

wallet: Make validateHeaderChainDifficulties fulfill contract

---

internal/rpc/jsonrpc/methods.go
wallet/wallet.go

If the raw transaction provided by the caller contains invalid signatures, set complete=false to indicate that the transaction is not ready to send.
This situation (where the user has manually modified the transaction after a previous redeemmultisigout call, which may add some of the required signatures) is unfortunate and there are possibly better ways we could deal with this, such as removing the invalid signature, or returning a more descriptive error for the failed script evaluation.
Refs #2273

Set complete=false in redeemmultisigout on invalid sigs

---

internal/loggers/loggers.go
log.go
spv/sync.go

This moves the header chain difficulty validation to an earlier point in time of the initial sync process.
This is preferable so that less work is performed in case invalid headers are received.
This PR includes a commit to move the p2p package logs to a separate subsystem, so that the syncing process can be logged with a higher logging level while not producing significant log spam due to individually logging each peer message.
Part of #2289

spv: Move validate header chain difficulties to earlier point in startup sync

---

spv/backend.go
spv/sync.go

This moves the "fetching missing cfilters" stage of syncing from individual peer startup to the syncer startup.
This reduces the overall load by ensuring this stage is only done once instead of being done for each new peer.
Future PRs will continue the process of moving syncing stages from the per-peer `startupSync()` function to the global syncer `Run()` function, removing duplicate work that is currently done by the wallet.

spv: Move FetchMissingCFilter step to syncer startup

---

p2p/peering.go
spv/sync.go

This disconnects SPV peers ealier in the peer startup sequence, before they are added to the `remotes` map. This improves the SPV loop by ensuring peers that are too much behind the wallet's tip are _not_ given a chance of being selected for any operations and a new peer connection is attempted.
It also adds tracking of the last returned header per peer, which will be useful in future refactorings.

spv: Drop unsynced peers earlier

---

p2p/peering.go
spv/backend.go
spv/sync.go

This moves the fetch headers and cfilters stage from the per-peer startup function to the main syncer startup function.
This avoids wasting duplicate effort for every peer. In the future, this will allow using multiple peers to fetch headers and cfilters from, as well as allowing asynchronous fetching.
This change significantly reduces the amount of resources (cpu, ram, goroutines) used during the initial sync at the cost of increasing the sync time. The sync time will be reduced in the future as well, after parallelizing the headers/cfilters/chainswitch stages and after [batched cfilter fetching](https://github.com/decred/dcrd/pull/3211) is implemented and deployed.
Part of #2289

spv: Move getheaders stage to global syncer instead of per-peer

---

spv/backend.go
spv/sync.go
wallet/network.go
wallet/network_test.go

This moves the initial account and address discovery and rescan from the per-peer startup procedure to the global syncer startup sync procedure.
This makes the code easier to reason about and removes the need for the atomic lock to the discoverAccounts field.
The previous code would execute a rescan after every connected peer, if it had any new headers that connected to the main chain.  With the changes in this commit, the syncer now only performs the full rescan once at startup and relies on the header announcement logic to scan when new blocks are relayed from peers after the initial sync.
It also finishes switching all backend functions in SPV to use `waitForRemotes` and removes unneeded functions.
Part of #2289

Move initial rescan to global syncer loop

---

chain/sync.go
spv/sync.go
wallet/wallet.go

This makes the wallet BlockLocators function return the height of the first (i.e. most recent) block locator.
This makes checking if the peer failed to provide headers independent of the state of the db.
While this makes no functional difference at the moment, in the future, when fetching headers and updating the db from different goroutines, this makes it easier to reason that the check is being done correctly.

spv: Track requested block locator height

---

p2p/peering.go
spv/backend.go
spv/sync.go

This refactors the initial cfilter fetching to be based around requesting smaller batches of cfilters from the lower p2p level.
While this does not make any functional difference at the moment, in the future, when a P2P protocol with batched CFilter is supported (https://github.com/decred/dcrd/pull/3211 or equivalent), it will be trivial to switch to using it for remote peers that support it.
Additionally, this reduces the total number of goroutines used for the underlying `CFiltersV2()` call from the p2p package, which is useful in slightly reducing the total cpu and memory loads during initial sync.

spv: Refactor initial cfilter fetching to be done in smaller batches

---

spv/backend.go
spv/sync.go
wallet/sidechains.go

This modifies the cfilter fetching stage of the initial sync process to request cfilters from multiple peers instead of a single one.
This spreads the load across multiple peers, making the initial sync process (on average) slightly faster due to lower remote peer resource usage.

spv: Fetch cfilters from multiple remote peers

---

wallet/chainntfns.go
wallet/sidechains.go
wallet/sidechains_test.go

This modifies the pruning procedure of the sidechain forest to prune not just entire trees, but instead to prune partial chains from trees.
This enables the ability to maintain headers in the forest for which its ancestor chain has been included in the wallet's main chain, while the successor chain has not yet been fully processed (for example, due to missing cfilters).
While this does not make a functional difference at the moment, in the future this will allow the SPV syncer to process chains asynchronously.

wallet: Prune chain instead of rooted tree

---

chain/sync.go
rpc/client/dcrd/calls.go

Previously, request for notifications about connected blocks were sent to the underlying dcrd instance before the chain was fully synced.  This could cause a race issue if the underlying dcrd instance was also performing an initial sync, causing blocks to be connected by the blockConnected handler before the active data filter was loaded, causing transactions to be missed and the wallet's balance to be wrong, requiring a rescan to be fixed.
This could happen, for example, if both the dcrd and dcrwallet processes were started at the same time or if dcrd took just enough time to connect to the network that the wallet was also initialized (for exemple, from within Decrediton).
This fixes the issue by refactoring the initial sync code to only request block notifications after the initial …

chain: Request block ntfns only after initial sync

---

internal/rpc/rpcserver/log.go

A typing error was preventing stripGrpcPrefixArgs from working as intended. Before, the type check for args[0] to be a string type would always fail, and no prefix stripping occurred.
Fixes #2169.

Fix grpc log prefix stripping

---

chain/sync.go
internal/rpc/jsonrpc/server.go
internal/rpc/rpcserver/server.go
p2p/peering.go
spv/sync.go
wallet/wallet.go

These types prevent atomic misuse by only allowing access through the provided methods and guarantee proper alignment even if the variables are moved in the struct layout.

Use Go 1.19 atomic types

---

spv/backend.go
spv/sync.go

This switches the initial SPV header fetching process to process each batch of headers in parallel through its various stages.
The initial header sync process is split into a 3-stage pipeline, where batches of headers progress through. Each stage is run on a separate goroutine, providing some parallelism for the entire process.
The following is a rough comparison of sync times with/without this PR (all on mainnet, [reference master](https://github.com/decred/dcrwallet/commit/9873543d9880637f22978cfc47f83bf100f8d456)):
```
master
[DBG] SYNC: Initial sync completed in 13m3s
[DBG] SYNC: Initial sync completed in 13m2s
[DBG] SYNC: Initial sync completed in 13m34s
master, spvconnect to a known fast peer
[DBG] SYNC: Initial sync completed in 7m42s
[DBG] SYNC: Initial sync completed in 7m4s …
```

spv: Process header batches in parallel

---

chain/sync.go

This adds a check for the presence of the parent block on a known sidechain prior to re-requesting all headers on announced blocks during RPC chain sync
Prior to this commit, the parent block was checked for presence only on the main chain, which could cause getHeaders to be repeatedly executed on reorgs of size greater than one.
This was mostly an issue for automated tests that generate large reorgs.

chain: Avoid early getHeaders on sidechains

---

spv/sync.go

This modifies the peer setup procedure to request any updated headers from a newly connected peer if the connection is made after the initial sync is completed.
This speeds up re-syncing after initial sync when the local client has been offline for some time (for example, due to a flicking network connection) by ensuring any and all updated headers are requested immediately, instead of waiting until a new block is announced to begin the catchup process.

spv: Request headers from peer after initial sync

---

wallet/discovery.go

This fixes an off-by-one in sizing the backing array for cfilter data during address discovery.
During address discovery, the GetMainChainCFilters call to fetch cfilters from the DB uses an array sized by the caller to put the data. However, due to being an inclusive fetch, the call in the address finder is not correctly sized, missing one (i.e. the last) block.
This could cause an issue when the wallet had a single address used and that address was used on a transaction on the wallet's tip, causing the wallet to miss that address being used.
Required by #2318.
This was uncovered while debugging [this test](https://github.com/decred/dcrwallet/pull/2318/files#diff-0acd0b60cd995be3ef8f885d942a9fd509ffd3375f3486a31a29d3e1846843a9R183-R200)

wallet: Fix off-by-one in addr discovery

---

p2p/peering.go

If the height or required services is deemed insufficient after the connection handshake, do not request more addresses right away, waiting for its response before killing the TCP connection.  This stops ConnectOutbound from returning early with error while the TCP connection is still active, and causing the SPV syncer to begin connecting to more remote peers.  While the SPV syncer remains limited to 8 total outbound managed peers, the total count of TCP connections can easily exceed this, and has been observed to max out the circuit limit on Tor proxies.

Request more p2p addrs after peer checks

---

p2p/peering.go

The reject message is deprecated, and has also been removed from the most recent protocol version entirely.
Although the reject could be sent after a check of the negotiated pver, there's no value to sending a reject to a peer for bad advertised services. No message was ever rejected from being received by the remote peer.

Do not send reject messages for bad services

---

wallet/wallet.go

This check could prevent a wallet from going through address discovery if it had not completed the initial chain sync prior to being restarted.
One instance this could happen is when restoring SPV wallets under an instable network connection or having a power loss during the initial sync of a restored wallet.
Detected while debugging issues with #2318.

wallet: Remove mainchain tip check on NeedsAccountsSync

---

walletsetup.go

This removes the enforced coin type upgrade for simnet wallets, in order to allow testing the upgrade code path under simnet.
Prior to this commit, the coin type of a restored simnet wallet was always upgraded to the corresponding SLIP0044 coin type, in order to ensure that the address meant to be used as the mining address for the dcrd node was never made invalid. However, despite this enforced upgrade, there is still a bug with account and address discovery if the wallet was started before at least blocks 1 and 2 were mined in the underlying full node.
To alert simnet users about this bug this commit adds a note displayed during simnet wallet creation.
In the future, this bug may be fully fixed by ensuring the underlying node is fully synced and has blocks before the sync process …

wallet: Allow coin type upgrades on simnet 

---

.github/workflows/go.yml
README.md

Suggest using and test against Go 1.21 and 1.22.

Drop Go 1.20 support

---

p2p/peering.go

This is a backport of 92b6b88ab6f858eccd2627263c475e54b68d7f21.

[release-v1.8] p2p: update the required minimum protocol version

---

p2p/peering.go

Backport of b6295695062320f960bedc89c3f4a399ed6ceb03.

[release-v1.8] p2p: do not retry failed outbound connections

---

wallet/createtx.go

Not only would these not be valid, but the split tx has not been published either.

Do not attempt publish of unsigned ticket purchases

---

chain/sync.go
config.go
dcrwallet.go
sample-dcrwallet.conf
wallet/network.go

This prevents the wallet from syncing from blockConnected messages when it is connected to a dcrd instance that is not yet as synced as the one the wallet has used in the past. This improves performance by batching the sync work in the initial getHeaders stage and prevents wallet misuse by ensuring the underlying dcrd is also synced to recent blocks.
Note that the the case of a new wallet (with recorded tip height 0) connected to a network isolated dcrd instance (header and block height both 0) is explicitly allowed to proceed without waiting. This handles the use-cases of airgapped and empty simnet wallets.

chain: Wait for dcrd to sync before starting RPC sync

---

lru/map.go

Map is like Cache but records both a key and a value.
A new Get method is added to receive the value for a key, if present.  When found, the item is moved to the front of the most-recently-used list.  Another method Hit is similar, marking the item (if any) as the most recently used, but discards the value.

lru: Implement Map type

---

internal/rpc/jsonrpc/methods.go
internal/rpc/rpcserver/server.go
internal/vsp/feepayment.go
internal/vsp/vsp.go
wallet/createtx.go
wallet/vspticket.go
wallet/wallet.go

Upon creation, the new VSPTicket struct is initialized with all of the values necessary to register a ticket with a VSP. It is then passed into the VSP client. This helps to ensure no invalid tickets are added to a VSP client, thus removing a bunch of error handling from `vsp.go` and `feepayment.go`. It also reduces database access because values such as the raw transactions are retrieved once and then held in the VSPTicket struct to be reused.
As a result of this PR, a lot of duplicated logic and complexity are removed from `vsp.go` and `feepayment.go`. A lot of logic specific to VSP tickets is removed from `wallet.go` and into `vspticket.go`.
This is quite a big diff, but it is mostly just moving code around and refactoring without changing semantics. I have made the changes in a series …

vsp: Encapsulate VSP ticket logic in new VSPTicket struct

---

config.go
dcrwallet.go
p2p/peering.go
sample-dcrwallet.conf

This setting allows the wallet to not sync mempool transactions when in SPV mode. This is useful to reduce cpu, memory and bandwidth consumption for wallets that see very few useful mempool transactions, such as wallets meant for only occasional use or mobile wallets.
The setting is exposed as a CLI or config argument --spvdisablerelaytx.
Related: https://github.com/decred/dcrd/issues/3234

multi: Expose disablerelaytx

---

chain/sync.go

#2340 added additional sync conditions to startup, one of which is that `InitialBlockDownload` from `getblockchaininfo` must be `true`. A condition for `InitialBlockDownload` to be true is that the best header cannot be older than 24 hours.
In dcrdex, we use a simnet harness that starts with an archived chain with about 600 blocks. Building the chain from scratch takes substantial time, and we can't e.g. mine one block to get a fresh header, because the wallets can't vote. 
This change forego's the check of `InitialBlockDownload` on test networks, leaving in place the condition `info.Blocks >= minHeight`.

rpc: allow syncing older tips on test networks

---

go.sum
p2p/peering.go
spv/backend.go

Requires https://github.com/decred/dcrd/pull/3211
Part of #2289
Draft for the time being, until the upstream requirement is merged, but should be close to the final format.
When the remote peer supports batched cfilter fetching, use that. This allows mixing both peers that support with peers that do not support batched fetching when downloading cfilters, making this useful even while the network is not fully updated.
```
spv connect with known remote fast node
[DBG] SYNC: Initial sync completed in 3m5s 
```

spv: Add batched cfilter fetching

---

config.go
testsolver.go

There was some confusion over the `csppsolver` option that resulted in it being set as if it were a boolean option.  This caused a properly built and working csppsolver to not be used, and instead, the solverrpc package attempted look up and exec a file named "1".  Adding the error message would have removed some confusion as this was debugged.

Improve error message for initial csppsolver check

---

chain/sync.go

If syncing over JSON-RPC is being reattempted in a loop, as the main package does, not waiting for the errgroup that runs the wallet's mixing client may cause it to concurrently enter mixclient.Client.Run again before it has returned.  This eventually results in a panic due to closing the already-closed warming chan.
This is a backport candidate for 2.0.1.

chain: Wait for errgroup before returning from sync

---

chain/sync.go
go.mod
go.sum
rpc/client/dcrd/calls.go

This changes the notification handler when a run-0 KE is received but the sender's own PR is not yet known to request the PR from dcrd.
Because this also works to initially sync the mixpool during the warming period, the previous call to getmixpairrequests is no longer necessary and has been removed.

chain: Fetch unknown PRs of notified orphan KEs

---

p2p/peering.go

Similar to a recent dcrd change, we want published inventory by SPV wallet peers be submitted with a small random amount of delay.  In this change we use the same logic that dcrd now uses to pick, for each connected peer, a random delay between 100-500ms before the inventory is sent.

Add 100-500ms of per-peer inventory delay

---

spv/sync.go

This fixes an issue where SPV wallets would only request blocks from peers after a new block was mined.
The issue could be triggered if the number of peers ever dropped to zero, causing the SPV syncer to consider itself unsynced, and if blocks were mined in the intervening period until a new peer was connected.
The root cause was the addition of the unsynced status on the refactoring made in commit 6cde2cc7. That made the sync status atomic decoupled to the state of the initialSyncDone signalling channel, which meant that if the atomic was switched to zero after the initial sync was done, new headers would fail to be requested from newly connected peers.
Upon further review, the check is ultimately unnecessary and is removed in this commit ensuring that, after initial sync is completed, …

spv: Fix request of new blocks after initial sync

---

spv/sync.go

This fixes an issue where SPV wallets would only request blocks from peers after a new block was mined.
The issue could be triggered if the number of peers ever dropped to zero, causing the SPV syncer to consider itself unsynced, and if blocks were mined in the intervening period until a new peer was connected.
The root cause was the addition of the unsynced status on the refactoring made in commit 6cde2cc. That made the sync status atomic decoupled to the state of the initialSyncDone signalling channel, which meant that if the atomic was switched to zero after the initial sync was done, new headers would fail to be requested from newly connected peers.
Upon further review, the check is ultimately unnecessary and is removed in this commit ensuring that, after initial sync is completed, …

[release-v2.0] spv: Fix request of new blocks after initial sync

---

vsp/vsp.go

Previously was checking if fp == nil and then attempting to access fp.

vsp: Prevent nil pointer dereference.

---

go.mod
go.sum
vsp/feepayment.go
vsp/vsp.go

types/v3 removes the deprecated "revoked" field from /vspinfo response (not used by dcrwallet).

Update to latest vspd modules.

---

wallet/udb/stake.go
wallet/udb/stakedb.go
wallet/udb/upgrades.go

Removes some redundant code (including a panic).

Remove unnecessary DBVersion param. 

---

internal/rpc/jsonrpc/methods.go
wallet/chainntfns.go
wallet/notifications.go
wallet/udb/addressdb.go
wallet/udb/addressmanager.go
wallet/udb/txdb.go
wallet/udb/txquery.go
wallet/udb/vsp.go
wallet/vspticket.go

Nits noticed by IDE whilst working on other things.

Misc refactoring and tidying.

---

config.go

Ticket buyer options were moved to the main config file 8 years ago by 32b6ca9528b202059e81bcd6b6c527acce7c5270, it's reasonable to assume this warning is no longer necessary.

config: Remove old ticket buyer conf warning.

---

internal/rpc/rpcserver/server.go

Preparing for some up-coming breaking changes.

rpcserver: Bump gRPC major version to 8.

---

internal/rpc/jsonrpc/methods.go

This fixes a bug where the change from a ticket purchase was always sent back to the purchasing account, regardless of whether mixing is enabled and a different change account has been configured.

jsonrpc: Use correct change account when mixing.

---

dcrwallet.go
internal/rpc/rpcserver/server.go
ticketbuyer/tb.go

Ticket buyer config is only set once at creation and then not accessed again from externally, so there is no need for an AccessConfig func, it can just be passed into New.

Add cfg to ticketbuyer.New.

---

rpc/Dockerfile

- Pull base image by digest, helping to avoid supply chain attacks.
- Use alpine base image instead of debian (245MB vs 837MB).
- Update from golang 1.21.0 to 1.23.1.
- Download specific version of protobuf from GitHub rather than whatever version happens to be provided by the base images package manager.
Prior to this PR the Dockerfile did not work at all and the version of protobuf provided by Debian's package manager was v21.12. For context, the most recent pb files in the repo were built with version v27.3.

rpc: Refresh Docker for generating protobuf files.

---

ticketbuyer/tb.go

If the call to RescanPoint fails the ticketbuyer should not be terminated forever, it can continue running and subsequent calls to RescanPoint may succeed. This is how all other errors in the ticketbuyer are handled (with the exception of incorrect passphrase error).

ticketbuyer: Dont terminate if RescanPoint fails.

---

debug.go

Removes the following compatibility flags when building the "go 1.22" module with Go 1.23:
```
build	DefaultGODEBUG=asynctimerchan=1,gotypesalias=0,httpservecontentkeepheaders=1,tls3des=1,tlskyber=0,x509keypairleaf=0,x509negativeserial=1
```

Use Go 1.23 default GODEBUG

---

wallet/createtx.go

This was accidentally changed during the move to peer-to-peer mixing.
I believe this is all that is necessary to close #2420.

Use correct account for mixed ticket split txns.

---

wallet/createtx.go
wallet/wallet.go

The comments suggested that this was the intended behavior, but the voting account option was only being considered when UseVotingAccount (allowing the option to be used in non-mixing situations) was true, and mixed ticketbuying was not setting this value.

Always use configured voting account when mixing

---

dcrwallet.go
internal/rpc/jsonrpc/methods.go
internal/rpc/rpcserver/server.go
ticketbuyer/tb.go
wallet/createtx.go
wallet/feepayment.go
wallet/vsp.go
wallet/vspclientloader.go
wallet/wallet.go

Moving this code should have minimal impact on consumers of the vsp package because they will have been importing the wallet package already due to the fact that a VSP client could not be created without an instance of wallet.
The benefits of this are:
- vsp client creation now exists only in the wallet package, rather than being scattered across 3 packages.
- vsp client loading funcs and variables are no longer package global.
- simplifies the creation of a vsp client because the wallet no longer needs to be passed into the func as a param.
- no longer necessary to abstract the vsp client away by referring to its methods, the client can just be used directly.
Can be squashed before merging.

Move VSP client code to wallet package

---

dcrwallet.go
internal/loader/loader.go
internal/rpc/jsonrpc/methods.go
internal/rpc/rpcserver/server.go
ticketbuyer/tb.go
wallet/createtx.go
wallet/feepayment.go
wallet/vsp.go
wallet/vspclientloader.go
wallet/wallet.go
walletsetup.go

Ensure dialer is set correctly so VSPs are reached over tor if requested in config. This also has a nice side-effect of simplifying VSP client creation.
Based on #2428

Make VSP clients respect tor config

---

internal/rpc/rpcserver/server.go
wallet/vsp.go

Removing a lot of duplication and boilerplate. Will squash before merge.

Tidy up creation of VSP clients.

---

chain/backend.go
chain/sync.go
spv/backend.go
spv/sync.go
ticketbuyer/tb.go
wallet/mixing.go
wallet/network.go
wallet/network_test.go
wallet/wallet.go

Any long-lived process (such as mixing) must return if the network backend (e.g. the dcrd RPC connection) is disconnected or the syncer encounters another error.  However, it was observed that mixclient calls were continuing to execute despite the syncer erroring, resulting in locked outputs that could not be mixed after the syncer reconnected and restarted.
To avoid this, the network backend interface gains additional methods to select on when disconnect occurs, and a new context wrapping function is added, which creates a derived context that is canceled (or "done") after the syncer exits.  Wrapped contexts are added in the ticket purchasing and account mixing paths, including those being performed by the autobuyer.

Add context wrapping for syncer disconnections

---

internal/rpc/jsonrpc/methods.go
wallet/wallet.go

This changes the call sites of VSP library functions to fill in missing policy choices with empty maps instead of nil maps.
This fixes an issue where certain VSPs will fail to accept the policy calls because those fields are required by the API but not sent.
Fix #2402

multi: Send empty VSP policy fields

---

spv/backend.go

If initial sync takes longer than six blocks and peers have not changed, sync will hand at ninety-nine percent unable to get cfilters for the last few blocks. Also accept cfilters from a peer that gave us headers at or above the desired height in this case.
closes  #2444

spv: Accept cfilters from more peers.

---

chain/sync.go

TLS 1.2 is already the required minimum TLS version, which does not support any insecure curves.
Additionally, setting the curve preferences disables the X25519MLKEM768 key exchange, which would otherwise be used by default beginning in Go 2.24.

Do not specify TLS curve preferences

---

go.mod
go.sum
internal/rpc/jsonrpc/methods.go

Changing nil to empty map is handled in VSP client v4.0.1 so this behaviour is no longer required in dcrwallet.
Ref #2438

jsonrpc: Let client handle empty VSP policy fields

---

.github/workflows/go.yml
README.md
debug.go
go.mod

This bumps the Go version required by the v5 module (which has not yet been tagged) to the previous Go 1.23 release.
The default GODEBUG flags when building with Go 1.24 have been changed to the 1.24 default values.

Add updates for Go 1.24.

---

wallet/setup_test.go
wallet/udb/txcommon_test.go

These test directories are always unique per test and will be cleaned up automatically after the test ends.

Use testing.T.TempDir() for temporary test directories

---

internal/rpc/jsonrpc/methods.go

Previously, only the JSON-RPC API version would be included or added.
The application version, in addition to API version, is already returned by dcrd.

Add dcrwallet version to version JSON-RPC result

---

dcrwallet.go
spv/sync.go

Recreate a new syncer in the SPV reconnect loop in main.  This will allow
initial sync logic to be reperformed if peers can be connected later.
This also adds a forced 5s backoff before peers connection attempts are made
again, matching the backoff behavior for RPC syncing.
Rebased over #2463.

spv: Teardown syncer after all peers are lost 

---

spv/sync.go

Backoff for discovered peers begins at 5s and adds an exponentially-decaying
increase before maxing out at 90s.  Persistent peers use a smaller scaled
backoff curve starting at 1s and maxing out at 18s.
All backoffs include a small amount of random jitter to avoid reconnection
storms at syncer startup.
Backoffs are reset if network connection is established to the peer.
Fixes #2464.

spv: Implement per-peer increasing backoffs

---

chain/sync.go

The ordered shutdown of wallet goroutines before closing the websocket connection introduced a new bug where the RPC syncer would hang if the dcrd connection is lost before clean shutdown is signaled, due to a missing call to cancel the context passed to Wallet.Run.

Prevent hang when dcrd connection is lost

---

internal/rpc/jsonrpc/methods.go

This produces a nicer and more understandable error then "account not found" as it would have previously failed while looking up the unconfigured mixing accounts.

jsonrpc: Error early from mixoutput if mixing is not enabled

---

wallet/discovery.go

Since we have already checked err before and returned != nil, err must be nil here. In fact, it should return `r.err`.

fix: fix incorrect nil return value

---

wallet/udb/upgrades_test.go

`TempDir()` is a method introduced in Go 1.15 for `testing.T`. It automatically creates a temporary directory and cleans it up after the test is complete, eliminating the hassle of manually handling errors and cleanup.  More detail about TempDir  https://pkg.go.dev/testing#B.TempDir

refactor: use t.TempDir() instead of os.MkdirTemp

---

dcrwallet.go
internal/rpc/jsonrpc/server.go
rpcserver.go

This ensures that the context of in-flight RPC requests is cancelled when the dcrwallet process context is cancelled.

jsonrpc: Use process ctx as request ctx parent.

---

dcrwallet.go
internal/loader/loader.go
internal/rpc/jsonrpc/config.go
internal/rpc/jsonrpc/methods.go
internal/rpc/rpcserver/server.go
rpcserver.go
wallet/wallet.go
walletsetup.go

A hard-coded value for VSP max fee should not be used when a value is available from config.

Don't use hard-coded VSP MaxFee.

---

config.go
dcrwallet.go
internal/loader/loader.go
internal/rpc/jsonrpc/config.go
internal/rpc/jsonrpc/methods.go
rpcserver.go
wallet/chainntfns.go
wallet/mixing.go
wallet/setup_test.go
wallet/wallet.go
walletsetup.go

Loader was using a flag to disable mixing whereas the rest of the code was using a flag to enable it. Standardizing on one removes the need to invert back and forth.

Standardize on "mixingEnabled" and explain --mixing config more thoroughly.

---

dcrwallet.go
internal/rpc/jsonrpc/methods.go
internal/rpc/rpcserver/server.go
ticketbuyer/tb.go
wallet/createtx.go
wallet/wallet.go

This is a breaking API change that removes the error-prone UseVotingAccount
field from the purchase tickets request configuration.  Users of this API must
instead explicitly specify this field (or the default account 0 will be used
instead).
Rebased over #2482.  The previous commit can be backported if needed, while this is a breaking API change for v5.

Require an explicit voting account.

---

kdf/kdf.go
p2p/peering.go
spv/sync.go
wallet/discovery.go
wallet/feepayment.go
wallet/mixing.go

In Go 1.21, the standard library includes built-in [max/min](https://pkg.go.dev/builtin@go1.21.0#max) function, which can greatly simplify the code.

refactor: use the built-in max/min to simplify the code

---

internal/prompt/prompt.go

There is a [new function](https://pkg.go.dev/slices@go1.21.0#Contains) added in the go1.21 standard library, which can make the code more concise and easy to read.

refactor: use slices.Contains to simplify code

---

wallet/wallet.go

When an extra output is required to be created to pay the VSP during UTXO
contention, the estimated fee tx size included an unnecessary change output
and a buffer of 2x the estimated network fee.  However, this would create
change outputs small enough to be considered dust, causing the additional
value to be rolled into the network transaction fee instead, causing a roughly
3x network fee overpayment for these VSP fee transactions.
Fix this by removing the unnecessary change output from the size calculation
and do not add more than 1x the estimated network fee for the 1:1 VSP fee
transaction.

Prevent VSP fee rate overpayment

---

spv/sync.go
wallet/vspclientloader.go

There is a [new function](https://pkg.go.dev/maps@go1.21.1#Clone) added in the go1.21 standard library, which can make the code more concise and easy to read.

refactor: use maps.Clone to simplify code

---

internal/rpc/jsonrpc/methods.go

There is a [new function](https://pkg.go.dev/slices#Sort) added in the go1.21 standard library, which can make the code more concise and easy to read.

refactor: replace sort.Slice with slices.Sort for natural ordering

---

wallet/feepayment.go

The fp variable is never nil by the time the defer runs so the nil check can be removed.
If this method is called concurrently with the same ticket hash, the newly created fp variable is never scheduled, so it doesn't need to be stopped.

Remove unnecessary code from feePayment

---

wallet/chainntfns.go
wallet/udb/vsp.go
wallet/udb/vsp_test.go
wallet/vsp.go
wallet/vspticket.go

~If a ticket becomes unmined because of a fork it should be removed from any VSP clients the wallet has configured.~
**See comment below for corrected description**

Remove pruned unmined tickets from vsp client and DB.

---

wallet/chainntfns.go

A database update transaction is already opened here, and attempting to open another one will deadlock the wallet while processing new blocks.
While here, also simplify the removal logic to skip an unnecessary read and serialization of the DB's VSP ticket.

Prevent deadlock removing pruned VSP tickets from DB

---

chain/sync.go
spv/backend.go
spv/sync.go
wallet/chainntfns.go
wallet/checkpoints.go
wallet/reorg_test.go
wallet/sidechains.go
wallet/udb/tx_test.go
wallet/udb/txmined.go

There is a longstanding bug that causes the wallet to lose transactions if they appear in a mined block, that block is reorged out, and a later reorg reinstates the original block back in the best main chain.  This occurs due to how relevant transactions are passed around during reorgs.  Each syncer is responsible for providing the relevant transactions during the call to ChainSwitch, but the syncers are not aware of the transactions that are rolled back from previous reorgs.
Rather than passing in relevant transactions from the syncer, record these transactions in each block node in the sidechain forest.  During a reorg, save the removed transactions along with each block node when saving the sidechains.
Requires #2526.
Fixes #1740.

Fix reorg transaction loss

---

go.mod
go.sum

This update fixes a busy loop that would occur when a session was formed by only inactive peers.

Update to latest mixing module

---

dcrwallet.go
internal/rpc/rpcserver/server.go
rpcserver.go

After discussions in #2518 I took a closer look at how RPC services are initialized. This is a first step towards improving consistency between services.
<del>The races described in #2518 are not addressed by this PR.</del>
The races described in #2518 are addressed by the last commit in this PR.

Initialize RPC services more consistently
