decred/dcrwallet

wallet/createtx.go

The byte size of inputs and outputs was changed to reflect the current
serialization sizes of Decred transactions. The size of the transaction
is also now more generously estimated in case a large amount of inputs
are required.

Corrected fee estimation for general transactions

---

rpcserver.go

The listscripts RPC command has been added, allowing a user to dump
the redeem scripts contained by their wallet. The dumped redeem scripts
also include the 20-byte HASH160 script hash and the script hash
address.

Add listscripts RPC command handling

---

README.md

Update releases link in README.md for the decred-release repository.

README.md: Update URL to releases

---

rpc/legacyrpc/methods.go
wtxmgr/query.go

TicketsForAddress used to return tickets that existed in the wstakemgr
database but which were pruned in the wtxmgr database. This update
also checks the ticket hashes against the wtxmgr database in case they
have been pruned and removes pruned tickets from the response.

Correct TicketsForAddress returning pruned tickets

---

internal/prompt/prompt.go

This commit allows you to have extra spaces when inputting a wallet seed during create.
This means you can paste the seed shown during a previous create in as is with the
newlines intact.
Closes #29

Allow newlines and extra spaces when entering seed.

---

wtxmgr/tx.go

Only access isClosed inside the mutex in wtxmgr.

---

wallet/wallet.go

Switch from log.Debug to log.Debugf.

---

wallet/createtx.go

0-value outputs are unspendable in Decred. The current implementation of wallet
allows you to generate a new address for an unspendable output when creating
tickets. Now these outputs are given random addresses so they do not
incorrectly incrememnt the address pool.

Use a random address for 0-value outputs

---

wtxmgr/unconfirmed.go

Add err check for unchecked

---

wallet/addresspool.go

Could cause address desyncing and address reuse

Change initilialize to use proper index (extIdx)

---

wallet/createtx.go

A bug existed that could cause the unusual locking up of the wallet
when requesting a transaction, such as through sendtoaddress. The
new function MakeInputSource opens a database transaction, but when
the address pool runs out of addresses it also attempts to open a
database transaction through waddrmgr.NextInternalAddresses. This
would cause a gridlock. To fix this, the address is pulled before
the database transaction is opened and then committed to later if
the transaction succeeds and includes the change address.

Fix a bug causes wallet lockup when making transactions

---

rpc/legacyrpc/methods.go

Add .ToCoin() to GetWalletFee return val to be consistent

---

dcrwallet.go

Clean UX so it is more clear that a pass is required

---

rpc/walletrpc/api.pb.go

Fixes build when using newer versions of the grpc packages.

Regenerate walletrpc package.

---

internal/rpchelp/helpdescs_en_US.go

Update help comments to show fee per kb instead of increment

---

dcrwallet.go
wallet/loader.go
walletsetup.go

Avoid stdin passphrase prompt with --noinitialload.

---

chain/chain.go

Fix lockup relating to channel blocking

---

wallet/chainntfns.go
wallet/createtx.go

PurchaseTicket returned an incorrect generic error when sendrawtransaction
failed. This has been replaced with the actual error.

Make purchaseticket return the correct error

---

glide.lock

Update to pull in update dcrrpcclient commit

Update glide locks

---

config.go

Disable ticket purchase by default in preparation for
dcrticketbuyer.

Disable ticket purchase by default

---

cmd/movefunds/config.json
cmd/movefunds/createtx.go
cmd/movefunds/feeest.go
cmd/movefunds/main.go
docs/README.md
docs/offline_wallets.md

A guide explaining how to spend from a cold wallet while offline
was added along with a utility, movefunds, enabling easier signing
of offline transactions.

Add offline wallet guide and movefunds utility

---

wstakemgr/stake.go

Remove unused SendRawTransaction func in StakeStore

---

wtxmgr/db.go
wtxmgr/tx.go

The code previously would remove transactions in the forward
order when rolling back a block, which may cause faults if
there are transaction chains. Instead, roll back in the
reverse order.

Remove transactions in reverse order when rolling back blocks

---

internal/prompt/prompt.go
walletsetup.go

This will allow other tools to call the same prompts, passing these
arguments to either the wallet.Create function or to the wallet.Loader
type to create a new wallet.

Move prompting of passphrases and seed to prompt pkg.

---

rpc/legacyrpc/methods.go

Replace chainec.Sign with secp256k1.SignCompact in SignMessge RPC

---

wallet/chainntfns.go

Add back in strErrType for other possible chainClient.Notification types

---

wallet/wallet.go

Check that nextToUseIdx is > 0, otherwise throw err since account is unused

---

wallet/chainntfns.go

Remove unused const for ticket purchasing

---

wallet/wallet.go

Change n in RangeTransactions to more closely track count param

---

rpc/documentation/api.md
rpc/rpcserver/server.go
wallet/loader.go

Prevent a hang in wallet.Loader.OpenExistingWallet.

---

rpc/documentation/serverchanges.md

Refer to correct version of the gRPC Go plugin.

---

wallet/addresspool.go
wallet/wallet.go

Notifications for account address index were never added to
the address pool. Now, when new addresses are successfully
pulled, notifications will be sent out.

Add account notifications to the address pool

---

glide.lock
internal/rpchelp/helpdescs_en_US.go
rpc/legacyrpc/methods.go
wallet/wallet.go

Needs dcrd commit b58d1c4bd45c3fce89318ada51dd1288b5c5c58d
Fixes #213

rpc: Add blockheight to getstakeinfo results

---

wallet/wallet.go

rpc: fixes high reported missed counts when sstrx are first issued

---

rpc/rpcserver/server.go

Add copyright for The Decred developers.

Switch doco links to point to the Decred repo.

---

glide.lock
rpc/walletrpc/api.pb.go

Update to latest gRPC.

---

config.go

Save logs to the specified appdata directory.

---

wallet/createtx.go

wallet: limit the tx size with compressWallet/consolidate.

---

glide.lock

Update dcr* deps glide.lock for 0.5.0

---

glide.lock

Update dependencies, including 3rd party ones.

---

rpc/documentation/clientusage.md

Update gRPC client doco for changed requirements.

---

glide.lock
rpc/legacyrpc/methods.go
wallet/createtx.go
wstakemgr/db.go
wstakemgr/stake.go
wtxmgr/db.go
wtxmgr/tx.go

Update dcrutil version

---

rpc/documentation/api.md

Name WalletLoaderService correctly in documentation.

---

wallet/chainntfns.go
wtxmgr/error.go
wtxmgr/tx.go

Correctly handle duplicate blocks in the main chain.

---

wallet/chainntfns.go
wallet/wallet.go
wtxmgr/db.go
wtxmgr/tx.go

Improve error handling by ignoring less errors.

---

wallet/wallet.go

This was sitting in my local tree but I forgot to add it to the
staging area before ammending my commit.  This should have been part
of commit b9ef7b1.

Actually require the wtxmgr namespace to exist.

---

rpc/documentation/clientusage.md

Use atoms, not Satoshis, in example clients.

---

ticketbuyer/purchase.go

This was not safe for concurrent access, and by running purchases
concurrently the behavior also differed from dcrticketbuyer.
Fixes #471.

Serialize calls to ticketbuyer Purchase.

---

config.go

Revert change to default ticketmaxprice option.

---

ticketbuyer/buyer.go

ticketbuyer: Fix set split tx, ticket fees

---

ticketbuyer.go

ticketbuyer: Fix use of maxpriceaabsolute, txfee

---

config.go

bump wallet vote version to 3

---

glide.lock

Update internal glide deps for 0.7.0

---

version.go

Bump for v0.7.0

---

.travis.yml

Use latest Go patch releases on Travis-CI.

---

.travis.yml

Remove spew install from Travis-CI script.

---

ticketbuyer/buyer.go

Updated all logging levels which affect purchase to `info`
Fixes #490

ticketbuyer: better log levels for purchase result

---

config.go
dcrwallet.go
glide.lock
glide.yaml
wallet/wallet.go
walletsetup.go

Remove default values from descriptions as some are wrong.  Also, check
votebitsextended early.

config: cleanup

---

wallet/tickets.go
walletsetup.go

fix wallet creation due to new votebitsextended limits.

---

config.go

config: set pricetarget to 0 (disabled) by default.

---

config.go
dcrwallet.go

config: deprecate ticketbuyfreq. use ticketbuyer.maxperblock instead.

---

config.go
dcrwallet.go
walletsetup.go

See --ticketbuyer.maxpriceabsolute and --ticketbuyer.maxpricerelative.

config: deprecate --ticketmaxprice

---

config.go

Write --help output to stdout

---

glide.lock
rpc/legacyrpc/methods.go
rpc/rpcserver/server.go
wtxmgr/tx.go

Change 'getbalance <account>' to output the new format.

---

config.go
sample-dcrwallet.conf
ticketbuyer/buyer.go

depreciate balancetomaintain in wallet config
create balancetomaintainabsolute in ticketbuyer config
add balancetomaintainrelative with default value
support balanceToMaintain in spreadtickets calc
passed testing on testnet
Closes #541

make balance to maintain absolute and relative

---

rpc/rpcserver/server.go
wallet/utxos.go

Bump the RPC server's API patch version for this fix.
Fixes #529.

Ignore unspent stake tree outputs in WalletService.FundTransaction.

---

config.go

This fixes --create, which was erroring due to votebits being too
short with the default config, by prepending the version before any of
the create logic runs.

Set extended vote bits version before branching for --create.

---

cmd/movefunds/main.go
glide.lock
wallet/createtx.go

Update internal glide repos for v0.8.0

---

ticketbuyer/buyer.go

- fix off by one bug
- do not overbuy the maxinmempool value
closes https://github.com/decred/dcrticketbuyer/issues/24

fix maxinmempool quirks

---

config.go
ticketbuyer/buyer.go

closes https://github.com/decred/dcrticketbuyer/issues/59

fix expirydelta quirks

---

wtxmgr/tx.go

wtxmgr: fix getbalance calculations

---

ticketbuyer/buyer.go
version.go

closes https://github.com/decred/dcrticketbuyer/issues/23

use minfee if purchase slots are not full

---

config.go
sample-dcrwallet.conf
ticketbuyer/buyer.go

closes https://github.com/decred/dcrticketbuyer/issues/32

depreciate maxpricescale

---

waddrmgr/db.go

This bucket has been unused since headers syncing was introduced.
Remove it from the database with an upgrade.
While here, change the waddrmgr db version check to check for an exact
version match.  We do not want old code to be used on upgraded
databases.

Remove sync bucket with waddrmgr db upgrade.

---

wallet/udb/addressmanager.go

This one does not derive branch keys, so it can be used slightly more
efficiently when multiple branch xpubs must be derived.
While here, fix a data race caused by reading and writing cached
manager data without the write lock held.

Add method to return the account's actual xpub as well.

---

.travis.yml
goclean.sh

Use newer ubuntu release for travis

---

chain/chain.go

This change moves the wait for the session RPC response (used as a
pong) to a new goroutine that does not run directly in the queue
handler.  By moving this out to a new goroutine, the handler can
continue enqueuing and dequeueing notifications while waiting for the
session response.  Previously, if a notifiation was sent after the
session RPC was called and before the response was received, the
rpcclient main loop would block due to being unable to enqueue the
notification.
Fixes #611.

Fix RPC ping/pong deadlock and timeout issue.

---

config.go
glide.lock
netparams/params.go
walletsetup.go

Testnet reset DO NOT MERGE

---

ticketbuyer/buyer.go

ensure calculated avg ticket price is at least MinimumStakeDiff

---

ticketbuyer/buyer.go
wallet/createtx.go

This resolves double spend errors that are caused by creating and
publishing multiple transactions while in a single database
transaction.  If any of the tickets can not be purchased, the
transactions that were published remain tracked by the database.
The PurchaseTickets method has also been changed to always return the
hashes of all successfully published tickets, even if less than the
requested number could be bought.  This allows ticketbuyer to update
its statistics with the number of bought tickets if only some were
successfully sent.
While here, add a comment about why a hardcoded minconf=0 in the auto
ticket buyer code is needed.
Fixes #617.
Closes #608.

Always commit database transaction when buying tickets.

---

cmd/movefunds/main.go
cmd/sweepaccount/main.go
config.go
glide.lock
netparams/params.go
wallet/createtx.go
wallet/udb/txcommon_test.go
walletsetup.go

This updates dcrd and dcrutil deps.
Closes #619

Remove old testnet v1 variables.

---

config.go

This allows warning to be shown since it is now after the logger is
setup and it matches what the comment says about going last.
Closes #630

Move log setup to before first use of logger

---

config.go

Flush loggers before running wallet creation.

---

wallet/wallet.go

derive stake pool payment addresses properly

---

wallet/wallet.go

If the wallet was locked without any timeout, other unlock attempts
(except those with incorrect passphrases) no longer reset the timeout
and instead will keep the wallet unlocked until an explicit lock is
performed.
The logging has been improved to not log multiple unlocks when the
current lock and timeout state did not change, and an additional log
has been added for reporting that an unlocked wallet has been locked
after an invalid passphrase attempt.
Fixes #628.
Fixes #664.

Require walletlock for persistent unlocks.

---

wallet/wallet.go

When accounts were created, the first gap limit number of addresses in
each of the external and internal branches were not being watched,
causing missed relevant transactions.

Watch addresses of newly created accounts.

---

wallet/chainntfns.go

handle missed tickets even when not voting

---

wallet/udb/stake.go

Remove an unnecessary mutex grab in stakepooluserinfo.

---

wallet/wallet.go

Bump stake versions for 1.0.0 release agendas.

---

rpctest/rpcharness.go
ticketbuyer/feeest.go
ticketbuyer/price.go

Use GetBlockHeader when only The header is needed.

Use GetBlockHeader when only the header is needed.

---

rpc/legacyrpc/methods.go
rpc/rpcserver/server.go
ticketbuyer/buyer.go
ticketbuyer/mempool.go
wallet/udb/stake.go
wallet/udb/txdb.go
wallet/udb/txquery.go
wallet/wallet.go

This change attempts to make the work and RPC waiting done by
getstakeinfo as concurrent as possible.  It also adds some more
efficient DB methods to reduce the amount of data that must be read
and parsed.

Improve getstakeinfo performance.

---

wallet/wallet.go

This greatly improves startup performance when loading BIP0044 account
addresses by generating addresses and loading the dcrd transaction
filters concurrently.
Imported addresses don't currently get the same optimization but that
could be added in the future.
Fixes #708.

Improve startup performance when loading addresses.

---

rpc/legacyrpc/methods.go

legacyrpc: mark expired tickets as such

---

rpc/rpcserver/server.go

Previously, WalletService.ChangePassphrase would try to use an
actually empty byte slice as the public passphrase.  This violated the
API specification.
Fixes #734.

Handle changing empty public passphrases in gRPC server.

---

chain/chain.go

This is necessary for the addition of the existsmissedtickets RPC.

Bump required dcrd JSON-RPC API semver.

---

wallet/chainntfns.go
wallet/notifications.go

This shortens the time spent in db updates and allows for some
client notification processing to only require views.

Rework db tx handling for chain notifiations.

---

rpc/rpcserver/server.go
wallet/udb/txquery.go
wallet/wallet.go

Save published transactions if relevant.

---

rpc/rpcserver/server.go

In the current gRPC version, grpc.Errorf has been deprecated for
status.Errorf.
Closes #762.

Replace all grpc.Errorf occurences with status.Errorf.

---

wallet/tickets.go

Closes #766.
4-5x speed improvement in my testing.

tickets: use async/a map to speedup LiveTicketHashes

---

ticketbuyer/README.md
wallet/README.md
walletdb/README.md
walletdb/bdb/README.md

Update README.md files for new github parser.

---

README.md

README.md updates for grpc server going default.

---

wallet/wallet.go

This fixes an off by one that caused hangs on startup on dcrd RPC
(re)connect.
Fixes #793.

Fix off by one in active address loading.

---

rpc/documentation/clientusage.md

Update port in clientusage.md

---

config.go
dcrwallet.go
glide.lock
glide.yaml
log.go

One change of note is that this pulls in the new btclog-based logger
and removes the seelog dependency.

Update project dependencies.

---

wallet/chainntfns.go
wallet/createtx.go
wallet/rescan.go
wallet/tickets.go
wallet/wallet.go

The previous code did not include any handling of multisig output
scripts, which is worrying.

Reuse processTransaction for inserting ticket purchase.

---

wallet/tickets.go

fix GenerateVoteTx by using correct scope/variable

---

rpc/legacyrpc/methods.go

It should not assume that the chain RPC client is available.
While here, remove calls that import scripts and start rescans for
multisig outputs.  There is absolutely zero reason why this should be
performed by signrawtransaction, which should have no side effects.

Make signrawtransaction work on offline wallets.

---

wallet/udb/txdb.go
wallet/udb/txmined.go

Since they use the sstx commitments to calculate fees need to be taken into account.
Fixes #821

Fix voting authority and locked by tickets balance calculation

---

chain/log.go
loader/log.go
log.go
rpc/legacyrpc/methods.go
rpc/legacyrpc/server.go
rpctest/rpcharness_test.go
ticketbuyer/buyer.go
wallet/log.go
wallet/udb/stake.go
wallet/udb/txmined.go
wallet/wallet.go
walletdb/db_test.go

Some unused code has been left around, either because they are
constants in a group of other used constants, or the code is meant for
test purposes but isn't being called due to disabled tests.

Remove most unused code.

---

rpc/legacyrpc/rpcserver_test.go

Fatal is not safe for concurrent usage and may only be called by the
testing goroutine, not new goroutines spawned by the test.

Refactor TestThrottle to avoid incorrect Fatal usage.

---

cmd/movefunds/main.go
config.go
glide.lock
rpc/legacyrpc/methods.go
rpc/rpcserver/server.go
rpctest/rpcharness_test.go
ticketbuyer/buyer.go
ticketbuyer/mempool.go
wallet/createtx.go
wallet/wallet.go

~~NOTE: This PR contains a temporary glide redirect to https://github.com/jrick/logrotate/commit/a93b200c26cbae3bb09dd0dc2c7c7fe1468a034a, https://github.com/dnldd/dcrd/tree/decodeaddress, https://github.com/dnldd/dcrutil and https://github.com/dnldd/dcrrpcclient/tree/decodeaddress.  This will need to be removed before merging~~

Update DecodeAddress signature

---

loader/loader.go

If creating the database errors for some reason, but the file is still
written to disk, further starts will panic due to the empty database.

Defer --create error cleanup sooner.

---

wallet/addresses.go

This change simplifies the logic used to determine which addresses to
derive to begin watching and corrects a bug which resulted in gaps of
watched addresses from account branches.
While seemingly unrelated, this will fix several issues encountered
where the wallet would create double spending transactions.  The issue
was commonly seen on any wallet that purchased tickets.  In short,
ticket purchases were lingering in wallet's unmined transaction set
because the transactions were never notified by dcrd due to the wrong
set of watched addresses.  When the block at the expiry height was
processed, these ticket purchases (or any other transaction that set
expiry) would be pruned from the wallet and the previous outputs spent
by them would be marked unspent.  Later transations would then …

Avoid creating gaps in watched addresses.

---

glide.lock
rpc/legacyrpc/methods.go
wallet/udb/txmined.go

~~**NOTE: This PR contains a temporary glide redirect to https://github.com/dnldd/dcrd/commit/079daef2305a2e6c2b5a1550acc8288d218f0aa6. This will have to be removed before merging**~~
Fixes #852

multi: add unconfirmed field to Balance struct.

---

config.go
internal/cfgutil/address.go
loader/loader.go
rpc/rpcserver/server.go
ticketbuyer/buyer.go
wallet/wallet.go

Update ticketbuyer and stakeoptions config fields

---

rpc/rpcserver/server.go
rpcserver.go

It is not allowed to register additional gRPC services after the
server has started serving.  However, this was being done for optional
services that weren't ready to be used yet (e.g. the WalletServer
would be started later in the program's execution after being loaded).
This bug was discovered due to a check and fatal log in newer versions
of the Go gRPC implementation.
The fix used here is to create incomplete implementations of all
services and register each of them before serving.  The method
interceptors have added a check to verify that the service is ready
and available before the methods are called on the incomplete service.
Atomics are used to check for service readiness when necessary.  Like
before (where gRPC would panic when a service was registered multiple
times) the …

Register all gRPC services before serving.

---

glide.lock
wallet/wallet.go

pull in new agenda and bump vote versions

---

wallet/wallet.go

This can now be done locally since all block headers are saved in the
database, removing an unnecessary use of RPC.

Avoid RPC when fetching heights of block hashes.

---

wallet/udb/txunmined.go

Allow votes to double spend other invalid unmined votes.

---

ticketbuyer/purchase.go

Fixes #595.
Thanks to @raedah for his contribution.

ticketbuyer: mitigate older blocks on reconnect/resync.

---

wallet/sync.go

The previous code would search accounts concurrently but both branches
would be scanned sequentially.  In best case scenarios, this can halve
the amount of time performing the address discovery.
This change also uses the errgroup package to wait for all of the
tasks to run and merge the errors, as this is simpler and less error
prone than the error channel previously used.

Concurrently discover account branch used addresses.

---

rpc/legacyrpc/methods.go
rpc/rpcserver/server.go
wallet/udb/addressmanager.go
wallet/udb/addressmanager_test.go
wallet/udb/testdata/v5.db.go
wallet/wallet.go
wif/wif.go
wif/wif_test.go

Use the new wif package instead of the WIF code provided by dcrutil.

Copy dcrutil WIF code to wif package.

---

wallet/chainntfns.go
wallet/udb/txmined.go
wallet/udb/txunmined.go

Remove any invalid votes after every main chain tip change.

---

wallet/wallet.go

This change modifies the output of the listtransactions JSON-RPC by:
1. Removing "sends" for transactions that have a spent output
2. Reporting all "receives" of a tx before any "sends"
3. Sorting results from oldest to newest
Together, these changes make the JSON objects in the result match the
order and amounts of the listtransactions call in Bitcoin Core.

Modify listtransactions to more closely match the Bitcoin Core API.

---

rpc/legacyrpc/methods.go

This matches the behavior of Bitcoin Core's JSON-RPC API.

Return negative fees from gettransaction.

---

Gopkg.lock
wallet/chainntfns.go

resolves #830.
thanks to @jrick for providing additional info on the issue.

wallet: log rejected duplicate vote txs as info.

---

.travis.yml

travis: set GOVERSION environment properly

---

wallet/chainntfns.go

Orphan votes are votes that have become invalid by consensus rules as
the main chain tip has changed either due to a reorg or a missed vote.
These votes should not be accepted to the unmined transaction set
since they do not provide any meaningful value for the wallet, and in
many cases, these same votes have already been removed at least once
from the wallet as they are no longer valid in the new best chain.
Fixes #1034.

Reject orphan votes.

---

wallet/sync.go

Unbreak --createwatchingonly after SLIP0044 coin type upgrades.

---

rpc/legacyrpc/methods.go
rpc/rpcserver/server.go

Fixes #406
**NB** This PR has a temporary dep redirect for dcrd (it's currently using https://github.com/dnldd/dcrd/tree/ticketfee), this will have to be removed before merging.

rpc: use ticket fee if specified for PurchaseTicket.

---

wallet/udb/txmined.go

udb: return all eligible utxos if target is not specified (target=0).

---

walletdb/interface.go

Walletdb: typo

---

rpc/legacyrpc/methods.go
wallet/wallet.go

-`wallet/wallet.go` method, masterpubkey, updated to return extended key
-`rpc/legacyrpc/methods.go` updated to suit the needs of the above

Multi: Update masterpubkey to return a extendedkey

---

chain/chain.go

chain: typo

---

walletdb/interface.go

In the case a panic occurs, the panic is not recovered to keep the
original stacktrace and panic intact.

Close DB transactions after view/update panics.

---

wallet/udb/addressdb.go

udb: update bucket after cursor iteration for udb.deletePrivateKeys.

---

rpc/legacyrpc/methods.go

legacyrpc: add sort for balance accounts

---

rpc/legacyrpc/methods.go
wallet/wallet.go

This changes the amount in the gettransaction result object to include
all debits and credits instead of ignoring change amounts.  It also
removes the custom code used to generate the "details" array and
instead reuses the listtransaction code to describe the sends and
receives.
Fixes #1139.

Fix gettransaction amounts and details.

---

rpc/legacyrpc/methods.go

Make listtransactions error message more descriptive

---

run_tests.sh
wallet/udb/addressdb.go
wallet/udb/txmined.go

travis: gometalinter --enable=vet

---

config.go

Simple change that updates the --createtemp flag's description is from--datadir  --appdata
#1165

config: updates--createtemp description

---

wallet/createtx.go

Use correct input amount for ticket creation.

---

ticketbuyer/v2/tb.go

When the v2 ticketbuyer processes a block notification, it should not
simultaneously block reading of the next block notification.  This causes
deadlocks as code which writes to the subscribed tip-changed client is blocked
by an ongoing ticket purchase.
To prevent this, ticket purchases are run in their own goroutine and do not
block the read of the next block connected notification.

Avoid ticketbuyer deadlock

---

config.go

This option has not done anything for quite some time, but there was confusion
about being able to use it to as it showed up in the config.  Hide it and the
--rollbacktest options from appearing in the help output, but do not remove them
entirely from the config to prevent parsing errors if the options are set in old
config files.  Print warnings if either is specified.

Deprecate and hide --automaticrepair

---

chain/sync.go

This change introduces additional checks of the context variable during header
and cfilter fetching when catching up to a remote dcrd node in the RPC sync
mode.  This results in more responsive process shutdown if the RPC syncer is
currently fetching headers from the node when shutdown is requested.

Allow RPC startup sync cancellation

---

config.go

Add descriptions to SPV options.

---

wallet/internal/txsizes/size.go
wallet/udb/txmined.go

wallet: allow P2PK output inclusion for InputSource.

---

go.mod
go.sum
validate/go.mod
validate/go.sum

The following modules and versions are provided by this change:
github.com/decred/dcrwallet/validate@v1.0.1

Update to gcs 1.0.2 for ARM fixes.

---

testmodules.sh

This script is intended to be invoked by CI infra.

Add script to perform tests across all repo modules.

---

chain/backendwrapper.go
chain/sync.go
config.go
wallet/createtx.go
wallet/internal/txsizes/size.go
wallet/notifications.go
wallet/tickets.go
wallet/udb/txmined.go
wallet/wallet.go
wallet/wallet_test.go

Conflicts:
Gopkg.lock
Gopkg.toml
chain/sync.go

Merge 1.3 release branch fixes to master 

---

wallet/internal/txsizes/size.go

This is ideal for estimating tx sizes when the tx format is known but tx outputs have not been generated yet.

txsizes: Add EstimateSerializeSizeFromScriptSizes.

---

walletsetup.go

Display mining address when creating simnet wallets.

---

p2p/peering.go

Just unlock 2 mutexes and corrected a typo.

p2p: missing mutex unlock

---

wallet/addresses.go

This changes the behavior of the code which watches future address
usage by modifying it to watch gap limit number of addresses after the
last derived or returned address, rather than past the last address
which is marked used.  This fixes address watching issues on heavily
used wallets which derive many addresses by ensuring that all
addresses derived for an operation are part of the watched address
set.  Before this change, it was possible that addresses were returned
past the gap limit of the last address marked used, which resulted in
these addresses not being watched and mined transactions involving the
address to be missed.

Watch gap limit addresses after last returned address

---

rpc/legacyrpc/methods.go
spv/go.mod
spv/go.sum
ticketbuyer/go.mod
ticketbuyer/go.sum
ticketbuyer/v2/go.sum

Recreation of closed PR with fixes
closes #1042

legacyrpc: get rid of extraneous comment

---

wallet/addresses.go

This fixes lookup errors or missing details of addresses returned by
getnewaddress and account branch extensions performed by
accountsyncaddressindex.
Fixes #1333.

Always sync database addresses when persisting returned index.

---

internal/zero/go.mod
internal/zero/go.sum

Update to latest errors module and remove replacement.
Begin tracking the go.sum file with git.

Prepare internal/zero/v1.0.1 module

---

loader/loader.go

Enforce disablecointypeupgrades for opening existing wallets

---

go.sum
wallet/createtx.go
wallet/go.mod
wallet/go.sum

This removes the transitive dependency on dcrjson v1.

Update wallet module to mempool/v2.

---

wallet/notifications.go

This fixes a race condition detected by external tests using the `-race`
switch. The condition is fixed by using the notification server's mutex
to fully protect the currentTxNtfn member.
When sending an aggregated tx notification, only the current outstanding
events (at the time of the start of the sendAttachedBlockNotification
call) will be sent to subscribed clients.
Fix #1411

notifications: Fix race condition

---

rpc/documentation/api.md

Remove gRPC API instability notices.

---

wallet/udb/addressmanager.go
wallet/wallet.go

This new wallet function allows the extraction of the extended private
key for a given account of the wallet.

wallet: Add MasterPrivKey function

---

errors/errors.go
rpc/legacyrpc/methods.go
rpc/legacyrpc/server.go
rpc/rpcserver/server.go
spv/backend.go
spv/rescan.go
spv/sync.go
wallet/addresses.go
wallet/chainntfns.go
wallet/createtx.go
wallet/difficulty.go
wallet/notifications.go
wallet/udb/testdata/v1.db.go
wallet/udb/testdata/v2.db.go
wallet/udb/testdata/v3.db.go
wallet/udb/testdata/v4.db.go
wallet/udb/testdata/v5.db.go
wallet/udb/testdata/v7.go
wallet/udb/txdb.go
wallet/unstable.go
wallet/utxos.go
wallet/wallet.go

gofmt, unchecked errors, unused vars..

multi: please the linters

---

config.go

Deprecate reuseaddresses and disallowfree options.

Shorten and clarify config option descriptions.

---

wallet/createtx.go
wallet/udb/txmined.go
wallet/wallet.go

This change allows wallet methods for creating regular transactions and
purchasing tickets to be called concurrently.  UTXOs chosen as transaction
inputs are temporarily locked and will not be picked by other methods to avoid
double spend situations.

Allow concurrent UTXO selection.

---

wallet/internal/bdb/driver_test.go
wallet/internal/bdb/interface_test.go

bdb: re-enable bdb tests.

---

rpc/legacyrpc/methods.go
rpc/legacyrpc/server.go

Add context to RPC method handlers

---

spv/sync.go

same functionality but with proper spelling.

spv: Add SetPersistentPeers, deprecate SetPersistantPeers

---

wallet/tickets.go

These calls changed in dcrd to pass a JSON array of hash strings
instead a hex blob of concatenated unreversed hashes.  To make these
calls correctly with rpcclient/v2, RawRequest is needed.

Replace remaining rpcclient.Exists*Tickets calls

---

wallet/cointype.go

This fixes a bug where grpc's NextAddress calls would panic due to the
account's xpub being nil.
This only affected newly created wallets immediately after the coin type
upgrade.

wallet: Store account xpub in address buffer after upgrade

---

chain/sync.go

This change adds a mutex to protect the concurrent access of the RPC
syncer's sidechain block management.  This fixes a new bug introduced
when the RPC client library was recently switched.  The old code used
to only process any notifications after the startup sync had
completed, while the new notifications may be processed at any time
during headers fetching and rescanning, allowing a data race between
the sidechain map whenever a block was connected and startup sync was
still ongoing.
Fixes #1513

Protect concurrent access to chain.Syncer.sidechains

---

rpc/jsonrpc/methods.go

This updates `listsinceblock` to allow listing 0-conf txs and corrects the `last_block` result field behaviour.
Fixes #1309.
Tested on simnet with ticket purchases.
```
~/harness/vwallet                                                                                                                                                                                       
❯ ./ctl listsinceblock 000005b17355b5ee115278f8637339cab3b428a2c7fb2d98312ae5e802ed94cd 3                                                                                                               
{                                                                                                                                                                                                       
"transactions": [ …
```

multi: list 0 confirmation txs for listsinceblock.

---

loader/loader.go

This is not used anywhere in the project and, being part of the main
module, the loader package is not designed for external consumption.

Remove Loader.SetDatabaseDriver

---

wallet/wallet.go

It is a bad idea to try and register all watched outpoints from a
single call, due to the network backend possibly being a dcrd instance
and JSON-RPC being used.  Partition the data into sets of 64 outpoints
each and perform multiple calls instead of registering all of them
single-shot.
This will reduce the likelihood that a send timeout is hit on large
data sets.

Partition watched outpoints into multiple LoadTxFilter calls

---

go.mod
go.sum
wallet/go.mod
wallet/go.sum
wallet/wallet.go

Note: The wallet will not follow the fork yet if it activates.  This will require modifications to the block validation logic.

Enable vote for header commitments agenda

---

wallet/wallet.go

There is no reason to load the transaction filter with watched
addresses while having a database view open the entire time.  Doing so
causes unnecessary database contention and memory usage.

Derive and load watched addresses outside of DB view.

---

wallet/addresses.go

Depends on #1592.
There is no reason to do this when it is known that transaction
history is missing, and the addresses that should be watched can not
be determined.

Do not watch future addresses when transactions are not fully synced.

---

wallet/mixing.go

This avoids burning through addresses (there is no wrapping, because
these addresses may not be reused) if the CSPP server cannot be
successfully dialed.

Derive mixed output address after dialing CSPP server

---

go.sum
wallet/createtx.go
wallet/go.mod
wallet/go.sum
wallet/log.go
wallet/mixing.go

Move all cspp client logging to debug level in the wallet log
subsystem.

Upgrade cspp module for handling of server-sent errors

---

assets/assets.go
go.mod
go.sum

This updates the wallet module to their latest versions as tagged from
master, and backports the following changes made to the main module:
1fb7aff5a03f3235178111cace5dffdd07f9b26c

Update submodules and backport main module improvements

---

go.mod

This package provides definitions and registration for the auditreuse
method.

Update to recently-tagged JSON-RPC types package

---

wallet/udb/addressmanager.go

Imported xpub accounts which do not contain any data (including no
nonce) for the account xpriv should not error during reading.
Instead, these accounts should be treated as if the wallet was locked
and the key could not be decrypted.

Do not attempt to decrypt missing account xprivs

---

wallet/wallet.go

While the database was being properly updated for import xpub
accounts, and the decryption errors for the missing nonce have been
corrected when no encrypted private key was recorded, the wallet would
eventually die in a panic on the next attached block following an
importxpub RPC invocation due to a nil pointer dereference of the
(missing) in-memory account xpub.  This change corrects this bug by
adding an account buffer for the imported account (instead of only
being read on next dcrwallet startup from the database) and watches
the initial gaplimit number of children in both BIP0044 branches.

Fix panic on next attached block following importxpub

---

go.mod
go.sum

This fixes a panic for the upcoming 1.5.1 release.

Update wallet module to v3.2.1

---

wallet/wallet.go

This unifies the three existing cases where a block range is required in
the wallet to a single function in order to simplify its usage.
This also fixes an outstanding bug in block determination in
GetTransaction.

wallet: Unify blockRange determination

---

wallet/discovery.go

Fixes an out-of-bounds error during account discovery with imported
accounts that have high account numbers.

Fix index to script's account in usage slice

---

wallet/stakepool.go

Check for enabled VSP features in StakePoolUserInfo

---

go.mod
go.sum
p2p/peering.go
rpc/client/dcrd/calls.go
rpc/client/dcrd/json.go
spv/backend.go
validate/validate.go
wallet/network.go
wallet/network_test.go
wallet/peer_test.go
wallet/udb/upgrades.go

While here, update gcs to v2.0.1.

Remove all gcs (v1) usage

---

wallet/addresses.go

The wrapping for creating KnownAddress types from wrapping a
udb.ManagedAddress was appearing in multiple places, and causing
difficulty for readers and reviewers.  This change separates the
wrapping logic to a separate reusable function.

Move udb.ManagedAddress wrapping to one func

---

rpc/documentation/clientusage.md

- Updated client usage doc to point to correct package path
- Added `go.mod` to facilitate local client development using `replace`

walletrpc doc fix+go.mod addition

---

go.mod
go.sum

Update to wsrpc 2.3.3 for data race fix

---

p2p/peering.go

Extracted from #1487 
(Also updated a bit as discussed in the dev channel.)
This adds the possibility of multiple concurrent requests for blocks
from remote peers.
Requesting the same block multiple times concurrently from a peer is an
error. Previously this wasn't a problem since the only place that
requests blocks is the syncer and it correctly de-dupes requests.
In a future commit we'll introduce the ability of external clients to
ask for blocks, so concurrent syncer and external requests could race,
leading to problems.
This fixes the issue by keeping track of in-flight requests and allowing
multiple callers to request the same block from the same peer.

p2p: Allow concurrent block requests

---

wallet/createtx.go

This change fixes a lock ordering issue between acquiring the address
and db locks.  After this change, the order of acquired locks when
deriving the voting and subsidy addresses when buying tickets is to
first acquire the address mutex, and then the db lock.  This is
accomplished by moving the address returning functions outside of a db
update.
Since the other order (acquiring the db lock first, and then the
address lock) is incorrect, the addrFunc signature is also changed to
remove the now unused maybeDBTX parameter, and this func will always
call persistReturnedChild with a nil dbtx so that a transaction is
only opened with the address lock held.
Fixes #1793.

Fix lock ordering

---

ticketbuyer/tb.go

Ticket purchasing actions were already being skipped when transactions
were not synced with the last recorded block, but this check wasn't
being applied to change account mixing.  Move this check further up so
that it applies to both activities.

Skip CSPP change account mixing when wallet is unsynced

---

wallet/udb/addressmanager.go

The address manager recorded all returned private keys in map and,
when locked, would iterate over each to zero them.  This created a
memory leak for any wallet that was never locked, such as some
ticketbuyers and all voter wallets.  Removing this map and always
returning newly derived or decrypted priate keys plugs, and moving the
key zeroing to the caller plugs this leak.
The PrivateKey method now returns a function which zeros the key
immediately, rather than blocking the address manager from zeroing
keys before callers are finished with them.  This keeps the changeset
small (rather than modifying the API and requiring callers to
explicitly call the Zero method of the returned key) without changing
any observable functionality.

Do not cache returned private keys for future zeroing

---

internal/prompt/prompt.go
walletsetup.go

This was not possible previously because the tty was not able to be
read for the passphrase.  To solve this issue, when the private
passphrase config option (--pass) is not empty, its value is used for
the private passphrase rather than prompting.
This also fixes a bug with the input buffering when reading the seed
could otherwise cause the wallet to loop forever from valid creation
input.
As a demonstration:
```
$ cat ~/var/input.txt
n
y
8dce73948a6d51fd56530a0ee12633ef53df3add4bdd853b1ec7e3046b72934c
$ [ -d /tmp/dcrwallet ] || mkdir /tmp/dcrwallet
$ dir=$(mktemp -d -p /tmp/dcrwallet)
$ dcrwallet --create --appdata=$dir --pass=password < ~/var/input.txt
2020-08-04 18:36:52.568 [WRN] DCRW: open /tmp/dcrwallet/tmp.zGjKZVtpW5/dcrwallet.conf: no such file or directory
Do you want to add an …
```

Allow wallets to be created from standard input

---

p2p/peering.go

The previous change was incorrect and caused errors reading the
response body, because the request context was closed too early.

Cancel seeder requests after reading response

---

wallet/chainntfns.go

stakePoolEnabled is asserted above in this if block to be true, so
do not test inside the block for false.

Remove impossible branch

---

go.mod
go.sum

This change results in simnet votes becoming standard transactions.

Update chaincfg module to latest master

---

vsp/payfee.go
vsp/vsp.go

I am breaking #1840 in smaller and more related PRs, asked by @dajohi

vsp: split vsp fee creation and fee payment

---

wallet/createtx.go

findEligibleOutputsAmount was missing coin maturity checks when
returning spendable outputs.

wallet: add missing maturity checks

---

internal/rpc/rpcserver/server.go
wallet/txrules/rules.go
wallet/udb/txmined.go
wallet/wallet.go

We wish to add a JSON-RPC method which calls the wallet's
PublishTransaction method, but the enabling or disabling of high fee
checks works differently between the JSON-RPC and gRPC servers.  In
the JSON-RPC server, the method has its own default value for this
setting rather than using the wallet application config, while the
gRPC server uses the application settings.  One possible way to deal
with this would be to add another bool parameter for the setting to
the PublishTransaction signature.  This change instead keeps the
function signature the same, but requires callers to perform high fee
checks (if any), and gives more flexibility as to how this check is
enabled.

Move PublishTransaction high fee check to caller

---

wallet/createtx.go

this is needed to so a reserve failure unlocks previous successes.

wallet: move unlocking defer

---

config.go
dcrwallet.go
internal/rpc/jsonrpc/methods.go
sample-dcrwallet.conf
vsp/feeaddress.go
vsp/payfee.go
vsp/poolfee.go
vsp/ticketstatus.go
vsp/vsp.go

config: update --vsp.server to take a URL

---

internal/rpc/rpcserver/server.go

This implements the VSPHost and VSPPubKey options that were previously added to the purchase ticket grpc request.

rpc: Implement purchase tickets for new VSP

---

wallet/createtx.go

This is a similar fix as fb6e6d2831, but deals with the condition that
enough balance and utxos were able to reserve all of the outputs to
pay vspd fees, and the low balance was later hit during the creation
of the split transaction.

Purchase fewer tickets than requested with low balance

---

internal/vsp/vsp.go

Use returns instead of breaks when inside of a select statement and
the goal was to break out of an outer loop.  The break statement will
break out of the switch statement, not the loop.
Do not queue items from Process.  This was needlessly recursive
(Process -> queue -> Process) and caused the first Process call to
return the original error before attempting the second process
(despite waiting for 2 minutes in the foreground), by which time the
second Process call could fail due to the wallet locking after the
first Process call returned.
Remove a log of expected context cancellation errors.

Fix some strange vsp package bugs

---

x509_test.go

This adds retry logic with a timeout to the untrusted certificate test to ensure slower environments, such as the CI environment, give time for the mock TLS HTTP server to start listening.
Fixes #1884.

x509: Fix false positive in untrusted cert test.

---

rpc/documentation/clientusage.md

Update Go gRPC sample code

---

wallet/chainntfns.go

The map of recently published transactions was being incorrectly
deleted from, by using the block hashes with relevant transactions,
rather than removing the transactions themselves by the tx hash.
While here, move this logic below the database update to prevent any
modification of the in-memory recently-published transactions in case
the update fails.

Remove recently published transactions as blocks are attached

---

wallet/chainntfns.go

The SPV syncer may call Wallet.ChainSwitch concurrently for multiple
peers, and if this occurs and the chain had already been extended by
data provided by another peer, a logic race made it possible for the
syncer to error and restart due to a total work check.  This change
works around the logic race by doing one final check while inside the
database update, where if the tip block of the chain being attached is
equal to the tip recorded in the database, no changes are performed
and the method does not error.
---
depends on #1908.

Do nothing in ChainSwitch if already at same tip block

---

internal/vsp/feeaddress.go
internal/vsp/types.go

Requires https://github.com/decred/vspd/pull/205

vsp: send parent tx of ticket in the feeaddress request

---

spv/sync.go

The connectingRemotes map must not be unlocked and relocked between
checking for a connecting peer, and marking the peer as currently
connecting.
Fixes #1798.

Avoid logic race causing duplicate outbound connections

---

p2p/peering.go
spv/sync.go

This fixes a layering issue where peers were always disconnected by
the SPV syncer if they did not advertise a sufficiently-high last
block height, when this operation is better performed by the peer code
which integrates with the address manager.  Erroring in the handshake
results in the addresses not being marked as "good" in the address
manager prior to immediately disconnecting from the peer for not being
synced.

Check for sufficiently-synced height during p2p handshake

---

p2p/peering.go
spv/sync.go

Do not continue conn attempts on permanent errors

---

wallet/udb/txmined.go

This does not affect the balance reporting, but only the outputs
returned by methods such as listunspent, or what inputs are selected
for funding other transactions.
Fixes #1940

Do not consider unpublished TxOuts UTXOs or use as tx inputs

---

internal/uniformprng/prng.go

These methods will be useful for creating random time.Duration values,
which is an int64 type.

Add Int63/Int63n methods to uniformprng.Source

---

internal/rpc/jsonrpc/methods.go
rpc/jsonrpc/types/methods.go

This results in a bijection of methods to command types when
registering with dcrjson, to avoid errors/panics during registration.

Define new types for dcrd commands we implement

---

wallet/mixing.go

There is no reason to connect early.

Move connection to CSPP server below fee estimations

---

wallet/createtx.go
wallet/wallet.go

After we create an extra split output to deal with UTXO contention in
a VSP ticket purchase, there is no need to perform UTXO selection
again to reserve an output for a single VSP fee payment. Add an
unexported field to the purchase ticket parameters so that upon
reentry, this output can be used directly.

[release-v1.6] Use extra split output rather than selecting random UTXOs

---

internal/rpc/rpcserver/server.go

This is an old and incorrect ChangeAccount being set.  It's set correctly further down.

[tb] Remove extra ChangeAccount

---

wallet/createtx.go

If there was not enough remaining balance to reserve outputs to pay
for one ticket (after reserving outputs for paying a VSP fee), but the
sum of the already-reserved UTXOs and the remaining UTXOs in the
account do sum to enough value to create the additional split
transaction, that split transaction should still be created.  Not
including these outputs in the additional split was causing confusing
"insufficient balance" errors for users, as not all of the UTXOs in
the account were being considered.
For example, consider a ticket price of 100 and an account with two
UTXOs of 60.  One output would be reserved for paying the fee, but
reserving additional outputs to pay for a single ticket would fail,
and this second output of 60 was not being included in the logic for
creating the …

Include remaining UTXOs for additional split during low balance

---

wallet/udb/addressmanager.go

When an account is individually encrypted, whether or not to derive
the private key instead of the public key depends on whether the
account is unlocked, rather than querying the unlocked state of all
other accounts without individual encryption keys.

Derive correct public/private key for encrypted accounts

---

internal/rpc/rpcserver/server.go
ticketbuyer/tb.go

This is a cherrypick of 73ef730e0d99a29cc715f1a4bb1546b079c1452b to the release-v1.6 branch.

[release-v1.6] Check for password when running buyer

---

internal/rpc/rpcserver/server.go

If the VSP client had already been created, with different accounts in
its global policy, these old accounts would have been used rather than
the intended accounts from the request.  By specifying the particular
policy to use when syncing each ticekt, this issue is avoided.

Use request's policy for syncing failed VSP tickets

---

internal/vsp/feepayment.go

There should not be any feePayments performing background tasks unless
they are tracked by the VSP and are unique.
Issue spotted by @matheusd.

Save all feePayments to the jobs map

---

internal/vsp/feepayment.go

When a feePayment job is removed, any currently scheduled task should
be unscheduled.
When executing deferred functions that may reschedule another task, do
not schedule any task if the job has been stopped.

Avoid VSP scheduling inconsistencies

---

internal/vsp/feepayment.go

The submitPayment method did not check the status code for any API
errors.  This was causing submitPayment to be rescheduled by its own
defer.
Instead of ever scheduling submitPayment, schedule reconcilePayment
instead.  This method does check the status code, and will properly
handle the various states such as fees already being confirmed or
received.
This makes the state machine quite a bit easier to follow as well,
since more scheduling logic will be driven directly by
reconcilePayment.

Do not schedule submitPayment tasks

---

ticketbuyer/tb.go

This results in up to --ticketbuyer.limit number of separate
connections to the CoinShuffle++ server triggered by each connected
block, instead of a single connection that funds several ticket
purchases but only creates a single change output.
This will result in slower mixed ticketbuying if the funding account
has limited UTXOs, as separate requests means that each individual
ticket purchase must be funded by a separate set of UTXOs.

Limit mixed autobuyer ticket purchases to one per cxn

---

internal/rpc/rpcserver/server.go

Now that we are using the account locking we need to remove this check.

[vsp] Remove wallet unlocked check

---

internal/rpc/rpcserver/server.go
wallet/discovery.go

Hadn't properly returned the expected DiscoverUsageResponse on a successful request.

rpc: Fix DiscoverUsage request

---

spv/sync.go

This fixes a potential race issue where the sidechain forest is accessed
outside the lock.
Specifically, the `.sidechains.HasSideChainBlock` needs to happen with `sidechainMu` held.

spv: Move sync ops inside sidechain mutex

---

internal/rpc/jsonrpc/methods.go

There have been several new requests and additions since the last time
this was bumped.

Bump JSON-RPC API minor version

---

wallet/wallet.go

Fix listreceivedbyaccount panic with imported BIP0044 accounts

---

internal/rpc/jsonrpc/methods.go

This updates the JSON-RPC server's `walletinfo` handler so that it ensures a known network backend type is in use.
This also sets the `DaemonConnected` field according to the number of remote peers when in SPV mode.

jsonrpc: handle invalid network backend in walletinfo

---

p2p/peering.go

The verack message is not necessarly the second message sent by a
peer.  There is also no reason to wait for it, since the protocol
version has already been negotiated (and failure to do this would
cause disconnect).

Ignore and do not wait for received verack

---

internal/vsp/vsp.go

When comparing VSP and local vote choices, we should not range over the VSP choices because this could be an empty map, which will lead to the VSP never being updated.

vsp: Fix bug where VSP vote choices not updated.

---

internal/rpc/jsonrpc/methods.go
internal/rpc/rpcserver/server.go

This also includes the missing error handling from #2130

Pull VSPHost from DB rather than config.

---

rpc/regen.sh

The script would previously return with error code 1.

Fix regen.sh return code if $UID is unset

---

wallet/wallet.go

The expired slice was accessed out-of-bounds due to dcrd no longer
supporting the existsexpiredtickets method.  Avoid these RPCs entirely
(including existslivetickets) by instead counting missed or expired
tickets by the block heights of their revocations.  (This is not
necessarily 100% accurate for tickets that were missed prior to the
activation of DCP0009, but there is no better way for wallet to
provide this result without tracking the entire ticket pool.)
Fixes #2163.

Prevent panic in RPC-mode getstakeinfo

---

.github/workflows/go.yml
dcrwallet.go
internal/rpc/rpcserver/server.go
wallet/createtx.go
wallet/internal/bdb/interface_test.go
wallet/udb/txdb.go
wallet/udb/vsp.go
wallet/wallet.go
wallet/walletdb/interface_test.go

build: Test against Go 1.19

---

wallet/discovery.go

Resolves https://github.com/decred/dcrwallet/issues/2199.
As per this suggestion https://github.com/decred/dcrwallet/issues/2199#issuecomment-1415990722 seems easier to fix than I originally thought.

addresses: discovery deadlock

---

config.go
internal/rpc/jsonrpc/config.go
internal/rpc/jsonrpc/methods.go
rpcserver.go

Don't override with a hard-coded value of 0.2e8.

jsonrpc: Respect configured VSPMaxFee.

---

internal/vsp/feepayment.go
internal/vsp/vsp.go

Spotted by @buck54321 in decred/vspd#382

vsp: Add missing mutex locks.

---

internal/uniformprng/prng.go
wallet/createtx.go

This introduces a random delay during the publishing of tickets during mixed ticket buying.  After the mixed split transaction has been created and published, random times picked between 20-60s are created for each ticket being created, and publishing of these tickets will not occur until the trickle duration has been reached.

Trickle tickets during mixed buying

---

wallet/udb/vsp_test.go

Just adding tests for existing behaviour, no changes to production code.

udb: Add tests for serializing VSP data.

---

internal/vsp/feepayment.go

Previously the live & expiry heights were only being set once upon feePayment initialization, which meant that an unmined ticket added to the VSP client would have heights set to zero forever.
With this change, if either of the values are found to be zero, we check if the ticket has been mined yet and the heights are recalculated to their correct values if so.

vsp: Recalculate ticket live/expiry heights.

---

spv/backend.go
spv/sync.go

This changes the initial cfilter fetch to request cfilters only for the best sidechain.  This avoids having to perform work for sidechains that are not (and will never) become the main chain.
Additionally, this refactors the initial cfilter fetching logic to a separate function.  In the future, this will help in refactoring the cfilter fetching to perform it in a batched fashion.

spv: Request cfilters only for best chain

---

spv/backend.go
spv/sync.go

This moves all the header fetching logic from the old getHeaders (renamed to initialSyncHeaders) to a separate getHeaders function.
In the future, this will make it easier to refactor the initial sync header fetching to perform this stage in parallel to the other stages.
This is mostly a code moving commit.

spv: Refactor initialSyncHeaders

---

p2p/peering.go

It reads better to have a dial timeout of 10s followed by a handshake with a 5s timeout, instead of relying on the outer context wrapping in a 30s overall timeout to connectOutbound.
The previous code could allow a handshake up to 20s but this was only to deal with the potential of there being reconnect attempts, which are now gone.

p2p: avoid strange context timeout wrapping

---

chain/sync.go

This introduces an additional mode for fetching headers in RPC mode when a few headers are missing after the initial sync process has completed. In this mode, headers are fetched and rescanned on dcrd's side one by one before being handed over the the standard blockConnected handler.
This is meant to fix an issue when loading wallets with a very large number of used addresses on slow computers or VMs. In this situation, it may happen that the LoadActiveDataFilter call takes so long to be processed (in the order of several minutes) that a new block is found but its notification is missed (due to the wallet not yet having subscribed to block notifications).
This would trigger a (new) full initial sync to be performed, with a subsequent full address reload, potentially getting the wallet …

chain: Fetch missing blocks one by one after initial getheaders

---

internal/prompt/prompt.go
walletsetup.go

This simplifies the provisioning process as these xpubs will now be included in the address discovery and initial rescan, without manually requiring a RPC call to add them and rescan again for them.

Prompt for account xpub imports at wallet creation

---

wallet/rescan.go

RPC rescans were performing batching of 2000 blocks at a time, but separate database updates would occur for each block that contained any matching transactions.  To improve rescan performance, batch the update using a background goroutine worker when the total amount of transactions exceeds a value (currently untuned, but I observe significant rescan times with a first try guess of 256).

Batch rescan database updates

---

chain/sync.go
config.go
dcrwallet.go

When the new config option --dcrdauthtype=clientcert is set, a client certificate and key (set by --dcrdclientcert and --dcrdclientkey) will be used to authenticate the dcrd JSON-RPC connection instead of basic authentication with a user and password.
Closes #2101.

Allow client certificate authentication to dcrd RPC

---

internal/rpc/jsonrpc/methods.go

jsonrpc: assign mixed-split account for rpc tickets

---

chain/sync.go
go.mod
go.sum

This update includes debug logging added to mixpool's AcceptMessage method, so some additional and now duplicate logging can be removed.  This also has the side effect of logging the same messages in SPV mode, and with matching messages to dcrd also running with mixpool debug logging.

Update to latest mixing module

---

spv/sync.go

Similar to dcrd, we want SPV wallets to maintain a minimum number of peers that support the mixing protocol version.  This will be especially important after dcrwallet is updated to a mixclient branch that submits PR messages over the entire duration before the epoch occurs, as any errors for failed message sends due to not having a single mixing-capable peer connected would be delayed far into the future.

Attempt cxns to >=3 mixing-capable peers

---

walletsetup.go

walletsetup: Return birthday prompt error.

---

go.mod
go.sum

This includes a fix for a potential panic if address generation errors, and will report the error at the error log level rather than being hidden behind debug.

Update to latest development mixing module

---

dcrwallet.go
ticketbuyer/tb.go

Ensure autobuyer always uses the configured voting account

---

wallet/txauthor/author_test.go

remove duplicate package import

chore: remove duplicate package import

---

wallet/mixing.go

When an output is skipped during an account mix due to current throttling, emit a debug log that this throttling occurred.
If any outputs selected during the mix account request could not be assigned a split denomination, give this a unique debug log as well.
Add an additional log for each call to MixAccount reporting the total count of selected outputs, and how many were successfully mixed.
While here, remove the log suppression for exceeding the total number of Tor circuits.  This is no longer relevant for peer-to-peer mixing.

wallet: Improve MixAccount debug logging

---

wallet/createtx.go

One of consolidate's uses is to sweep up existing dust.  It would be quite ironic for it to create an additional dust output.
Adding this dust check also causes consolidate to error sooner when the estimated fee is greater than the total input sum, preventing creating a transaction output with a negative amount.
Closes #2489.

Check that consolidate output is not dust

---

rpc/client/dcrd/calls.go

If a huge number of addresses need to be checked they should be sent to dcrd in batches to avoid breaching its hard-coded read limit.
This is necessary in cases where gap limit is set greater than ~441k.

Batch calls to dcrd existsaddresses RPC.

---

wallet/wallet.go

This fixes a data race introduced by #2516.

wallet: Fix watch HD addrs data race.

---

wallet/udb/addressdb.go
wallet/udb/addressmanager.go
wallet/udb/txdb.go
wallet/wallet.go

chore: Typos fix

---

wallet/vsp.go

This fixes a bug where a batch of tickets added to the vsp client would not be fully processed if one of the tickets already had a confirmed fee.

vsp: Ensure all tickets are processed.

---

wallet/chainntfns.go
wallet/udb/txunmined.go

Unmined tickets are removed when the required ticket price changes, invalidating them for future blocks.  Wallet makes an attempt to remove these, but may use the incorrect sdiff value (the sdiff from the current best block header, not the next required block) when it is at the end of the current ticket price window.  Calculate the correct value (which is only possible once DCP0001 is activated), or otherwise do not prune these unmined tickets at all using the potentially incorrect value.

Fix sdiff used for unmined ticket pruning

---

chain/sync.go
internal/rpc/rpcserver/server.go
p2p/peering.go
spv/sync.go

Various minor bits of housekeeping plus fixing an extremely unlikely panic in `StartWalletService`.

Tidy up use of atomics.
